<template>
  <div>
    <DataLinkage
      ref="DataLinkage"
      :fields="diyList"
      :chooseData="data"
      :model.sync="code5"
    >
    </DataLinkage>
  </div>
</template>

<script>
import DataLinkage from "./components/diy-DataLinkage";
export default {
  data() {
    return {
      code5:'',
      diyList: [
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "42deb4bb-3773-4ae6-94a9-374d93f039ed",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "名称",
          Name: "Mingcheng",
          NameConfirm: true,
          Type: "varchar(100)",
          Code: "",
          Component: "Text",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-01 13:43:12",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 100,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"","EnableSearch":false,"NumberTextStep":1,"NumberTextPrecision":0,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"","V8CodeBlur":"","DividerPosition":"left","DataSource":"","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"","SelectSaveField":"","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":false,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"","TableChildSysMenuId":"","TableChildSysMenuName":"","TableChildFkFieldName":"","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: null,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        },
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "52c59244-c396-4e63-a45b-5063cad09c1a",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "免运费",
          Name: "mianYF",
          NameConfirm: true,
          Type: "bit",
          Code: "",
          Component: "Switch",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-01 13:51:16",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 350,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"","EnableSearch":false,"NumberTextStep":1,"NumberTextPrecision":0,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"if (V8.Form.mianYF==true){\\nV8.FieldSet(\'Yunfei\',\'Visible\',false)\\n}else{\\nV8.FieldSet(\'Yunfei\',\'Visible\',true)\\n}\\n\\n","V8CodeBlur":"","DividerPosition":"left","DataSource":"","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"","SelectSaveField":"","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":false,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"","TableChildSysMenuId":"","TableChildSysMenuName":"","TableChildFkFieldName":"","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: 12,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        },
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "48c94866-624b-4d89-93a4-c5c6b1c4356e",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "运费",
          Name: "Yunfei",
          NameConfirm: true,
          Type: "decimal(18, 1)",
          Code: "",
          Component: "NumberText",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-01 13:46:52",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 400,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"","EnableSearch":false,"NumberTextStep":0.5,"NumberTextPrecision":1,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"","V8CodeBlur":"","DividerPosition":"left","DataSource":"","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"","SelectSaveField":"","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":false,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"","TableChildSysMenuId":"","TableChildSysMenuName":"","TableChildFkFieldName":"","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: 12,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        },
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "4994480c-8e9c-4f78-911b-7cb9a6e1d0d5",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "类别",
          Name: "Leibie",
          NameConfirm: true,
          Type: "varchar(100)",
          Code: "",
          Component: "Select",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-01 14:43:57",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 500,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"SELECT Id,Mingcheng \\nFROM Diy_Commodity_category WHERE IsDeleted=0","EnableSearch":true,"NumberTextStep":1,"NumberTextPrecision":0,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"let sql=\\"SELECT Id,Mingcheng FROM Diy_Commodity_classification WHERE IsDeleted=0 AND LeibieID=\'\\"+V8.ThisValue.Id+\\"\'\\";\\nV8.RunSqlGetList(sql, function(data){ \\n\\tV8.FieldSet(\'Fenlei\',\'Data\',data);\\n})","V8CodeBlur":"","DividerPosition":"left","DataSource":"Sql","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"Mingcheng","SelectSaveField":"Mingcheng","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":false,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"","TableChildSysMenuId":"","TableChildSysMenuName":"","TableChildFkFieldName":"","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: null,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        },
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "afa04bb0-cc08-4a4b-b345-0a6d6217bcb1",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "分类",
          Name: "Fenlei",
          NameConfirm: true,
          Type: "varchar(100)",
          Code: "",
          Component: "Select",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-02 14:17:46",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 530,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"","EnableSearch":true,"NumberTextStep":1,"NumberTextPrecision":0,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"let sql=\\"SELECT Id,Mingcheng FROM Diy_Commodity_segmentation WHERE IsDeleted=0 AND FenleiID=\'\\"+V8.ThisValue.Id+\\"\'\\";\\nV8.RunSqlGetList(sql, function(data){ \\n\\tV8.FieldSet(\'Xifen\',\'Data\',data);\\n})","V8CodeBlur":"","DividerPosition":"left","DataSource":"","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"Mingcheng","SelectSaveField":"Mingcheng","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":false,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"","TableChildSysMenuId":"","TableChildSysMenuName":"","TableChildFkFieldName":"","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: null,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        },
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "6c471944-b2ef-49f9-8b1b-348fdb1fd5cd",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "细分",
          Name: "Xifen",
          NameConfirm: true,
          Type: "varchar(100)",
          Code: "",
          Component: "Select",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-02 14:17:47",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 560,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"","EnableSearch":true,"NumberTextStep":1,"NumberTextPrecision":0,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"","V8CodeBlur":"","DividerPosition":"left","DataSource":"","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"Mingcheng","SelectSaveField":"Mingcheng","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":false,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"","TableChildSysMenuId":"","TableChildSysMenuName":"","TableChildFkFieldName":"","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: null,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        },
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "a6e92fd0-380b-491b-97c4-97f70539b32e",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "封面图",
          Name: "FengmianT",
          NameConfirm: true,
          Type: "varchar(50)",
          Code: "",
          Component: "ImgUpload",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-02 09:41:22",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 600,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"","EnableSearch":false,"NumberTextStep":1,"NumberTextPrecision":0,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"","V8CodeBlur":"","DividerPosition":"left","DataSource":"","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"","SelectSaveField":"","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":false,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"","TableChildSysMenuId":"","TableChildSysMenuName":"","TableChildFkFieldName":"","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: null,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        },
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "e2c814b5-bcee-45ed-8ab3-474ed605ce77",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "轮播图",
          Name: "LunboT",
          NameConfirm: true,
          Type: "mediumtext",
          Code: "",
          Component: "ImgUpload",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-02 09:42:15",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 650,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"","EnableSearch":false,"NumberTextStep":1,"NumberTextPrecision":0,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"","V8CodeBlur":"","DividerPosition":"left","DataSource":"","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"","SelectSaveField":"","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"","TableChildSysMenuId":"","TableChildSysMenuName":"","TableChildFkFieldName":"","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: 24,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        },
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "aec2d8e7-9ac4-4cdb-9f88-2860d603713e",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "商品详情",
          Name: "ShangpinXQ",
          NameConfirm: true,
          Type: "mediumtext",
          Code: "",
          Component: "RichText",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-02 09:39:53",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 900,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"","EnableSearch":false,"NumberTextStep":1,"NumberTextPrecision":0,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"","V8CodeBlur":"","DividerPosition":"left","DataSource":"","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"","SelectSaveField":"","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":false,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"","TableChildSysMenuId":"","TableChildSysMenuName":"","TableChildFkFieldName":"","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: 24,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        },
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "dcd03597-bbac-49e1-802e-72aa3e72ed22",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "商品参数",
          Name: "ShangpinCS",
          NameConfirm: true,
          Type: "",
          Code: "",
          Component: "TableChild",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-02 10:02:00",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 950,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"","EnableSearch":false,"NumberTextStep":1,"NumberTextPrecision":0,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"","V8CodeBlur":"","DividerPosition":"left","DataSource":"","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"","SelectSaveField":"","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":false,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"c2855ce6-5320-4519-a28a-95c2f6d867ee","TableChildSysMenuId":"e7762933-8faf-47c3-835f-5371b2eaa937","TableChildSysMenuName":"商品参数","TableChildFkFieldName":"ShangpinID","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: 24,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        },
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "413fd9ba-4cea-446c-89f8-e028b0f9c063",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "商品库存",
          Name: "ShangpingKC",
          NameConfirm: true,
          Type: "",
          Code: "",
          Component: "TableChild",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-01 14:34:14",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 1000,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"","EnableSearch":false,"NumberTextStep":1,"NumberTextPrecision":0,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"","V8CodeBlur":"","DividerPosition":"left","DataSource":"","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"","SelectSaveField":"","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":false,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"c8236e7c-2859-4d3d-aed0-a4a68e7674bc","TableChildSysMenuId":"50d9db47-d334-429d-86af-73e010ddc95c","TableChildSysMenuName":"商品库存","TableChildFkFieldName":"ShangpinID","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: 24,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        },
        {
          TableName: "Diy_Commodity_information",
          TableDescription: "商品信息",
          Id: "87c82524-8209-46d0-a0d2-a63079de0bef",
          TableId: "7363dcb9-ffac-4fdf-ab04-ac88df85042f",
          Label: "商品评论",
          Name: "ShangpinPL",
          NameConfirm: true,
          Type: "",
          Code: "",
          Component: "TableChild",
          Description: "",
          NotEmpty: false,
          Visible: true,
          Readonly: false,
          CreateTime: "2021-11-01 15:01:44",
          UpdateTime: "2021-11-22 16:31:45",
          UserId: "00000000-0000-0000-0000-000000000000",
          Sort: 1100,
          Tab: "",
          OsClient: "shopdiy",
          IsDeleted: false,
          Data: "[]",
          Config:
            '{"ParamData":{},"KeysAddVisible":false,"KeysAddVModel":"","Sql":"","EnableSearch":false,"NumberTextStep":1,"NumberTextPrecision":0,"NumberText":0,"NumberTextMath":"","NumberTextBtn":true,"NumberTextBtnPosition":"right","V8Code":"","V8CodeBlur":"","DividerPosition":"left","DataSource":"","DataSourceSqlRemote":false,"DataSourceSqlRemoteLoading":false,"TextShowPassword":false,"TextIcon":"","TextIconPosition":"","TextApend":"","TextApendPosition":"","SelectLabel":"","SelectSaveField":"","SelectSaveFormat":"Text","DateTimeType":"date","TextAutocomplete":false,"AutoNumberFixed":"","AutoNumberLength":1,"AutoNumberFields":[],"AutoNumber":{"DataRule":"","CreateRule":""},"ImgUpload":{"Limit":false,"Multiple":false,"Tips":"","MaxCount":10,"ShowFileList":false,"Preview":true,"MaxSize":10},"FileUpload":{"Limit":true,"Multiple":true,"Tips":"","MaxCount":10,"ShowFileList":false,"MaxSize":10},"DevComponentName":"","DevComponentPath":"","TableChildTableId":"7e1cfd2b-4138-43e4-82cb-567c208ad1dc","TableChildSysMenuId":"27ed5ab0-803c-4b4e-9ea8-996f1fdf99cb","TableChildSysMenuName":"商品评论","TableChildFkFieldName":"ShangpinID","TableChildCallbackField":"","TableChildRowClickV8":"","TableChild":{"Data":[],"SearchAppend":{}},"MapCompany":"Baidu","Button":{"Type":"primary","Loading":false,"Icon":"","Size":"mini","PreviewCanClick":true},"Autocomplete":{},"Unique":{"Type":"Alone"},"OpenTable":{"BtnText":"","ShowDialog":false,"MultipleSelect":false,"SubmitV8":"","BeforeOpenV8":"","SearchAppend":{}}}',
          FormWidth: 24,
          TableWidth: 100,
          DefaultValue: "",
          Unique: false,
          BindRole: "[]",
          V8TmpEngineTable: "",
          V8TmpEngineForm: "",
          Placeholder: null,
          Remark: "",
          DataAppend: "",
          InTableEdit: false,
          KeyupV8Code: "",
          IsLockField: false
        }
      ],
      // 此处为模拟传入token（会过期，需实时修改
      token:'eyJhbGciOiJSUzUxMiIsInR5cCI6ImF0K2p3dCJ9.eyJuYmYiOjE2NDU1OTMwMDYsImV4cCI6MTY0NTU5NDIwNiwiaXNzIjoiaHR0cDovL2F1dGguaXRkb3MuY29tIiwiY2xpZW50X2lkIjoic2hvcGRpeSIsInN1YiI6ImM3NGQ2NjljLWEzZDQtMTFlNS1iNjBkLWI4NzBmNDNlZGQwMyIsImF1dGhfdGltZSI6MTY0NTU5MzAwNiwiaWRwIjoibG9jYWwiLCJJZCI6ImM3NGQ2NjljLWEzZDQtMTFlNS1iNjBkLWI4NzBmNDNlZGQwMyIsIlVzZXJJZCI6ImM3NGQ2NjljLWEzZDQtMTFlNS1iNjBkLWI4NzBmNDNlZGQwMyIsIlVzZXJBY2NvdW50IjoiYzc0ZDY2OWMtYTNkNC0xMWU1LWI2MGQtYjg3MGY0M2VkZDAzIiwibmFtZSI6ImM3NGQ2NjljLWEzZDQtMTFlNS1iNjBkLWI4NzBmNDNlZGQwMyIsImdpdmVuX25hbWUiOiJpdGRvc19HaXZlbk5hbWUiLCJmYW1pbHlfbmFtZSI6Iml0ZG9zX0ZhbWlseU5hbWUiLCJlbWFpbCI6ImFkbWluQGlUZG9zLmNvbSIsInJvbGUiOiJpdGRvc191c2VyIiwianRpIjoiMkRFRjhCOTQzNzNCODk2NzgxRkE3Q0ZDNDQ5NkRBOTgiLCJpYXQiOjE2NDU1OTMwMDYsInNjb3BlIjpbImFwaTEiLCJpVGRvc0FwaSIsIm9wZW5pZCIsInByb2ZpbGUiLCJvZmZsaW5lX2FjY2VzcyJdLCJhbXIiOlsiY3VzdG9tIl19.a6qWe6sw1z92jCfgYqT7-Ya5bcO40YxbUhUYHF348IbjmJgPy8hS-aFQ_45hoNmLAApneUMh8AMo1M8jyGNiQ2hx2vPVuKLi7juBYZagiGJno-KUjMt7nVpIAgKgnkQhdpgV-TACl55TtCGBDclW2hy_YOnr6L2wClXuJahPOXp5Ea7IUXOnugNMKGQY6S9WY99oUBn8b-Lb8G6ZfTsTQOrJGZfGRuKPvAJC4RZnrzubmpkKiY5KgM1PaPh6CfyMhElpovlQgZqAQ62cgGeTMPl_a0fIdrVeY2pEOStw6rPTubQyHG3jg9lLWaRr9eUwMdQdFr97hxNvU9Hw6S_URw',
      // 此处为模拟传入选择的字段属性，省略了许多
      data:{
        Label: "名称",
        Name: "Mingcheng",
      },
    };
  },
  components: {
    DataLinkage
  },
  methods: {
    
  },
  mounted(){
    // 有用到接口所以需要设置token，此处为模拟
    localStorage.setItem('authorization', this.token);
    // 获取本地缓存的接口地址，此处为模拟
    localStorage.setItem('DiyApiBase', 'https://api-china.itdos.com');
  },
};
</script>

<style>
</style>