export function getLangs() {
  let langOptions = [
    { value: "chinese_simplified", label: "简体中文" },
    // { value: "chinese_traditional", label: "繁體中文" },
    { value: "english", label: "English" },
    // { value: "korean", label: "한국어" },
    // { value: "japanese", label: "しろうと" },
    // { value: "vietnamese", label: "Tiếng Việt" },
    // { value: "hindi", label: "हिन्दी" },
    // { value: "russian", label: "Русский язык" },
    // { value: "french", label: "Français" },
    // { value: "ukrainian", label: "УкраїнськаName" },
    // { value: "norwegian", label: "Norge" },
    // { value: "welsh", label: "color name" },
    // { value: "dutch", label: "nederlands" },
    // { value: "filipino", label: "Pilipino" },
    // { value: "lao", label: "ກະຣຸນາ" },
    // { value: "telugu", label: "తెలుగుQFontDatabase" },
    // { value: "romanian", label: "Română" },
    // { value: "nepali", label: "नेपालीName" },
    // { value: "haitian_creole", label: "Kreyòl ayisyen" },
    // { value: "czech", label: "český" },
    // { value: "swedish", label: "Svenska" },
    // { value: "malagasy", label: "Malagasy" },
    // { value: "burmese", label: "ဗာရမ်" },
    // { value: "pashto", label: "پښتوName" },
    // { value: "thai", label: "คนไทย" },
    // { value: "armenian", label: "Արմենյան" },
    // { value: "persian", label: "Persian" },
    // { value: "kurdish", label: "Kurdî" },
    // { value: "turkish", label: "Türkçe" },
    // { value: "bulgarian", label: "български" },
    // { value: "malay", label: "Malay" },
    // { value: "swahili", label: "Kiswahili" },
    // { value: "oriya", label: "ଓଡିଆ" },
    // { value: "icelandic", label: "ÍslandName" },
    // { value: "irish", label: "Íris" },
    // { value: "khmer", label: "ខ្មែរKCharselect unicode block name" },
    // { value: "gujarati", label: "ગુજરાતી" },
    // { value: "slovak", label: "Slovenská" },
    // { value: "kannada", label: "ಕನ್ನಡ್Name" },
    // { value: "hebrew", label: "היברית" },
    // { value: "hungarian", label: "magyar" },
    // { value: "marathi", label: "मराठीName" },
    // { value: "tamil", label: "தாமில்" },
    // { value: "estonian", label: "eesti keel" },
    // { value: "malayalam", label: "മലമാലം" },
    // { value: "inuktitut", label: "ᐃᓄᒃᑎᑐᑦ" },
    // { value: "arabic", label: "بالعربية" },
    // { value: "deutsch", label: "Deutsch" },
    // { value: "slovene", label: "slovenščina" },
    // { value: "bengali", label: "বেঙ্গালী" },
    // { value: "urdu", label: "اوردو" },
    // { value: "azerbaijani", label: "azerbaijani" },
    // { value: "portuguese", label: "português" },
    // { value: "samoan", label: "lifiava" },
    // { value: "afrikaans", label: "afrikaans" },
    // { value: "tongan", label: "汤加语" },
    // { value: "greek", label: "ελληνικά" },
    // { value: "indonesian", label: "IndonesiaName" },
    // { value: "spanish", label: "Español" },
    // { value: "danish", label: "dansk" },
    // { value: "amharic", label: "amharic" },
    // { value: "punjabi", label: "ਪੰਜਾਬੀName" },
    // { value: "albanian", label: "albanian" },
    // { value: "lithuanian", label: "Lietuva" },
    // { value: "italian", label: "italiano" },
    // { value: "maltese", label: "Malti" },
    // { value: "finnish", label: "suomi" },
    // { value: "catalan", label: "català" },
    // { value: "croatian", label: "hrvatski" },
    // { value: "bosnian", label: "bosnian" },
    // { value: "polish", label: "Polski" },
    // { value: "latvian", label: "latviešu" },
    // { value: "maori", label: "Maori" }
  ];
  return langOptions;
}
