//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Microi.net
{
    /// <summary>
    /// 实体类DiyTable。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("diy_table")]
    [Serializable]
    public partial class DiyTable : Entity
    {
        #region Model
		private string _Id;
		private string _Name;
		private string _Description;
		private DateTime _CreateTime;
		private DateTime? _UpdateTime;
		private string _UserId;
		private int _IsDeleted;
		private string _OsClient;
		private int _IsTree;
		private int _EnableCache;
		private string _CacheParentKey;
		private int _Column;
		private int _TableInEdit;
		private string _RowAction;
		private string _Tabs;
		private string _TabsPosition;
		private string _TableTabs;
		private string _TableTabsPosition;
		private string _TableArticle;
		private string _FormArticle;
		private string _FormOpenType;
		private string _FormOpenWidth;
		private string _FormLabelPosition;
		private string _FieldBorder;
		private string _InFormV8;
		private string _OutFormV8;
		private string _SubmitFormV8;
		private string _InputBorderStyle;
		private string _BindRole;
		private string _AddCallbakApi;
		private string _UptCallbakApi;
		private string _DelCallbakApi;
		private int _DataEncryptSave;
		private int _DataEncryptTransfer;
		private string _ApiReplace;
		private int _IsAnonymousRead;
		private int _IsAnonymousAdd;
		private string _ServerDataV8;
		private string _TreeParentField;
		private string _TreeParentFields;
		private int? _TreeLazy;
		private string _TreeHasChildren;
		private string _UserName;
		private string _SubmitBeforeServerV8;
		private string _SubmitAfterServerV8;

		/// <summary>
		/// Id
		/// </summary>
		[Field("Id")]
		public string Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Description")]
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange("Description");
				this._Description = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreateTime")]
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange("CreateTime");
				this._CreateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UpdateTime")]
		public DateTime? UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange("UpdateTime");
				this._UpdateTime = value;
			}
		}
		/// <summary>
		/// UserId
		/// </summary>
		[Field("UserId")]
		public string UserId
		{
			get{ return _UserId; }
			set
			{
				this.OnPropertyValueChange("UserId");
				this._UserId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsDeleted")]
		public int IsDeleted
		{
			get{ return _IsDeleted; }
			set
			{
				this.OnPropertyValueChange("IsDeleted");
				this._IsDeleted = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OsClient")]
		public string OsClient
		{
			get{ return _OsClient; }
			set
			{
				this.OnPropertyValueChange("OsClient");
				this._OsClient = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsTree")]
		public int IsTree
		{
			get{ return _IsTree; }
			set
			{
				this.OnPropertyValueChange("IsTree");
				this._IsTree = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("EnableCache")]
		public int EnableCache
		{
			get{ return _EnableCache; }
			set
			{
				this.OnPropertyValueChange("EnableCache");
				this._EnableCache = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CacheParentKey")]
		public string CacheParentKey
		{
			get{ return _CacheParentKey; }
			set
			{
				this.OnPropertyValueChange("CacheParentKey");
				this._CacheParentKey = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Column")]
		public int Column
		{
			get{ return _Column; }
			set
			{
				this.OnPropertyValueChange("Column");
				this._Column = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TableInEdit")]
		public int TableInEdit
		{
			get{ return _TableInEdit; }
			set
			{
				this.OnPropertyValueChange("TableInEdit");
				this._TableInEdit = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RowAction")]
		public string RowAction
		{
			get{ return _RowAction; }
			set
			{
				this.OnPropertyValueChange("RowAction");
				this._RowAction = value;
			}
		}
		/// <summary>
		/// 表单Tabs
		/// </summary>
		[Field("Tabs")]
		public string Tabs
		{
			get{ return _Tabs; }
			set
			{
				this.OnPropertyValueChange("Tabs");
				this._Tabs = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TabsPosition")]
		public string TabsPosition
		{
			get{ return _TabsPosition; }
			set
			{
				this.OnPropertyValueChange("TabsPosition");
				this._TabsPosition = value;
			}
		}
		/// <summary>
		/// 表格Tabs
		/// </summary>
		[Field("TableTabs")]
		public string TableTabs
		{
			get{ return _TableTabs; }
			set
			{
				this.OnPropertyValueChange("TableTabs");
				this._TableTabs = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TableTabsPosition")]
		public string TableTabsPosition
		{
			get{ return _TableTabsPosition; }
			set
			{
				this.OnPropertyValueChange("TableTabsPosition");
				this._TableTabsPosition = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TableArticle")]
		public string TableArticle
		{
			get{ return _TableArticle; }
			set
			{
				this.OnPropertyValueChange("TableArticle");
				this._TableArticle = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FormArticle")]
		public string FormArticle
		{
			get{ return _FormArticle; }
			set
			{
				this.OnPropertyValueChange("FormArticle");
				this._FormArticle = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FormOpenType")]
		public string FormOpenType
		{
			get{ return _FormOpenType; }
			set
			{
				this.OnPropertyValueChange("FormOpenType");
				this._FormOpenType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FormOpenWidth")]
		public string FormOpenWidth
		{
			get{ return _FormOpenWidth; }
			set
			{
				this.OnPropertyValueChange("FormOpenWidth");
				this._FormOpenWidth = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FormLabelPosition")]
		public string FormLabelPosition
		{
			get{ return _FormLabelPosition; }
			set
			{
				this.OnPropertyValueChange("FormLabelPosition");
				this._FormLabelPosition = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FieldBorder")]
		public string FieldBorder
		{
			get{ return _FieldBorder; }
			set
			{
				this.OnPropertyValueChange("FieldBorder");
				this._FieldBorder = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("InFormV8")]
		public string InFormV8
		{
			get{ return _InFormV8; }
			set
			{
				this.OnPropertyValueChange("InFormV8");
				this._InFormV8 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OutFormV8")]
		public string OutFormV8
		{
			get{ return _OutFormV8; }
			set
			{
				this.OnPropertyValueChange("OutFormV8");
				this._OutFormV8 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SubmitFormV8")]
		public string SubmitFormV8
		{
			get{ return _SubmitFormV8; }
			set
			{
				this.OnPropertyValueChange("SubmitFormV8");
				this._SubmitFormV8 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("InputBorderStyle")]
		public string InputBorderStyle
		{
			get{ return _InputBorderStyle; }
			set
			{
				this.OnPropertyValueChange("InputBorderStyle");
				this._InputBorderStyle = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BindRole")]
		public string BindRole
		{
			get{ return _BindRole; }
			set
			{
				this.OnPropertyValueChange("BindRole");
				this._BindRole = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AddCallbakApi")]
		public string AddCallbakApi
		{
			get{ return _AddCallbakApi; }
			set
			{
				this.OnPropertyValueChange("AddCallbakApi");
				this._AddCallbakApi = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UptCallbakApi")]
		public string UptCallbakApi
		{
			get{ return _UptCallbakApi; }
			set
			{
				this.OnPropertyValueChange("UptCallbakApi");
				this._UptCallbakApi = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DelCallbakApi")]
		public string DelCallbakApi
		{
			get{ return _DelCallbakApi; }
			set
			{
				this.OnPropertyValueChange("DelCallbakApi");
				this._DelCallbakApi = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DataEncryptSave")]
		public int DataEncryptSave
		{
			get{ return _DataEncryptSave; }
			set
			{
				this.OnPropertyValueChange("DataEncryptSave");
				this._DataEncryptSave = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DataEncryptTransfer")]
		public int DataEncryptTransfer
		{
			get{ return _DataEncryptTransfer; }
			set
			{
				this.OnPropertyValueChange("DataEncryptTransfer");
				this._DataEncryptTransfer = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ApiReplace")]
		public string ApiReplace
		{
			get{ return _ApiReplace; }
			set
			{
				this.OnPropertyValueChange("ApiReplace");
				this._ApiReplace = value;
			}
		}
		/// <summary>
		/// 是否允许匿名读取
		/// </summary>
		[Field("IsAnonymousRead")]
		public int IsAnonymousRead
		{
			get{ return _IsAnonymousRead; }
			set
			{
				this.OnPropertyValueChange("IsAnonymousRead");
				this._IsAnonymousRead = value;
			}
		}
		/// <summary>
		/// 是否允许匿名新增
		/// </summary>
		[Field("IsAnonymousAdd")]
		public int IsAnonymousAdd
		{
			get{ return _IsAnonymousAdd; }
			set
			{
				this.OnPropertyValueChange("IsAnonymousAdd");
				this._IsAnonymousAdd = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ServerDataV8")]
		public string ServerDataV8
		{
			get{ return _ServerDataV8; }
			set
			{
				this.OnPropertyValueChange("ServerDataV8");
				this._ServerDataV8 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TreeParentField")]
		public string TreeParentField
		{
			get{ return _TreeParentField; }
			set
			{
				this.OnPropertyValueChange("TreeParentField");
				this._TreeParentField = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TreeParentFields")]
		public string TreeParentFields
		{
			get{ return _TreeParentFields; }
			set
			{
				this.OnPropertyValueChange("TreeParentFields");
				this._TreeParentFields = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TreeLazy")]
		public int? TreeLazy
		{
			get{ return _TreeLazy; }
			set
			{
				this.OnPropertyValueChange("TreeLazy");
				this._TreeLazy = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TreeHasChildren")]
		public string TreeHasChildren
		{
			get{ return _TreeHasChildren; }
			set
			{
				this.OnPropertyValueChange("TreeHasChildren");
				this._TreeHasChildren = value;
			}
		}
		/// <summary>
		/// 操作人
		/// </summary>
		[Field("UserName")]
		public string UserName
		{
			get{ return _UserName; }
			set
			{
				this.OnPropertyValueChange("UserName");
				this._UserName = value;
			}
		}
		/// <summary>
		/// 表单提交前事件
		/// </summary>
		[Field("SubmitBeforeServerV8")]
		public string SubmitBeforeServerV8
		{
			get{ return _SubmitBeforeServerV8; }
			set
			{
				this.OnPropertyValueChange("SubmitBeforeServerV8");
				this._SubmitBeforeServerV8 = value;
			}
		}
		/// <summary>
		/// 表单提交后事件
		/// </summary>
		[Field("SubmitAfterServerV8")]
		public string SubmitAfterServerV8
		{
			get{ return _SubmitAfterServerV8; }
			set
			{
				this.OnPropertyValueChange("SubmitAfterServerV8");
				this._SubmitAfterServerV8 = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.Name,
				_.Description,
				_.CreateTime,
				_.UpdateTime,
				_.UserId,
				_.IsDeleted,
				_.OsClient,
				_.IsTree,
				_.EnableCache,
				_.CacheParentKey,
				_.Column,
				_.TableInEdit,
				_.RowAction,
				_.Tabs,
				_.TabsPosition,
				_.TableTabs,
				_.TableTabsPosition,
				_.TableArticle,
				_.FormArticle,
				_.FormOpenType,
				_.FormOpenWidth,
				_.FormLabelPosition,
				_.FieldBorder,
				_.InFormV8,
				_.OutFormV8,
				_.SubmitFormV8,
				_.InputBorderStyle,
				_.BindRole,
				_.AddCallbakApi,
				_.UptCallbakApi,
				_.DelCallbakApi,
				_.DataEncryptSave,
				_.DataEncryptTransfer,
				_.ApiReplace,
				_.IsAnonymousRead,
				_.IsAnonymousAdd,
				_.ServerDataV8,
				_.TreeParentField,
				_.TreeParentFields,
				_.TreeLazy,
				_.TreeHasChildren,
				_.UserName,
				_.SubmitBeforeServerV8,
				_.SubmitAfterServerV8,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._Name,
				this._Description,
				this._CreateTime,
				this._UpdateTime,
				this._UserId,
				this._IsDeleted,
				this._OsClient,
				this._IsTree,
				this._EnableCache,
				this._CacheParentKey,
				this._Column,
				this._TableInEdit,
				this._RowAction,
				this._Tabs,
				this._TabsPosition,
				this._TableTabs,
				this._TableTabsPosition,
				this._TableArticle,
				this._FormArticle,
				this._FormOpenType,
				this._FormOpenWidth,
				this._FormLabelPosition,
				this._FieldBorder,
				this._InFormV8,
				this._OutFormV8,
				this._SubmitFormV8,
				this._InputBorderStyle,
				this._BindRole,
				this._AddCallbakApi,
				this._UptCallbakApi,
				this._DelCallbakApi,
				this._DataEncryptSave,
				this._DataEncryptTransfer,
				this._ApiReplace,
				this._IsAnonymousRead,
				this._IsAnonymousAdd,
				this._ServerDataV8,
				this._TreeParentField,
				this._TreeParentFields,
				this._TreeLazy,
				this._TreeHasChildren,
				this._UserName,
				this._SubmitBeforeServerV8,
				this._SubmitAfterServerV8,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "diy_table");
            /// <summary>
			/// Id
			/// </summary>
			public readonly static Field Id = new Field("Id", "diy_table", "Id");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Description = new Field("Description", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime", "diy_table", "");
            /// <summary>
			/// UserId
			/// </summary>
			public readonly static Field UserId = new Field("UserId", "diy_table", "UserId");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsDeleted = new Field("IsDeleted", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OsClient = new Field("OsClient", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsTree = new Field("IsTree", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field EnableCache = new Field("EnableCache", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CacheParentKey = new Field("CacheParentKey", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Column = new Field("Column", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TableInEdit = new Field("TableInEdit", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field RowAction = new Field("RowAction", "diy_table", "");
            /// <summary>
			/// 表单Tabs
			/// </summary>
			public readonly static Field Tabs = new Field("Tabs", "diy_table", "表单Tabs");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TabsPosition = new Field("TabsPosition", "diy_table", "");
            /// <summary>
			/// 表格Tabs
			/// </summary>
			public readonly static Field TableTabs = new Field("TableTabs", "diy_table", "表格Tabs");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TableTabsPosition = new Field("TableTabsPosition", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TableArticle = new Field("TableArticle", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FormArticle = new Field("FormArticle", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FormOpenType = new Field("FormOpenType", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FormOpenWidth = new Field("FormOpenWidth", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FormLabelPosition = new Field("FormLabelPosition", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FieldBorder = new Field("FieldBorder", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field InFormV8 = new Field("InFormV8", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OutFormV8 = new Field("OutFormV8", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SubmitFormV8 = new Field("SubmitFormV8", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field InputBorderStyle = new Field("InputBorderStyle", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field BindRole = new Field("BindRole", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AddCallbakApi = new Field("AddCallbakApi", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UptCallbakApi = new Field("UptCallbakApi", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DelCallbakApi = new Field("DelCallbakApi", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DataEncryptSave = new Field("DataEncryptSave", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DataEncryptTransfer = new Field("DataEncryptTransfer", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ApiReplace = new Field("ApiReplace", "diy_table", "");
            /// <summary>
			/// 是否允许匿名读取
			/// </summary>
			public readonly static Field IsAnonymousRead = new Field("IsAnonymousRead", "diy_table", "是否允许匿名读取");
            /// <summary>
			/// 是否允许匿名新增
			/// </summary>
			public readonly static Field IsAnonymousAdd = new Field("IsAnonymousAdd", "diy_table", "是否允许匿名新增");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ServerDataV8 = new Field("ServerDataV8", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TreeParentField = new Field("TreeParentField", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TreeParentFields = new Field("TreeParentFields", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TreeLazy = new Field("TreeLazy", "diy_table", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TreeHasChildren = new Field("TreeHasChildren", "diy_table", "");
            /// <summary>
			/// 操作人
			/// </summary>
			public readonly static Field UserName = new Field("UserName", "diy_table", "操作人");
            /// <summary>
			/// 表单提交前事件
			/// </summary>
			public readonly static Field SubmitBeforeServerV8 = new Field("SubmitBeforeServerV8", "diy_table", "表单提交前事件");
            /// <summary>
			/// 表单提交后事件
			/// </summary>
			public readonly static Field SubmitAfterServerV8 = new Field("SubmitAfterServerV8", "diy_table", "表单提交后事件");
        }
        #endregion
	}
}