<script setup>
import {onMounted,reactive,ref} from 'vue';
import {MciButton,MciCard,MciFormField,MciModal,MciDataState,MciSkeleton} from '@microi/mci-ui';
import {api,formatTime,states} from './api.js';
const emit=defineEmits(['navigate']);const loading=ref(true),busy=ref(false),message=ref(''),resources=ref([]),items=ref([]),editor=ref(null),form=reactive({});
const localTime=date=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
async function act(fn){if(busy.value)return;busy.value=true;try{await fn();}catch(error){message.value=error.message;}finally{busy.value=false;}}
async function refresh(){resources.value=(await api('panel/snapshot')).resources.filter(x=>!['Pending','Removed'].includes(x.state));items.value=await api('panel/schedules');}
function edit(schedule){Object.assign(form,{id:schedule?.id||'',resourceId:schedule?.resourceId||resources.value[0]?.id||'',action:schedule?.action||'Backup',enabled:schedule?.enabled??true,intervalHours:schedule?.intervalHours||24,maximumGiB:schedule?.maximumGiB||10,expectedRevision:schedule?.revision||'',allowInterruption:false,firstRun:localTime(schedule&&new Date(schedule.nextRun)>new Date()?new Date(schedule.nextRun):new Date(Date.now()+24*3600000))});editor.value={existing:!!schedule};}
async function save(){await act(async()=>{await api('panel/schedules',{...form,firstRun:new Date(form.firstRun).toISOString(),confirm:form.id});editor.value=null;await refresh();});}
onMounted(async()=>{await act(refresh);loading.value=false;});
</script>
<template>
 <section class="mci-schedules" data-mci-ui-root>
  <MciSkeleton v-if="loading" height="240px" />
  <MciCard v-else><div class="mci-schedules-toolbar"><div><h2>计划任务</h2><p>定时创建冷备份或重启受管服务。计划和执行进度持久保存，关闭页面后继续执行。</p></div><div class="mci-schedules-actions"><MciButton variant="plain" :disabled="busy" @click="act(refresh)">刷新计划</MciButton><MciButton :disabled="busy || !resources.length" @click="edit(null)">新建计划</MciButton></div></div>
   <p>主机恢复后，每个过期计划只补执行一次。暂停计划会阻止后续排队，已经登记的操作继续执行。</p>
   <div v-if="items.length" class="mci-schedules-list"><article v-for="item in items" :key="item.schedule.id"><div class="mci-schedules-toolbar"><strong>{{ item.schedule.id }} · {{ item.schedule.resourceId }}</strong><span>{{ item.schedule.enabled?'已启用':'已暂停' }}</span></div><p>{{ item.schedule.action==='Backup'?'冷备份':'重启服务' }} · 每 {{ item.schedule.intervalHours }} 小时 · 下次 {{ formatTime(item.schedule.nextRun) }}</p><p v-if="item.schedule.action==='Backup'">单次备份上限 {{ item.schedule.maximumGiB }} GiB。历史备份可在“备份与恢复”中下载或删除。</p><p v-if="item.operation">最近操作：{{ states[item.operation.state]||item.operation.state }} · {{ formatTime(item.operation.created) }} <span v-if="item.operation.error">{{ item.operation.error }}</span></p><p v-if="item.schedule.lastError" role="status">{{ item.schedule.lastError }}</p><div class="mci-schedules-actions"><MciButton variant="plain" :disabled="busy" @click="edit(item.schedule)">编辑计划</MciButton><MciButton v-if="item.operation" variant="ghost" @click="emit('navigate','operations')">查看操作任务</MciButton></div></article></div>
   <MciDataState v-else title="还没有计划任务" description="可以把备份和维护安排在客户业务低峰时段。" />
  </MciCard>
  <MciModal :model-value="!!editor" :title="editor?.existing?'编辑计划任务':'新建计划任务'" @update:model-value="value=>{if(!value&&!busy)editor=null;}"><form v-if="editor" id="mci-schedule-form" class="mci-schedules-form" @submit.prevent="save"><MciFormField v-model="form.id" label="计划标识" :disabled="editor.existing" required placeholder="例如 nightly-backup" /><MciFormField label="执行实例"><select v-model="form.resourceId" aria-label="执行实例" required><option v-for="item in resources" :key="item.id" :value="item.id">{{ item.id }}</option></select></MciFormField><MciFormField label="计划操作"><select v-model="form.action" aria-label="计划操作"><option value="Backup">创建冷备份</option><option value="Restart">重启服务</option></select></MciFormField><MciFormField label="间隔（小时）"><input v-model.number="form.intervalHours" aria-label="间隔（小时）" type="number" min="1" max="168" required /></MciFormField><MciFormField label="首次执行时间"><input v-model="form.firstRun" aria-label="首次执行时间" type="datetime-local" required /></MciFormField><MciFormField v-if="form.action==='Backup'" label="单次备份上限（GiB）"><input v-model.number="form.maximumGiB" aria-label="单次备份上限（GiB）" type="number" min="1" max="100" required /></MciFormField><label class="mci-schedules-check"><input v-model="form.enabled" type="checkbox" />启用计划</label><label v-if="form.enabled" class="mci-schedules-check"><input v-model="form.allowInterruption" type="checkbox" required />已确认每次执行时服务会暂时中断</label></form><template #footer><MciButton variant="plain" :disabled="busy" @click="editor=null">取消</MciButton><MciButton type="submit" form="mci-schedule-form" :disabled="busy || (form.enabled && !form.allowInterruption)" :loading="busy">保存计划</MciButton></template></MciModal>
  <MciModal :model-value="!!message" title="计划任务提示" @update:model-value="value=>{if(!value)message='';}"><p role="alert">{{ message }}</p><template #footer><MciButton @click="message=''">知道了</MciButton></template></MciModal>
 </section>
</template>
<style scoped>
.mci-schedules { min-width:0; }.mci-schedules-toolbar,.mci-schedules-actions { display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap; }.mci-schedules-actions { justify-content:flex-start; }.mci-schedules p { color:var(--mci-text-secondary);overflow-wrap:anywhere; }.mci-schedules-list { display:grid;gap:20px;margin-top:20px; }.mci-schedules-list article { padding:20px 0;border-top:1px solid var(--mci-border-default); }.mci-schedules-form { display:grid;gap:16px; }.mci-schedules-form select { width:100%;padding:10px;background:var(--mci-surface-card);color:var(--mci-text-primary);border:1px solid var(--mci-border-default);border-radius:var(--mci-radius-control); }.mci-schedules-check { display:flex;align-items:center;gap:8px;line-height:1.6; }
</style>
