import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../..');
const {chromium,expect}=createRequire(resolve(root,'Microi.Client/package.json'))('@playwright/test');
const target=JSON.parse(await readFile(process.env.PANEL_BROWSER_CONTEXT||resolve(root,'.tmp/panel-20260910/latest-docker-context.json'),'utf8'));
const env=Object.fromEntries((await readFile(resolve(target.work,'panel.env'),'utf8')).trim().split(/\r?\n/).map(line=>{const n=line.indexOf('=');return[line.slice(0,n),line.slice(n+1)];}));
const work=resolve(target.work,'browser-'+Date.now());await mkdir(work,{recursive:true});
const browser=await chromium.launch({headless:true,channel:process.env.PANEL_TEST_BROWSER_CHANNEL||(process.platform==='win32'?'msedge':undefined)});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage(),errors=[],passed=[];
const siteSuffix=Date.now().toString(36),siteId='browser-'+siteSuffix,siteTitle='浏览器静态网站 '+siteSuffix;
page.on('pageerror',error=>errors.push(error.message));
const pass=name=>{passed.push(name);console.log('PASS '+name);};
const nav=label=>page.getByRole('navigation',{name:'运维功能'}).getByRole('button',{name:label,exact:true}).click();
try{
 await page.goto(process.env.PANEL_BROWSER_URL||target.base);
 await page.getByLabel(/^运维账号/).fill(env.OPS_ADMIN_USERNAME);
 await page.getByLabel(/^运维密码/).fill(env.OPS_ADMIN_PASSWORD);
 await page.getByRole('button',{name:'登录运维中心',exact:true}).click();
 await expect(page.getByRole('heading',{name:'服务器总览',exact:true})).toBeVisible();pass('independent browser login');
 const contentChecks={'插件市场':'Nginx','网站与反向代理':'网站验收','SSL 证书':'验收证书','容器管理':'gateway','操作任务':'gateway · 发布网站配置'};
 for(const label of ['插件市场','网站与反向代理','SSL 证书','容器管理','操作任务']){
  await nav(label);await expect(page.getByRole('heading',{name:label,exact:true}).first()).toBeVisible();
  await expect(page.locator('.mci-skeleton')).toHaveCount(0);
  await expect(page.getByText(contentChecks[label],{exact:true}).first()).toBeVisible();
  await page.screenshot({path:resolve(work,label+'.png'),fullPage:true});
 }
 pass('real Docker data appears on five panel routes');
 await nav('插件市场');await page.getByRole('button',{name:'＋ 安装',exact:true}).first().click();
 const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();
 const focusedInside=await dialog.evaluate(element=>element.contains(document.activeElement));assert.equal(focusedInside,true,'modal must receive keyboard focus');
 const field=dialog.locator('input').first();await expect(field).toHaveAttribute('required','');
 const header=dialog.locator('.mci-web-modal__header');const box=await header.boundingBox();await page.mouse.move(box.x+35,box.y+20);await page.mouse.down();await page.mouse.move(-1000,-1000,{steps:4});await page.mouse.up();
 const moved=await dialog.locator('.mci-web-modal__panel').boundingBox();assert(moved.x>=15&&moved.y>=15,'drag stays inside viewport');
 await page.keyboard.press('Tab');assert(await dialog.evaluate(el=>el.contains(document.activeElement)),'Tab remains inside dialog');
 await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(page.getByRole('button',{name:'＋ 安装',exact:true}).first()).toBeFocused();pass('modal focus, required fields, drag bounds and Escape restoration');
 await nav('网站与反向代理');await page.getByRole('button',{name:'＋ 创建网站',exact:true}).click();
 await page.getByLabel(/^网站标识/).fill(siteId);await page.getByLabel('网站名称',{exact:true}).fill(siteTitle);
 await page.getByLabel('域名（每行一个）',{exact:true}).fill(siteId+'.example.test');await page.getByLabel('网站类型',{exact:true}).selectOption('Static');
 await page.getByRole('button',{name:'保存到待发布配置',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.getByText(siteTitle,{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'发布配置',exact:true}).click();await page.getByRole('button',{name:'确认发布',exact:true}).click();
 await expect(page.getByRole('heading',{name:'操作任务',exact:true})).toBeVisible();
 await expect(page.locator('.mci-panel-operation').first()).toContainText('已完成',{timeout:30000});
 await nav('网站与反向代理');await expect(page.getByText(siteTitle,{exact:true})).toBeVisible();pass('browser website form publishes and reads persisted configuration');
 await nav('网站文件');await page.getByLabel('文件管理网站',{exact:true}).selectOption(siteId);
 await page.getByRole('button',{name:'新建文本',exact:true}).click();await page.getByLabel('文件内容',{exact:true}).fill('<h1>浏览器文件第一版</h1>');
 await page.getByRole('button',{name:'保存文件',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0,{timeout:30000});
 const fileRow=page.locator('.mci-files-table tbody tr').filter({hasText:'index.html'});await expect(fileRow).toBeVisible();
 await fileRow.getByRole('button',{name:'编辑',exact:true}).click();await expect(page.getByLabel('文件内容',{exact:true})).toHaveValue('<h1>浏览器文件第一版</h1>');
 await page.getByLabel('文件内容',{exact:true}).fill('<h1>浏览器文件第二版</h1>');await page.getByRole('button',{name:'保存文件',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0,{timeout:30000});
 const downloaded=page.waitForEvent('download');await fileRow.getByRole('link',{name:'下载',exact:true}).click();const download=await downloaded;assert.equal(download.suggestedFilename(),'index.html');await download.saveAs(resolve(work,'downloaded-index.html'));assert.equal(await readFile(resolve(work,'downloaded-index.html'),'utf8'),'<h1>浏览器文件第二版</h1>');
 await page.getByRole('button',{name:'历史版本与回收',exact:true}).click();await page.getByRole('button',{name:'恢复此版本',exact:true}).first().click();await page.getByRole('button',{name:'确认恢复文件',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'恢复文件版本',exact:true})).toHaveCount(0,{timeout:30000});await page.getByRole('dialog',{name:'历史版本与回收',exact:true}).getByRole('button',{name:'关闭',exact:true}).click();
 await fileRow.getByRole('button',{name:'编辑',exact:true}).click();await expect(page.getByLabel('文件内容',{exact:true})).toHaveValue('<h1>浏览器文件第一版</h1>');await page.getByRole('button',{name:'取消',exact:true}).click();
 await fileRow.getByRole('button',{name:'移入回收',exact:true}).click();await page.getByRole('button',{name:'确认移入回收',exact:true}).click();await expect(fileRow).toHaveCount(0,{timeout:30000});
 await page.getByRole('button',{name:'历史版本与回收',exact:true}).click();await page.getByRole('button',{name:'恢复此版本',exact:true}).first().click();await page.getByRole('button',{name:'确认恢复文件',exact:true}).click();await expect(page.getByRole('dialog',{name:'恢复文件版本',exact:true})).toHaveCount(0,{timeout:30000});await page.getByRole('dialog',{name:'历史版本与回收',exact:true}).getByRole('button',{name:'关闭',exact:true}).click();await expect(fileRow).toBeVisible();
 await page.getByRole('button',{name:'上传文件',exact:true}).click();await page.getByLabel('选择上传文件',{exact:true}).setInputFiles({name:'上传验收.txt',mimeType:'text/plain',buffer:Buffer.from('浏览器上传内容')});
 await page.getByRole('dialog',{name:'上传网站文件',exact:true}).getByRole('button',{name:'上传文件',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0,{timeout:30000});await expect(page.getByText('上传验收.txt',{exact:true})).toBeVisible();
 pass('browser file create edit download history restore recycle and upload persist');
 await nav('备份与恢复');await page.getByLabel('备份实例',{exact:true}).selectOption('gateway');await page.getByRole('button',{name:'创建冷备份',exact:true}).click();
 await page.getByLabel('备份容量上限（GiB）',{exact:true}).fill('1');await page.getByLabel('已确认此服务可以暂时中断',{exact:true}).check();await page.getByRole('button',{name:'确认创建备份',exact:true}).click();
 await expect(page.getByRole('heading',{name:'操作任务',exact:true})).toBeVisible();await expect(page.locator('.mci-panel-operation').first()).toContainText('已完成',{timeout:60000});
 await nav('备份与恢复');await page.getByLabel('备份实例',{exact:true}).selectOption('gateway');await expect(page.getByRole('button',{name:'恢复备份',exact:true}).first()).toBeVisible();
 await nav('网站文件');await page.getByLabel('文件管理网站',{exact:true}).selectOption(siteId);await fileRow.getByRole('button',{name:'编辑',exact:true}).click();await page.getByLabel('文件内容',{exact:true}).fill('备份后的临时修改');await page.getByRole('button',{name:'保存文件',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0,{timeout:30000});
 await nav('备份与恢复');await page.getByLabel('备份实例',{exact:true}).selectOption('gateway');await page.getByRole('button',{name:'恢复备份',exact:true}).first().click();await page.getByLabel('已确认切换备份内容与服务中断',{exact:true}).check();await page.getByRole('button',{name:'确认恢复备份',exact:true}).click();
 await expect(page.getByRole('heading',{name:'操作任务',exact:true})).toBeVisible();await expect(page.locator('.mci-panel-operation').first()).toContainText('已完成',{timeout:60000});
 await nav('网站文件');await page.getByLabel('文件管理网站',{exact:true}).selectOption(siteId);await fileRow.getByRole('button',{name:'编辑',exact:true}).click();await expect(page.getByLabel('文件内容',{exact:true})).toHaveValue('<h1>浏览器文件第一版</h1>');await page.getByRole('button',{name:'取消',exact:true}).click();
 pass('browser cold backup and complete restore recover prior website content');
 await nav('计划任务');await page.getByRole('button',{name:'新建计划',exact:true}).click();const scheduleId='browser-schedule-'+siteSuffix;
 await page.getByLabel(/^计划标识/).fill(scheduleId);await page.getByLabel('执行实例',{exact:true}).selectOption('gateway');await page.getByLabel('计划操作',{exact:true}).selectOption('Restart');await page.getByLabel('已确认每次执行时服务会暂时中断',{exact:true}).check();await page.getByRole('button',{name:'保存计划',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0,{timeout:30000});
 const scheduleRow=page.locator('.mci-schedules-list article').filter({hasText:scheduleId});await expect(scheduleRow).toContainText('已启用');await scheduleRow.getByRole('button',{name:'编辑计划',exact:true}).click();await page.getByLabel('启用计划',{exact:true}).uncheck();await page.getByRole('button',{name:'保存计划',exact:true}).click();await expect(scheduleRow).toContainText('已暂停');pass('browser schedule creation and pause persist');
 for(const [theme,palette,width] of ['亮色','暗色'].flatMap(theme=>['黑','白','红','橙','黄','绿','青','蓝','紫'].map((palette,index)=>[theme,palette,index%2?1440:390]))){
  await page.setViewportSize({width,height:width<600?844:1000});
  await page.getByRole('button',{name:'主题',exact:true}).click();await page.getByRole('button',{name:theme,exact:true}).click();await page.getByRole('button',{name:`切换为${palette}色主题`,exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();await nav('插件市场');
  await expect(page.getByRole('heading',{name:'Nginx',exact:true})).toBeVisible();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page must not overflow horizontally');
  const borders=await page.locator('nav button.active').evaluate(el=>{const s=getComputedStyle(el);return{left:s.borderLeftWidth,right:s.borderRightWidth};});assert.equal(borders.left,'0px');assert.equal(borders.right,'0px');
  const contrast=await page.locator('.mci-panel-plugin').first().evaluate(card=>{
   const rgba=value=>{const values=value.match(/[\d.]+/g).map(Number);return [values[0],values[1],values[2],values[3]??1];};
   const luminance=color=>color.slice(0,3).map(x=>x/255).map(x=>x<=0.04045?x/12.92:((x+0.055)/1.055)**2.4).reduce((sum,x,i)=>sum+x*[0.2126,0.7152,0.0722][i],0);
   const combine=(color,bg)=>color.slice(0,3).map((x,i)=>x*color[3]+bg[i]*(1-color[3]));
   const ratio=(a,b)=>{const values=[luminance(a),luminance(b)].sort((a,b)=>b-a);return(values[0]+0.05)/(values[1]+0.05);};
   const base=rgba(getComputedStyle(document.body).backgroundColor),style=getComputedStyle(card),stops=(style.backgroundImage.match(/rgba?\([^)]+\)/g)||[style.backgroundColor]).map(rgba).map(x=>combine(x,base));
   const text=rgba(getComputedStyle(card.querySelector('p')).color),button=card.querySelector('button'),buttonStyle=getComputedStyle(button),buttonStops=(buttonStyle.backgroundImage.match(/rgba?\([^)]+\)/g)||[buttonStyle.backgroundColor]).map(rgba).map(x=>combine(x,stops[0]));
   return{body:Math.min(...stops.map(bg=>ratio(text,bg))),button:Math.min(...buttonStops.map(bg=>ratio(rgba(buttonStyle.color),bg)))};
  });
  assert(contrast.body>=4.5,`${theme}/${palette} card text contrast ${contrast.body}`);assert(contrast.button>=4.5,`${theme}/${palette} button contrast ${contrast.button}`);
  await page.screenshot({path:resolve(work,`${theme}-${palette}-${width}.png`),fullPage:true});
 }
 pass('18 light dark palettes pass contrast and mobile layout checks without curved accent borders');
 assert.deepEqual(errors,[]);pass('no browser runtime errors');
}finally{
 await page.screenshot({path:resolve(work,'last-page.png'),fullPage:true}).catch(()=>{});
 await writeFile(resolve(work,'report.json'),JSON.stringify({passed,errors,completed:passed.length===9,target:target.base},null,2));
 await context.close();await browser.close();console.log('Report '+resolve(work,'report.json'));
}
