import test from 'node:test'
import assert from 'node:assert/strict'
import vm from 'node:vm'
import {readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {isIP} from 'node:net'
import {reportRows,csv} from '../src/cdn-model.js'
const sha=v=>createHash('sha256').update(v).digest('hex')
const source=readFileSync(new URL('../engines/mci-cdn-core.js',import.meta.url),'utf8')
function ipBytes(s){if(!isIP(s))throw Error('invalid');if(isIP(s)===4)return s.split('.').map(Number);const [l,r]=s.split('::'),a=l?l.split(':'):[],b=r?r.split(':'):[];const words=r!==undefined?[...a,...Array(8-a.length-b.length).fill('0'),...b]:a;return words.flatMap(x=>[parseInt(x,16)>>8,parseInt(x,16)&255])}
function setup({cloud=()=>({Code:1,Data:{}}),tenant='t1',code=source}={}){
 const db={},calls=[],ctx={console,Date,Math,JSON,Error,System:{Net:{IPAddress:{Parse:s=>({GetAddressBytes:()=>ipBytes(s)})}}}}
 const V8={Param:{},OsClient:tenant,CurrentUser:{Account:'admin'},EncryptHelper:{Sha256Hex:sha},Method:{NewGuid:()=>crypto.randomUUID()},ApiEngine:{Run:(key,p)=>{calls.push({key,...p});return cloud(p)}},FormEngine:{
  GetFormData:(t,p)=>{const row=db[t]?.get(p.Id);return row&&row.Tenant===tenant?{Code:1,Data:structuredClone(row)}:{Code:2}},
  GetTableData:(t,p)=>({Code:1,Data:[...(db[t]?.values()||[])].filter(row=>(p._Where||[]).every(([k,op,v])=>op==='='?row[k]===v:op==='In'?v.includes(row[k]):op==='>'?row[k]>v:op==='<='?row[k]<=v:op==='>='?row[k]>=v:op==='<'?row[k]<v:true)).slice(0,p._PageSize)}),
  AddFormData:(t,p)=>{db[t]??=new Map();if(db[t].has(p.Id))return {Code:0,Msg:'duplicate'};db[t].set(p.Id,structuredClone(p));return {Code:1,Data:structuredClone(p)}},
  UptFormData:(t,p)=>{const row=db[t]?.get(p.Id);if(!row)return {Code:0};Object.assign(row,structuredClone(p));return {Code:1,Data:structuredClone(row)}}
 }};ctx.V8=V8;vm.createContext(ctx);
 // 接口正文允许顶层 return。完整执行函数包装，再从 finally 导出同作用域函数，
 // 不按换行切掉调度正文，保证 LF/CRLF 都保留实际入口与安全分支。
 const result=vm.runInContext('(function(){try {\n'+code+'\n} finally {this.api={address,addresses,matches,protectedIp,command,rule,cleanConfig,functionChange,fingerprint,snapshotHash,verifies,scanRule,expiry,enqueue,id};}}).call(this)',ctx);
 return {ctx,api:ctx.api,result,db,calls,V8,put:(t,row)=>V8.FormEngine.AddFormData(t,{Tenant:tenant,...row})}
}

test('complete V8 entry preserves top-level return with both LF and CRLF',()=>{for(const eol of ['\n','\r\n']){const s=setup({code:source.replace(/\r?\n/g,eol)});assert.equal(s.result.Code,0);assert.equal(s.result.Msg,'不支持的 CDN 管理动作');assert.equal(typeof s.api.address,'function');assert.equal(s.calls.length,0)}})
test('IPv4 and expanded IPv6 CIDR matching protects overlapping ranges',()=>{const {api}=setup();assert.equal(api.address('2001:db8::1').value,'2001:0db8:0000:0000:0000:0000:0000:0001');assert.equal(api.matches('2001:db8::2','2001:db8::/32'),true);assert.equal(api.matches('192.0.2.3','192.0.2.0/24'),true);assert.equal(api.matches('192.0.3.3','192.0.2.0/24'),false);assert.equal(api.protectedIp('192.0.2.0/24',['192.0.2.4']),true);assert.throws(()=>api.address('127.1'));assert.throws(()=>api.address('example.com'))})
test('block defaults protect private networks and incomplete scopes',()=>{const {api}=setup();assert.throws(()=>api.command({Action:'Block',Domain:'example.com',IPList:'10.0.0.1'}),/白名单/);assert.throws(()=>api.command({Action:'GlobalBlock',Domain:'example.com',IPList:'192.0.2.1'}),/ALL_CDN_DOMAINS/);assert.throws(()=>api.command({Action:'RateLimit',Domain:'example.com',Rate:'1k'}),/100k/);assert.throws(()=>api.command({Action:'Block',Domain:'example.com?q=1',IPList:'192.0.2.1'}))})
const acl=(ip='192.0.2.9',source='off')=>({FunctionName:'ip_black_list_set',ConfigId:7,FunctionArgs:{FunctionArg:[{ArgName:'ip_list',ArgValue:ip},{ArgName:'ip_acl_xfwd',ArgValue:source},{ArgName:'customize_response_status_code',ArgValue:'429'}]}})
test('IP change merges existing entries and records only newly owned addresses',()=>{const {api}=setup();const c=api.command({Action:'Block',Domain:'example.com',IPList:'192.0.2.9,192.0.2.10'}),change=api.functionChange(c,[acl()]);assert.equal(change.Values.ip_list,'192.0.2.9,192.0.2.10');assert.equal(change.Values.customize_response_status_code,'429');assert.deepEqual([...change.Owned],['192.0.2.10']);assert.throws(()=>api.functionChange(c,[acl('192.0.2.9','on')]),/X-Forwarded-For/);assert.throws(()=>api.functionChange(c,[acl(),{FunctionName:'ip_allow_list_set'}]),/白名单/);assert.throws(()=>api.functionChange(c,[acl(),acl()]),/多条/)})
test('unblock removes only requested entries and deletes empty function',()=>{const {api}=setup();let c=api.command({Action:'Unblock',Domain:'example.com',IPList:'192.0.2.9'});assert.equal(api.functionChange(c,[acl()]).Remove,true);assert.equal(api.functionChange(c,[acl('192.0.2.9,192.0.2.10')]).Values.ip_list,'192.0.2.10')})
test('cloud fingerprint ignores argument order but detects configuration changes',()=>{const {api}=setup(),a=acl(),b=structuredClone(a);b.FunctionArgs.FunctionArg.reverse();assert.equal(api.fingerprint([a]),api.fingerprint([b]));b.ConfigId=8;assert.notEqual(api.fingerprint([a]),api.fingerprint([b]));assert.equal(api.snapshotHash({Action:'GlobalBlock'},{RequestId:'a',Entries:[]}),api.snapshotHash({Action:'GlobalBlock'},{RequestId:'b',Entries:[]}))})
test('tenant-keyed idempotency returns existing operation without duplicate insert',()=>{const s=setup(),t=setup({tenant:'t2'});const c=s.api.command({Action:'Block',Domain:'example.com',IPList:'192.0.2.1'}),a=s.api.enqueue(c,[],'h','request-1','Manual',''),b=s.api.enqueue(c,[],'h','request-1','Manual','');assert.equal(a.Id,b.Id);assert.equal(s.db.mci_cdn_operation.size,1);assert.notEqual(s.api.id('operation|request-1'),t.api.id('operation|request-1'))})
test('rules reject unsafe dimensions and duration and use disabled observation defaults',()=>{const {api}=setup();const r=api.rule({});assert.equal(r.Mode,'observe');assert.equal(api.cleanConfig({}).AutoEnabled,false);assert.throws(()=>api.rule({Metric:'sql'}));assert.throws(()=>api.rule({Duration:0}));assert.throws(()=>api.rule({MaxIps:1000}))})
function ruleScenario({complete=true,lastSeen,missing=0,dynamic=false}={}){const end=Math.floor((Date.now()/1000-300)/300)*300;const s=setup({cloud:p=>({Code:1,Data:{Complete:complete,LastSeen:lastSeen??end-2,MissingBytes:missing,Rows:[{remote_ip:'192.0.2.10',bytes:200,requests:300,last_seen:end-2}]}})});const row={Id:'rule1',Domain:'example.com',Provider:'aliyun',Name:'observe',RuleJson:JSON.stringify({Threshold:100,Consecutive:1,ThresholdType:dynamic?'dynamic':'fixed'}),StateJson:'{}',LastScan:0};s.put('mci_cdn_rule',row);return {...s,row,end}}
test('incomplete or late SLS windows never cause bans',()=>{for(const args of [{complete:false},{lastSeen:1},{missing:1}]){const s=ruleScenario(args),r=s.api.scanRule(s.row);assert.ok(r.Skipped);assert.equal(s.db.mci_cdn_operation?.size||0,0);assert.equal(s.calls.filter(x=>x.Action!=='Sls').length,0)}})
test('observe mode persists evidence and never calls cloud writes; same window not repeated',()=>{const s=ruleScenario();const r=s.api.scanRule(s.row);assert.equal(r.Mode,'observe');assert.equal(s.db.mci_cdn_operation.size,1);assert.equal([...s.db.mci_cdn_operation.values()][0].Status,'Observed');const updated=s.db.mci_cdn_rule.get('rule1');assert.ok(s.api.scanRule(updated).Skipped);assert.equal(s.calls.length,1)})
test('dynamic rules wait for sufficient historical windows',()=>{const s=ruleScenario({dynamic:true}),r=s.api.scanRule(s.row);assert.equal(r.Candidates.length,0);assert.equal(s.db.mci_cdn_operation?.size||0,0)})
test('expiry never removes pre-existing cloud entries',()=>{const s=setup();s.put('mci_cdn_operation',{Id:'op1',ResultJson:'{"Owned":[]}',PayloadJson:'{}',ExpireAt:1});s.api.expiry(s.db.mci_cdn_operation.get('op1'));assert.equal(s.db.mci_cdn_operation.get('op1').ExpireAt,0);assert.equal(s.calls.length,0)})
test('expiry defers ownership when another ban overlaps',()=>{const s=setup();s.put('mci_cdn_operation',{Id:'op1',Domain:'example.com',Provider:'aliyun',Action:'Block',Status:'Succeeded',ResultJson:'{"Owned":["192.0.2.1"]}',PayloadJson:'{"Domain":"example.com","Provider":"aliyun","Duration":60}',ExpireAt:1});s.put('mci_cdn_operation',{Id:'op2',Domain:'example.com',Provider:'aliyun',Action:'Block',Status:'Succeeded',PayloadJson:'{"IPList":["192.0.2.1"],"Duration":3600}',ExpireAt:Math.floor(Date.now()/1000)+3500});const r=s.api.expiry(s.db.mci_cdn_operation.get('op1'));assert.ok(r.DeferredUntil>Date.now()/1000);assert.equal(s.calls.length,0)})
test('nested operations report data parses without treating report headers as traffic',()=>{const rows=reportRows(JSON.stringify({data:[{deliver:{report:{header:[{url:'header',traf:123}]}},data:JSON.stringify([{ip:'192.0.2.1',traf:'4.2 GB',acc:30}])}]}));assert.equal(rows.length,1);assert.equal(rows[0].traf,'4.2 GB');assert.match(csv([{ip:'=cmd',requests:2}]),/'=cmd/)})
const adapterSource=readFileSync(new URL('../engines/mci-cdn-aliyun.js',import.meta.url),'utf8')
test('SLS entry accepts immutable CLR-like parameters and uses authoritative tenant configuration',()=>{const s=setup();s.V8.Param=new Proxy({Action:'Sls',Provider:'aliyun',Domain:'example.com',From:100,To:400,Config:{SlsProject:'untrusted'}},{set(){throw Error('CLR parameter assignment forbidden')}});const result=new Function('V8',source)(s.V8);assert.equal(result.Code,1,result.Msg);assert.equal(s.calls.length,1);assert.deepEqual(s.calls[0].Config,{});assert.equal(s.calls[0].From,100)})
function adapter(params,settings={},response={}){const requests=[];const V8={Param:params,SysConfig:{ServerPrivateSettings:settings},OsClientModel:{AlidnsKeyId:'legacy-id',AlidnsKeySecret:'legacy-secret'},Method:{NewGuid:()=>crypto.randomUUID(),HmacSha1Sign:()=> 'fixture-signature'},EncryptHelper:{MD5Encrypt:()=> 'abcd'},Http:{GetResponse:p=>{requests.push(p);return {StatusCode:200,Content:JSON.stringify(response)}},PostResponse:p=>{requests.push(p);return {StatusCode:200,Content:JSON.stringify(response)}}}};return {result:new Function('V8',adapterSource)(V8),requests}}
test('all twelve report requests obey Aliyun per-report parameter contracts',()=>{for(const id of [1,3,5,7,9,11,13,15,17,19,21,23]){const {result,requests}=adapter({Action:'Reports',Domain:'example.com',StartTime:'2026-09-01',EndTime:'2026-09-02',ReportId:id,Area:'shanghai',HttpCode:'2xx',IsOverseas:'1'});assert.equal(result.Code,1);const p=new URL(requests[0].Url).searchParams;assert.equal(p.has('DomainName'),id!==17);assert.equal(p.has('Area'),[13,15].includes(id));assert.equal(p.has('HttpCode'),[1,3,9,11].includes(id));assert.equal(p.has('IsOverseas'),[21,23].includes(id))}})
test('CDN signing keeps timestamp lexical ISO and credentials never appear in result',()=>{const {result,requests}=adapter({Action:'Domains'},{},{Domains:{PageData:[]}});assert.equal(result.Code,1);const url=new URL(requests[0].Url);assert.equal(url.searchParams.get('Action'),'DescribeUserDomains');assert.match(url.searchParams.get('Timestamp'),/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/);assert(!JSON.stringify(result).includes('legacy-secret'))})
test('half-configured tenant credentials do not mix or fall back to SaaS',()=>{const {result,requests}=adapter({Action:'Domains'},{'Integration.Cdn.Aliyun.AccessKeyId':'tenant-id'});assert.equal(result.Code,0);assert.equal(requests.length,0)})
test('SLS uses bounded fixed SQL, direct peer IP and a fixed regional endpoint',()=>{const {result,requests}=adapter({Action:'Sls',Domain:'example.com',Config:{SlsRegion:'cn-hangzhou',SlsProject:'test-project',SlsLogstore:'test-logstore'},From:100,To:400,Dimension:'ipUrl',Metric:'bytes'},{},{meta:{progress:'Incomplete'},data:[]});assert.equal(result.Data.Complete,false);assert.equal(requests[0].Url,'https://test-project.cn-hangzhou.log.aliyuncs.com/logstores/test-logstore/logs');const body=JSON.parse(requests[0].PostParamString);assert.match(body.query,/SELECT remote_ip, uri/);assert(!body.query.includes('uri_param'));assert.equal(body.powerSql,false);assert.equal(Number(requests[0].Headers['x-log-bodyrawsize']),Buffer.byteLength(requests[0].PostParamString))})
test('historical report URLs drop query credentials at the adapter boundary',()=>{const {result}=adapter({Action:'Reports',Domain:'example.com',StartTime:'2026-09-01',EndTime:'2026-09-02',ReportId:3},{},{Content:{data:[{url:'https://example.com/a.zip?token=private',traf:10,acc:1}]}});assert.equal(result.Data.Content.data[0].url,'https://example.com/a.zip');assert(!JSON.stringify(result).includes('private'))})
