//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;using Dos.ORM;namespace Microi.net{






	/// <summary>	/// 实体类SysMenu。(属性说明自动提取数据库字段的描述信息)	/// </summary>    [Table("sys_menu")]
	[Serializable]
	public partial class SysMenu : Entity
	{


		#region Model        private string _Id;		private string _Name;		private string _Description;		private string _EnName;		private string _EnDescription;		private string _Code;		private string _Url;		private string _Link;		private string _ParentId;		private int _Sort;		private string _Icon;		private string _IconClass;		private DateTime _CreateTime;		private string _OpenType;		private string _ComponentName;		private string _ComponentPath;		private string _JquerySelector;		private int _MultRun;		private int _Display;
		private int _AppDisplay;
        private string _Class;		private string _UserId;		private string _StoreId;		private string _DiyTableId;		private string _TableDiyFieldIds;		private string _PageTemplate;		private string _SearchFieldIds;		private string _DiyConfig;		private string _SortFieldIds;		private string _SqlWhere;		private string _SqlJoin;		private string _StatisticsFields;		private int _IsDeleted;		private string _DefaultOrderBy;		private string _NotShowFields;		private string _ImportTemplate;		private string _ImportTemplateName;		private string _MoreBtns;		private string _ImportV8;		private string _ExportV8;		private string _ExportMoreBtns;		private string _DetailPageV8;		private string _BatchSelectMoreBtns;		private string _PageBtns;		private string _PageTabs;		private int _InTableEdit;		private string _InTableEditFields;		private string _TableHeaders;		private int _IsMicroiService;		private DateTime? _UpdateTime;		private string _UserName;		private string _FormBtns;		private string _SelectFields;		private string _JoinTables;
		//private string _RoleGroup;













		/// <summary>		/// 		/// </summary>        [Field("Id")]		public string Id		{			get { return _Id; }			set			{				this.OnPropertyValueChange("Id");				this._Id = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("Name")]		public string Name		{			get { return _Name; }			set			{				this.OnPropertyValueChange("Name");				this._Name = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("Description")]		public string Description		{			get { return _Description; }			set			{				this.OnPropertyValueChange("Description");				this._Description = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("EnName")]		public string EnName		{			get { return _EnName; }			set			{				this.OnPropertyValueChange("EnName");				this._EnName = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("EnDescription")]		public string EnDescription		{			get { return _EnDescription; }			set			{				this.OnPropertyValueChange("EnDescription");				this._EnDescription = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("Code")]		public string Code		{			get { return _Code; }			set			{				this.OnPropertyValueChange("Code");				this._Code = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("Url")]		public string Url		{			get { return _Url; }			set			{				this.OnPropertyValueChange("Url");				this._Url = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("Link")]		public string Link		{			get { return _Link; }			set			{				this.OnPropertyValueChange("Link");				this._Link = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("ParentId")]		public string ParentId		{			get { return _ParentId; }			set			{				this.OnPropertyValueChange("ParentId");				this._ParentId = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("Sort")]		public int Sort		{			get { return _Sort; }			set			{				this.OnPropertyValueChange("Sort");				this._Sort = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("Icon")]		public string Icon		{			get { return _Icon; }			set			{				this.OnPropertyValueChange("Icon");				this._Icon = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("IconClass")]		public string IconClass		{			get { return _IconClass; }			set			{				this.OnPropertyValueChange("IconClass");				this._IconClass = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("CreateTime")]		public DateTime CreateTime		{			get { return _CreateTime; }			set			{				this.OnPropertyValueChange("CreateTime");				this._CreateTime = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("OpenType")]		public string OpenType		{			get { return _OpenType; }			set			{				this.OnPropertyValueChange("OpenType");				this._OpenType = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("ComponentName")]		public string ComponentName		{			get { return _ComponentName; }			set			{				this.OnPropertyValueChange("ComponentName");				this._ComponentName = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("ComponentPath")]		public string ComponentPath		{			get { return _ComponentPath; }			set			{				this.OnPropertyValueChange("ComponentPath");				this._ComponentPath = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("JquerySelector")]		public string JquerySelector		{			get { return _JquerySelector; }			set			{				this.OnPropertyValueChange("JquerySelector");				this._JquerySelector = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("MultRun")]		public int MultRun		{			get { return _MultRun; }			set			{				this.OnPropertyValueChange("MultRun");				this._MultRun = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("Display")]		public int Display		{			get { return _Display; }			set			{				this.OnPropertyValueChange("Display");				this._Display = value;			}		}

        [Field("AppDisplay")]
        public int AppDisplay
        {
            get { return _AppDisplay; }
            set
            {
                this.OnPropertyValueChange("AppDisplay");
                this._AppDisplay = value;
            }
        }










        /// <summary>        /// 就是Customer        /// </summary>                                                                            [Field("Class")]		public string Class		{			get { return _Class; }			set			{				this.OnPropertyValueChange("Class");				this._Class = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("UserId")]		public string UserId		{			get { return _UserId; }			set			{				this.OnPropertyValueChange("UserId");				this._UserId = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("StoreId")]		public string StoreId		{			get { return _StoreId; }			set			{				this.OnPropertyValueChange("StoreId");				this._StoreId = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("DiyTableId")]		public string DiyTableId		{			get { return _DiyTableId; }			set			{				this.OnPropertyValueChange("DiyTableId");				this._DiyTableId = value;			}		}






		/// <summary>		/// 表格要显示的列		/// </summary>        [Field("TableDiyFieldIds")]		public string TableDiyFieldIds		{			get { return _TableDiyFieldIds; }			set			{				this.OnPropertyValueChange("TableDiyFieldIds");				this._TableDiyFieldIds = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("PageTemplate")]		public string PageTemplate		{			get { return _PageTemplate; }			set			{				this.OnPropertyValueChange("PageTemplate");				this._PageTemplate = value;			}		}






		/// <summary>		/// 可搜索的字段		/// </summary>        [Field("SearchFieldIds")]		public string SearchFieldIds		{			get { return _SearchFieldIds; }			set			{				this.OnPropertyValueChange("SearchFieldIds");				this._SearchFieldIds = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("DiyConfig")]		public string DiyConfig		{			get { return _DiyConfig; }			set			{				this.OnPropertyValueChange("DiyConfig");				this._DiyConfig = value;			}		}






		/// <summary>		/// 可排序字段		/// </summary>        [Field("SortFieldIds")]		public string SortFieldIds		{			get { return _SortFieldIds; }			set			{				this.OnPropertyValueChange("SortFieldIds");				this._SortFieldIds = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("SqlWhere")]		public string SqlWhere		{			get { return _SqlWhere; }			set			{				this.OnPropertyValueChange("SqlWhere");				this._SqlWhere = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("SqlJoin")]		public string SqlJoin		{			get { return _SqlJoin; }			set			{				this.OnPropertyValueChange("SqlJoin");				this._SqlJoin = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("StatisticsFields")]		public string StatisticsFields		{			get { return _StatisticsFields; }			set			{				this.OnPropertyValueChange("StatisticsFields");				this._StatisticsFields = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("IsDeleted")]		public int IsDeleted		{			get { return _IsDeleted; }			set			{				this.OnPropertyValueChange("IsDeleted");				this._IsDeleted = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("DefaultOrderBy")]		public string DefaultOrderBy		{			get { return _DefaultOrderBy; }			set			{				this.OnPropertyValueChange("DefaultOrderBy");				this._DefaultOrderBy = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("NotShowFields")]		public string NotShowFields		{			get { return _NotShowFields; }			set			{				this.OnPropertyValueChange("NotShowFields");				this._NotShowFields = value;			}		}






		/// <summary>		/// 导入模板		/// </summary>        [Field("ImportTemplate")]		public string ImportTemplate		{			get { return _ImportTemplate; }			set			{				this.OnPropertyValueChange("ImportTemplate");				this._ImportTemplate = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("ImportTemplateName")]		public string ImportTemplateName		{			get { return _ImportTemplateName; }			set			{				this.OnPropertyValueChange("ImportTemplateName");				this._ImportTemplateName = value;			}		}






		/// <summary>		/// 更多按钮		/// </summary>        [Field("MoreBtns")]		public string MoreBtns		{			get { return _MoreBtns; }			set			{				this.OnPropertyValueChange("MoreBtns");				this._MoreBtns = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("ImportV8")]		public string ImportV8		{			get { return _ImportV8; }			set			{				this.OnPropertyValueChange("ImportV8");				this._ImportV8 = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("ExportV8")]		public string ExportV8		{			get { return _ExportV8; }			set			{				this.OnPropertyValueChange("ExportV8");				this._ExportV8 = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("ExportMoreBtns")]		public string ExportMoreBtns		{			get { return _ExportMoreBtns; }			set			{				this.OnPropertyValueChange("ExportMoreBtns");				this._ExportMoreBtns = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("DetailPageV8")]		public string DetailPageV8		{			get { return _DetailPageV8; }			set			{				this.OnPropertyValueChange("DetailPageV8");				this._DetailPageV8 = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("BatchSelectMoreBtns")]		public string BatchSelectMoreBtns		{			get { return _BatchSelectMoreBtns; }			set			{				this.OnPropertyValueChange("BatchSelectMoreBtns");				this._BatchSelectMoreBtns = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("PageBtns")]		public string PageBtns		{			get { return _PageBtns; }			set			{				this.OnPropertyValueChange("PageBtns");				this._PageBtns = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("PageTabs")]		public string PageTabs		{			get { return _PageTabs; }			set			{				this.OnPropertyValueChange("PageTabs");				this._PageTabs = value;			}		}






		/// <summary>		/// 是否开启表内编辑		/// </summary>        [Field("InTableEdit")]		public int InTableEdit		{			get { return _InTableEdit; }			set			{				this.OnPropertyValueChange("InTableEdit");				this._InTableEdit = value;			}		}






		/// <summary>		/// 表内可编辑字段		/// </summary>        [Field("InTableEditFields")]		public string InTableEditFields		{			get { return _InTableEditFields; }			set			{				this.OnPropertyValueChange("InTableEditFields");				this._InTableEditFields = value;			}		}






		/// <summary>		/// 多级表头数据		/// </summary>        [Field("TableHeaders")]		public string TableHeaders		{			get { return _TableHeaders; }			set			{				this.OnPropertyValueChange("TableHeaders");				this._TableHeaders = value;			}		}






		/// <summary>		/// 是否是微服务		/// </summary>        [Field("IsMicroiService")]		public int IsMicroiService		{			get { return _IsMicroiService; }			set			{				this.OnPropertyValueChange("IsMicroiService");				this._IsMicroiService = value;			}		}






		/// <summary>		/// 修改时间		/// </summary>        [Field("UpdateTime")]		public DateTime? UpdateTime		{			get { return _UpdateTime; }			set			{				this.OnPropertyValueChange("UpdateTime");				this._UpdateTime = value;			}		}






		/// <summary>		/// 操作人		/// </summary>        [Field("UserName")]		public string UserName		{			get { return _UserName; }			set			{				this.OnPropertyValueChange("UserName");				this._UserName = value;			}		}






		/// <summary>		/// 表单更多按钮		/// </summary>        [Field("FormBtns")]		public string FormBtns		{			get { return _FormBtns; }			set			{				this.OnPropertyValueChange("FormBtns");				this._FormBtns = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("SelectFields")]		public string SelectFields		{			get { return _SelectFields; }			set			{				this.OnPropertyValueChange("SelectFields");				this._SelectFields = value;			}		}






		/// <summary>		/// 		/// </summary>        [Field("JoinTables")]		public string JoinTables		{			get { return _JoinTables; }			set			{				this.OnPropertyValueChange("JoinTables");				this._JoinTables = value;			}		}








		/// <summary>		/// 		/// </summary>  //      [Field("RoleGroup")]		//public string RoleGroup		//{		//	get { return _RoleGroup; }		//	set		//	{		//		this.OnPropertyValueChange("RoleGroup");		//		this._RoleGroup = value;		//	}		//}














		#endregion
		#region Method        /// <summary>							   /// 获取实体中的主键列							   /// </summary>        public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {				_.Id,			};
		}






		/// <summary>		/// 获取列信息		/// </summary>        public override Field[] GetFields()
		{
			return new Field[] {				_.Id,				_.Name,				_.Description,				_.EnName,				_.EnDescription,				_.Code,				_.Url,				_.Link,				_.ParentId,				_.Sort,				_.Icon,				_.IconClass,				_.CreateTime,				_.OpenType,				_.ComponentName,				_.ComponentPath,				_.JquerySelector,				_.MultRun,				_.Display,				_.AppDisplay,
                _.Class,				_.UserId,				_.StoreId,				_.DiyTableId,				_.TableDiyFieldIds,				_.PageTemplate,				_.SearchFieldIds,				_.DiyConfig,				_.SortFieldIds,				_.SqlWhere,				_.SqlJoin,				_.StatisticsFields,				_.IsDeleted,				_.DefaultOrderBy,				_.NotShowFields,				_.ImportTemplate,				_.ImportTemplateName,				_.MoreBtns,				_.ImportV8,				_.ExportV8,				_.ExportMoreBtns,				_.DetailPageV8,				_.BatchSelectMoreBtns,				_.PageBtns,				_.PageTabs,				_.InTableEdit,				_.InTableEditFields,				_.TableHeaders,				_.IsMicroiService,				_.UpdateTime,				_.UserName,				_.FormBtns,				_.SelectFields,				_.JoinTables,				//_.RoleGroup,			};
		}






		/// <summary>		/// 获取值信息		/// </summary>        public override object[] GetValues()
		{
			return new object[] {				this._Id,				this._Name,				this._Description,				this._EnName,				this._EnDescription,				this._Code,				this._Url,				this._Link,				this._ParentId,				this._Sort,				this._Icon,				this._IconClass,				this._CreateTime,				this._OpenType,				this._ComponentName,				this._ComponentPath,				this._JquerySelector,				this._MultRun,				this._Display,				this._AppDisplay,
                this._Class,				this._UserId,				this._StoreId,				this._DiyTableId,				this._TableDiyFieldIds,				this._PageTemplate,				this._SearchFieldIds,				this._DiyConfig,				this._SortFieldIds,				this._SqlWhere,				this._SqlJoin,				this._StatisticsFields,				this._IsDeleted,				this._DefaultOrderBy,				this._NotShowFields,				this._ImportTemplate,				this._ImportTemplateName,				this._MoreBtns,				this._ImportV8,				this._ExportV8,				this._ExportMoreBtns,				this._DetailPageV8,				this._BatchSelectMoreBtns,				this._PageBtns,				this._PageTabs,				this._InTableEdit,				this._InTableEditFields,				this._TableHeaders,				this._IsMicroiService,				this._UpdateTime,				this._UserName,				this._FormBtns,				this._SelectFields,				this._JoinTables,				//this._RoleGroup,			};
		}








		/// <summary>		/// 是否是v1.10.5.6及以上版本实体。		/// </summary>		/// <returns></returns>        public override bool V1_10_5_6_Plus()
		{
			return true;
		}









		#endregion
		#region _Field        /// <summary>							   /// 字段信息							   /// </summary>        public class _
		{






			/// <summary>			/// * 			/// </summary>            public readonly static Field All = new Field("*", "sys_menu");






			/// <summary>			/// 			/// </summary>            public readonly static Field Id = new Field("Id", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field Name = new Field("Name", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field Description = new Field("Description", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field EnName = new Field("EnName", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field EnDescription = new Field("EnDescription", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field Code = new Field("Code", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field Url = new Field("Url", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field Link = new Field("Link", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field ParentId = new Field("ParentId", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field Sort = new Field("Sort", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field Icon = new Field("Icon", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field IconClass = new Field("IconClass", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field CreateTime = new Field("CreateTime", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field OpenType = new Field("OpenType", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field ComponentName = new Field("ComponentName", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field ComponentPath = new Field("ComponentPath", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field JquerySelector = new Field("JquerySelector", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field MultRun = new Field("MultRun", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field Display = new Field("Display", "sys_menu", "");


            public readonly static Field AppDisplay = new Field("AppDisplay", "sys_menu", "");



			/// <summary>			/// 就是Customer			/// </summary>            public readonly static Field Class = new Field("Class", "sys_menu", "就是Customer");






			/// <summary>			/// 			/// </summary>            public readonly static Field UserId = new Field("UserId", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field StoreId = new Field("StoreId", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field DiyTableId = new Field("DiyTableId", "sys_menu", "");






			/// <summary>			/// 表格要显示的列			/// </summary>            public readonly static Field TableDiyFieldIds = new Field("TableDiyFieldIds", "sys_menu", "表格要显示的列");






			/// <summary>			/// 			/// </summary>            public readonly static Field PageTemplate = new Field("PageTemplate", "sys_menu", "");






			/// <summary>			/// 可搜索的字段			/// </summary>            public readonly static Field SearchFieldIds = new Field("SearchFieldIds", "sys_menu", "可搜索的字段");






			/// <summary>			/// 			/// </summary>            public readonly static Field DiyConfig = new Field("DiyConfig", "sys_menu", "");






			/// <summary>			/// 可排序字段			/// </summary>            public readonly static Field SortFieldIds = new Field("SortFieldIds", "sys_menu", "可排序字段");






			/// <summary>			/// 			/// </summary>            public readonly static Field SqlWhere = new Field("SqlWhere", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field SqlJoin = new Field("SqlJoin", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field StatisticsFields = new Field("StatisticsFields", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field IsDeleted = new Field("IsDeleted", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field DefaultOrderBy = new Field("DefaultOrderBy", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field NotShowFields = new Field("NotShowFields", "sys_menu", "");






			/// <summary>			/// 导入模板			/// </summary>            public readonly static Field ImportTemplate = new Field("ImportTemplate", "sys_menu", "导入模板");






			/// <summary>			/// 			/// </summary>            public readonly static Field ImportTemplateName = new Field("ImportTemplateName", "sys_menu", "");






			/// <summary>			/// 更多按钮			/// </summary>            public readonly static Field MoreBtns = new Field("MoreBtns", "sys_menu", "更多按钮");






			/// <summary>			/// 			/// </summary>            public readonly static Field ImportV8 = new Field("ImportV8", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field ExportV8 = new Field("ExportV8", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field ExportMoreBtns = new Field("ExportMoreBtns", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field DetailPageV8 = new Field("DetailPageV8", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field BatchSelectMoreBtns = new Field("BatchSelectMoreBtns", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field PageBtns = new Field("PageBtns", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field PageTabs = new Field("PageTabs", "sys_menu", "");






			/// <summary>			/// 是否开启表内编辑			/// </summary>            public readonly static Field InTableEdit = new Field("InTableEdit", "sys_menu", "是否开启表内编辑");






			/// <summary>			/// 表内可编辑字段			/// </summary>            public readonly static Field InTableEditFields = new Field("InTableEditFields", "sys_menu", "表内可编辑字段");






			/// <summary>			/// 多级表头数据			/// </summary>            public readonly static Field TableHeaders = new Field("TableHeaders", "sys_menu", "多级表头数据");






			/// <summary>			/// 是否是微服务			/// </summary>            public readonly static Field IsMicroiService = new Field("IsMicroiService", "sys_menu", "是否是微服务");






			/// <summary>			/// 修改时间			/// </summary>            public readonly static Field UpdateTime = new Field("UpdateTime", "sys_menu", "修改时间");






			/// <summary>			/// 操作人			/// </summary>            public readonly static Field UserName = new Field("UserName", "sys_menu", "操作人");






			/// <summary>			/// 表单更多按钮			/// </summary>            public readonly static Field FormBtns = new Field("FormBtns", "sys_menu", "表单更多按钮");






			/// <summary>			/// 			/// </summary>            public readonly static Field SelectFields = new Field("SelectFields", "sys_menu", "");






			/// <summary>			/// 			/// </summary>            public readonly static Field JoinTables = new Field("JoinTables", "sys_menu", "");
            //public readonly static Field RoleGroup = new Field("RoleGroup", "sys_menu", "");
		}


		#endregion    }}