/* 功能开关发布：规则白名单、稳定摘要、DryRun、CAS和不可变版本。 */
function fail(msg, data) { return { Code: 0, Msg: msg, Data: data || null }; }
function admin() { var u = V8.CurrentUser || {}; return u && u.Id && Number(u.Level || 0) >= 9999; }
if (!admin()) return fail('权限不足：只有超级管理员才能发布功能开关。');
function text(value) { return value === null || value === undefined ? '' : String(value).replace(/^\s+|\s+$/g, ''); }
function list(value) { if (!value) return []; if (typeof value === 'string') { try { value = JSON.parse(value); } catch (ignore) { value = value.split(','); } } if (value.length === undefined) return []; var out = []; for (var i = 0; i < value.length; i++) out.push(value[i]); return out; }
function unique(value, max, label) { var rows = list(value), seen = {}, out = []; for (var i = 0; i < rows.length; i++) { var item = text(rows[i]); if (!item || seen[item]) continue; seen[item] = true; out.push(item); } if (out.length > max) throw new Error(label + '最多' + max + '项。'); out.sort(); return out; }
function parse(value, fallback, label) { if (!value) return fallback; if (typeof value !== 'string') return value; try { return JSON.parse(value); } catch (error) { throw new Error(label + '不是有效JSON。'); } }
function enabled(value, fallback) { if (value === null || value === undefined || value === '') return fallback ? 1 : 0; return value === false || value === 0 || text(value) === '0' || text(value).toLowerCase() === 'false' ? 0 : 1; }
function stable(value, depth) { if (depth > 30) throw new Error('规则JSON嵌套不能超过30层。'); if (value === null || value === undefined) return 'null'; if (typeof value === 'string' || typeof value === 'boolean') return JSON.stringify(value); if (typeof value === 'number') { if (!isFinite(value)) throw new Error('规则包含非有限数字。'); return JSON.stringify(value); } if (value.length !== undefined && typeof value !== 'string') { var rows = []; for (var a = 0; a < value.length; a++) rows.push(stable(value[a], depth + 1)); return '[' + rows.join(',') + ']'; } if (typeof value !== 'object') throw new Error('规则只允许JSON数据。'); var keys = Object.keys(value).sort(), fields = []; for (var k = 0; k < keys.length; k++) { var key = keys[k]; if (key === '__proto__' || key === 'prototype' || key === 'constructor') throw new Error('规则包含禁止字段。'); fields.push(JSON.stringify(key) + ':' + stable(value[key], depth + 1)); } return '{' + fields.join(',') + '}'; }
var param = V8.Param || {}, flagKey = text(param.FlagKey), name = text(param.Name), versionNo = text(param.VersionNo), expectedHash = text(param.ExpectedContentHash).toLowerCase();
if (!/^[A-Za-z0-9][A-Za-z0-9._:-]{1,98}$/.test(flagKey) || !name) return fail('FlagKey格式无效，Name不能为空。');
if (!/^v?\d+\.\d+(\.\d+)?([-.][0-9A-Za-z.-]+)?$/.test(versionNo)) return fail('VersionNo必须是语义版本。');
var rawRules; try { rawRules = parse(param.Rules || param.RulesJson, {}, 'RulesJson'); if (!rawRules || typeof rawRules !== 'object' || rawRules.length !== undefined) throw new Error('RulesJson必须是JSON对象。'); var allowedKeys = { UserIds: 1, ExcludedUserIds: 1, DeptIds: 1, RoleIds: 1 }; var ruleKeys = Object.keys(rawRules); for (var rk = 0; rk < ruleKeys.length; rk++) if (!allowedKeys[ruleKeys[rk]]) throw new Error('RulesJson包含不支持的字段：' + ruleKeys[rk]); }
catch (error) { return fail(error.message); }
var rules = { UserIds: unique(rawRules.UserIds, 500, '用户规则'), ExcludedUserIds: unique(rawRules.ExcludedUserIds, 500, '排除用户规则'), DeptIds: unique(rawRules.DeptIds, 500, '部门规则'), RoleIds: unique(rawRules.RoleIds, 500, '角色规则') };
var percentage = Number(param.Percentage === undefined ? 100 : param.Percentage); if (!isFinite(percentage) || percentage < 0 || percentage > 100) return fail('Percentage必须在0到100之间。'); percentage = Math.round(percentage * 100) / 100;
var startTime = text(param.StartTime), endTime = text(param.EndTime); if (startTime && endTime && startTime >= endTime) return fail('EndTime必须晚于StartTime。');
var enabledValue = enabled(param.Enabled, false), snapshot = { FlagKey: flagKey, Name: name, Description: text(param.Description), Enabled: enabledValue, Percentage: percentage, Variant: text(param.Variant || 'on'), Rules: rules, StartTime: startTime, EndTime: endTime, Owner: text(param.Owner), VersionNo: versionNo };
var canonical; try { canonical = stable(snapshot, 0); } catch (error) { return fail(error.message); }
if (canonical.length > 262144) return fail('功能开关配置不能超过256KB。');
var contentHash = text(V8.EncryptHelper.Sha256Hex(canonical)).toLowerCase(), existing = V8.FormEngine.GetFormData('mci_feature_flag', { _Where: [['FlagKey', '=', flagKey]] }, V8.DbTrans), row = existing && existing.Code === 1 ? existing.Data : null, currentHash = text(row && row.ContentHash).toLowerCase();
if (currentHash !== expectedHash) return fail('功能开关已变化，请刷新后重新校验。', { Conflict: true, CurrentHash: currentHash });
if (row && currentHash === contentHash) return { Code: 1, Data: { FlagId: row.Id, ContentHash: contentHash, VersionNo: row.VersionNo, Reused: true, DryRun: !!param.DryRun }, Msg: '开关内容未变化，已幂等复用。' };
var versionConflict = row ? V8.FormEngine.GetFormData('mci_resource_version', { _Where: [['ResourceType', '=', 'FeatureFlag'], ['AND', 'ResourceId', '=', row.Id], ['AND', 'VersionNo', '=', versionNo]] }, V8.DbTrans) : null;
if (versionConflict && versionConflict.Code === 1 && versionConflict.Data && text(versionConflict.Data.ContentHash).toLowerCase() !== contentHash) return fail('该开关版本号已用于其它内容，请递增版本号。');
if (param.DryRun === true || Number(param.DryRun || 0) === 1) return { Code: 1, Data: { DryRun: true, FlagId: row ? row.Id : '', ContentHash: contentHash, CurrentHash: currentHash, Snapshot: snapshot }, Msg: '功能开关协议和定向规则校验通过，尚未发布。' };
var flagId = row ? text(row.Id) : text(V8.Method.NewUlid()), now = DateNow('yyyy-MM-dd HH:mm:ss'), rawVersion = row && row.RowVersion, rowVersion = Number(rawVersion || 0), expectedVersion = rawVersion === null || rawVersion === undefined || rawVersion === '' ? null : rowVersion;
var data = { Id: flagId, FlagKey: flagKey, Name: name, Description: snapshot.Description, Enabled: enabledValue, Percentage: percentage, Variant: snapshot.Variant, RulesJson: JSON.stringify(rules), StartTime: startTime, EndTime: endTime, Owner: snapshot.Owner, VersionNo: versionNo, ContentHash: contentHash, RowVersion: rowVersion + 1, LastValidatedTime: now }, save;
if (row) { data._Where = [['Id', '=', flagId], ['AND', 'RowVersion', '=', expectedVersion], ['AND', 'ContentHash', '=', currentHash || null]]; save = V8.FormEngine.UptFormDataByWhere('mci_feature_flag', data, V8.DbTrans); }
else save = V8.FormEngine.AddFormData('mci_feature_flag', data, V8.DbTrans);
if (!save || save.Code !== 1) return save || fail('保存功能开关发生并发冲突。');
var versionId = text(V8.Method.NewUlid()), addVersion = V8.FormEngine.AddFormData('mci_resource_version', { Id: versionId, ResourceType: 'FeatureFlag', ResourceId: flagId, ResourceKey: flagKey, VersionNo: versionNo, ContentHash: contentHash, SnapshotJson: canonical, ChangeSummary: text(param.ChangeSummary), Status: 'Published', PublishedTime: now }, V8.DbTrans);
if (!addVersion || addVersion.Code !== 1) return addVersion || fail('保存功能开关不可变版本失败。');
var verify = V8.FormEngine.GetFormData('mci_feature_flag', { Id: flagId }, V8.DbTrans); if (!verify || verify.Code !== 1 || text(verify.Data.ContentHash).toLowerCase() !== contentHash || Number(verify.Data.RowVersion || 0) !== rowVersion + 1) return fail('功能开关发布回读失败，事务已回滚。');
return { Code: 1, Data: { FlagId: flagId, VersionId: versionId, ContentHash: contentHash, VersionNo: versionNo, RowVersion: rowVersion + 1, Reused: false }, Msg: '功能开关已发布。' };
