<template>
  <section class="field-permission-designer" v-mci-loading:form="loading">
    <el-alert v-if="hydrateError" :title="hydrateError" type="error" :closable="false" show-icon />
    <div class="permission-toolbar"><div><strong>字段权限</strong><p>按角色、人员、部门或岗位设置可见和可编辑字段。多个权限组命中时，拒绝优先。</p></div><el-switch v-model="config.Enabled" :disabled="readonly" active-text="启用" /></div>
    <div class="permission-defaults"><span>未指定字段的默认权限</span><el-checkbox v-model="config.DefaultVisible" :disabled="readonly" @change="config.DefaultEditable = config.DefaultEditable && config.DefaultVisible">可见</el-checkbox><el-checkbox v-model="config.DefaultEditable" :disabled="readonly || !config.DefaultVisible">可编辑</el-checkbox></div>
    <div v-if="config.Enabled" class="permission-workspace">
      <aside><el-button :icon="Plus" :disabled="readonly" @click="addRule">新增权限组</el-button><button v-for="(rule,index) in config.Rules" :key="rule.Id" type="button" :class="{active:index===selected}" @click="selected=index"><strong>{{rule.Name || '未命名权限组'}}</strong><small>{{targetCount(rule)}} 个授权对象 · {{rule.Fields.filter(f=>f.Visible).length}} 个可见字段</small></button><p v-if="!config.Rules.length">新增权限组后选择授权对象。</p></aside>
      <div v-if="current" class="permission-detail">
        <div class="group-title"><el-input v-model="current.Name" :disabled="readonly" placeholder="权限组名称" /><el-button :icon="Delete" :disabled="readonly" aria-label="删除权限组" @click="removeRule" /></div>
        <div class="subject-grid"><el-form-item v-for="target in targets" :key="target.key" :label="target.label"><el-select v-model="current[target.key]" multiple filterable remote :remote-method="keyword=>loadSubjects(target,keyword)" :loading="subjectLoading[target.key]" collapse-tags collapse-tags-tooltip :disabled="readonly" :placeholder="'搜索'+target.label"><el-option v-for="row in subjects[target.key]" :key="row.Id" :value="row.Id" :label="row[target.labelField || 'Name'] || row.Account || row.Id" /></el-select></el-form-item></div>
        <el-checkbox v-model="current.Everyone" :disabled="readonly">应用到所有普通用户</el-checkbox>
        <div class="matrix-toolbar"><el-input v-model="search" clearable placeholder="搜索字段名称" /><span>{{filteredFields.length}} 个字段</span></div>
        <div class="field-matrix"><div class="matrix-row matrix-head"><strong>字段</strong><el-checkbox :model-value="allVisible" :indeterminate="someVisible && !allVisible" :disabled="readonly" @change="value=>setAll('Visible',value)">可见</el-checkbox><el-checkbox :model-value="allEditable" :indeterminate="someEditable && !allEditable" :disabled="readonly" @change="value=>setAll('Editable',value)">可编辑</el-checkbox></div><div v-for="field in filteredFields" :key="field.Name" class="matrix-row"><div><strong>{{field.Label || field.Name}}</strong><small>{{field.Name}}</small></div><el-checkbox v-model="entry(field.Name).Visible" :disabled="readonly || field.Name==='Id'" :aria-label="field.Label+'可见'" @change="value=>{if(!value)entry(field.Name).Editable=false}" /><el-checkbox v-model="entry(field.Name).Editable" :disabled="readonly || !entry(field.Name).Visible || field.Name==='Id'" :aria-label="field.Label+'可编辑'" /></div><p v-if="!filteredFields.length">暂无匹配字段</p></div>
      </div><div v-else class="permission-empty">选择或新增一个权限组</div>
    </div>
    <p class="permission-note">超级管理员保留平台管理权限。配置后保存模块生效；隐藏字段不会通过表单、列表或导出返回，只读字段禁止直接接口修改。</p>
  </section>
</template>
<script setup>
import {computed,getCurrentInstance,onMounted,reactive,ref,watch} from 'vue';
import {Plus,Delete} from '@element-plus/icons-vue';
defineOptions({name:'DiyFieldPermissionDesigner',inheritAttrs:false});
const props=defineProps({modelValue:{type:[String,Object],default:''},field:{type:Object,default:()=>({})},FormDiyTableModel:{type:Object,default:()=>({})},FormMode:{type:String,default:''},FieldReadonly:{type:Boolean,default:false}});
const emit=defineEmits(['update:modelValue','CallbackFormValueChange']);const {proxy}=getCurrentInstance();const common=proxy.DiyCommon,api=proxy.DiyApi;
const empty=()=>({Version:1,Enabled:false,DefaultVisible:true,DefaultEditable:true,Rules:[]});const config=reactive(empty()),selected=ref(0),search=ref(''),fields=ref([]),loading=ref(false),subjects=reactive({Roles:[],Users:[],Departments:[],Jobs:[]}),subjectLoading=reactive({});
const targets=[{key:'Roles',label:'角色',table:'sys_role'},{key:'Users',label:'人员',table:'sys_user'},{key:'Departments',label:'部门',table:'sys_dept'},{key:'Jobs',label:'岗位',table:'diy_job',labelField:'JobName'}];
const hydrateError=ref('');
const readonly=computed(()=>props.FieldReadonly || props.FormMode==='View' || !!hydrateError.value),current=computed(()=>config.Rules[selected.value]);
const filteredFields=computed(()=>fields.value.filter(f=>!search.value || (f.Name+' '+f.Label).toLowerCase().includes(search.value.toLowerCase())));
const allVisible=computed(()=>!!filteredFields.value.length && filteredFields.value.every(f=>entry(f.Name)?.Visible)),someVisible=computed(()=>filteredFields.value.some(f=>entry(f.Name)?.Visible));
const allEditable=computed(()=>!!filteredFields.value.length && filteredFields.value.every(f=>entry(f.Name)?.Editable)),someEditable=computed(()=>filteredFields.value.some(f=>entry(f.Name)?.Editable));
let incoming=false;
function hydrate(value){incoming=true;hydrateError.value='';try{const data=typeof value==='string' && value?JSON.parse(value):value;if(data?.Enabled && (data.Version!==1 || !Array.isArray(data.Rules)))throw new Error('字段权限协议或规则格式无效');if(data?.Rules?.some(rule=>!rule || !Array.isArray(rule.Fields)))throw new Error('字段权限字段列表格式无效');Object.assign(config,empty(),data||{});ensureFields();}catch(error){Object.assign(config,empty());hydrateError.value='无法读取已保存的字段权限：'+error.message+'。原配置已保留，请先修复配置。';}queueMicrotask(()=>incoming=false);}
watch(()=>props.modelValue,hydrate,{immediate:true});
watch(config,()=>{if(incoming)return;const text=JSON.stringify(config);emit('update:modelValue',text);emit('CallbackFormValueChange',props.field,text);},{deep:true});
function entry(name){return current.value?.Fields.find(f=>f.Name===name) || {Name:name,Visible:config.DefaultVisible,Editable:config.DefaultEditable};}
function ensureFields(){for(const rule of config.Rules){rule.Fields ||= [];for(const field of fields.value)if(!rule.Fields.some(f=>f.Name===field.Name))rule.Fields.push({Name:field.Name,Visible:field.Name==='Id'||config.DefaultVisible,Editable:field.Name!=='Id'&&config.DefaultVisible&&config.DefaultEditable});}}
function targetCount(rule){return targets.reduce((sum,t)=>sum+(rule[t.key]?.length||0),rule.Everyone?1:0);}
function addRule(){config.Rules.push({Id:crypto.randomUUID(),Name:'权限组 '+(config.Rules.length+1),Everyone:false,Roles:[],Users:[],Departments:[],Jobs:[],Fields:[]});selected.value=config.Rules.length-1;ensureFields();}
function removeRule(){config.Rules.splice(selected.value,1);selected.value=Math.max(0,selected.value-1);}
function setAll(key,value){for(const f of filteredFields.value){if(f.Name==='Id')continue;const item=entry(f.Name);item[key]=value;if(key==='Visible'&&!value)item.Editable=false;if(key==='Editable'&&value)item.Visible=true;}}
function entityId(value){if(Array.isArray(value))return entityId(value[0]);if(value && typeof value==='object')return entityId(value.Id??value.id??value.Value??value.value);const text=String(value??'').trim();if(/^[{[]/.test(text)){try{return entityId(JSON.parse(text));}catch{}}return text;}
async function loadFields(){const id=entityId(props.FormDiyTableModel.DiyTableId);if(!id){fields.value=[];return;}loading.value=true;try{const result=await common.PostAsync(api.GetDiyFieldByDiyTables,{TableIds:[id]});if(Number(result?.Code)!==1)throw new Error(result?.Msg||'读取字段失败');fields.value=(result.Data||[]).filter(f=>f.Name && !['Tabs','CollapseGroup','Divider','Alert','StaticText','Button'].includes(f.Component));ensureFields();}catch(error){common.Tips(error.message,false);}finally{loading.value=false;}}
async function loadSubjects(target,keyword=''){subjectLoading[target.key]=true;try{const result=await common.PostAsync(api.GetDiyTableRow,{TableName:target.table,_SelectFields:['Id',target.labelField || 'Name'],_Keyword:keyword,_PageSize:100,_PageIndex:1});if(Number(result?.Code)!==1)throw new Error(result?.Msg||'读取授权对象失败');const selectedIds=new Set(current.value?.[target.key]||[]);subjects[target.key]=[...subjects[target.key].filter(x=>selectedIds.has(x.Id)),...(result.Data||[])].filter((x,i,a)=>a.findIndex(y=>y.Id===x.Id)===i);}catch(error){common.Tips(error.message,false);}finally{subjectLoading[target.key]=false;}}
watch(()=>entityId(props.FormDiyTableModel.DiyTableId),loadFields);onMounted(()=>{loadFields();for(const target of targets)loadSubjects(target);});
</script>
<style scoped>
.field-permission-designer{width:100%;color:var(--el-text-color-primary)}.permission-toolbar,.permission-defaults,.group-title,.matrix-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px}.permission-toolbar p,.permission-note,small{font-size:12px;color:var(--el-text-color-secondary);line-height:1.6}.permission-defaults{justify-content:flex-start;margin:16px 0;padding:12px 16px;background:var(--el-fill-color-light);border-radius:10px}.permission-workspace{display:grid;grid-template-columns:240px minmax(0,1fr);border:1px solid var(--el-border-color-light);border-radius:12px;overflow:hidden}aside{display:flex;flex-direction:column;gap:8px;padding:14px;background:var(--el-fill-color-extra-light);border-right:1px solid var(--el-border-color-light)}aside button{display:grid;gap:4px;min-height:56px;padding:10px 12px;text-align:left;border:1px solid transparent;border-radius:8px;background:transparent;color:inherit;cursor:pointer}aside button.active{background:var(--el-color-primary-light-9);border-color:var(--el-color-primary-light-7);color:var(--el-color-primary)}.permission-detail{min-width:0;padding:18px}.subject-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px 16px;margin-top:16px}.subject-grid .el-select{width:100%}.matrix-toolbar{margin:18px 0 10px}.matrix-toolbar .el-input{max-width:320px}.field-matrix{max-height:440px;overflow:auto;border:1px solid var(--el-border-color-lighter);border-radius:10px}.matrix-row{display:grid;grid-template-columns:minmax(140px,1fr) 110px 110px;align-items:center;min-height:56px;padding:8px 16px;border-bottom:1px solid var(--el-border-color-lighter)}.matrix-row>div{display:grid;gap:3px}.matrix-head{position:sticky;top:0;z-index:1;background:var(--el-fill-color-light)}.permission-empty{display:grid;place-items:center;min-height:260px;color:var(--el-text-color-secondary)}@media(max-width:900px){.permission-workspace{grid-template-columns:1fr}aside{border-right:0;border-bottom:1px solid var(--el-border-color-light);flex-direction:row;overflow:auto}aside button{min-width:180px}.subject-grid{grid-template-columns:1fr}.matrix-row{grid-template-columns:minmax(100px,1fr) 78px 82px;padding:8px}.permission-toolbar{align-items:flex-start}.permission-defaults{flex-wrap:wrap}}
</style>
