<template>
  <section class="mci-page-enter">
    <MciPageIntro eyebrow="ASSET DELIVERY" title="资产版本、变更门禁与协作租约" description="区块、组件、页面模板、主题和数据适配器以不可变内容哈希发布；跨资源交付由变更集记录计划、证据与回滚。">
      <button type="button" class="mci-button" @click="changeOpen = true">新建变更集</button>
      <button type="button" class="mci-button mci-button--primary" @click="packageOpen = true">新建资产包</button>
    </MciPageIntro>

    <MciStatePanel v-if="state === 'loading'" state="loading" />
    <MciStatePanel v-else-if="state === 'error'" state="error" :message="error" @retry="load" />
    <div v-else class="mci-grid">
      <article class="mci-card mci-section span-8">
        <div class="mci-section__head"><div><h2>可复用资产目录</h2><p>相同内容哈希幂等复用，版本指针使用条件更新。</p></div><span class="mci-badge">{{ packages.length }} 个资产包</span></div>
        <MciStatePanel v-if="!packages.length" state="empty" title="暂无资产包" action="新建资产包" @action="packageOpen = true" />
        <div v-else class="asset-grid"><article v-for="item in packages" :key="String(item.Id)" class="asset-card" :class="{ selected: selectedPackageId === String(item.Id) }" @click="selectPackage(item)"><header><span>{{ assetIcon(item.AssetType) }}</span><div><strong>{{ item.Name }}</strong><small>{{ item.PackageKey }}</small></div><i class="mci-badge" :data-tone="item.Status === 'Published' ? 'success' : 'warning'">{{ item.Status }}</i></header><footer><span>{{ item.AssetType }}</span><span>{{ item.Scope }}</span><span>{{ versionLabel(item) }}</span></footer><div class="asset-actions"><button type="button" @click.stop="openPublish(item)">发布版本</button><button type="button" :disabled="item.Status !== 'Published'" @click.stop="resolveAsset(item)">解析</button></div></article></div>
        <pre v-if="resolvedAsset" class="mci-code resolved">{{ JSON.stringify(resolvedAsset, null, 2) }}</pre>
      </article>

      <article class="mci-card mci-section span-4">
        <div class="mci-section__head"><div><h2>不可变版本</h2><p>{{ selectedPackage?.Name || '选择资产包查看版本' }}</p></div><span class="mci-badge">{{ selectedVersions.length }} 版</span></div>
        <MciStatePanel v-if="!selectedPackage" state="empty" title="请选择资产包" />
        <MciStatePanel v-else-if="!selectedVersions.length" state="empty" title="尚未发布版本" action="发布首个版本" @action="openPublish(selectedPackage!)" />
        <ol v-else class="version-list"><li v-for="item in selectedVersions" :key="String(item.Id)" :class="{ current: item.Id === selectedPackage?.CurrentVersionId }"><span></span><div><strong>{{ item.VersionNo }}</strong><small>{{ item.Status }} · {{ item.PublishedTime }}</small><code>{{ String(item.ContentHash || '').slice(0, 22) }}</code></div></li></ol>
      </article>

      <article class="mci-card mci-section span-7">
        <div class="mci-section__head"><div><h2>跨资源变更门禁</h2><p>资源清单、测试证据与回滚方案共同形成交付台账。</p></div><span class="mci-badge">{{ changes.length }} 项</span></div>
        <MciStatePanel v-if="!changes.length" state="empty" title="暂无变更集" action="新建变更集" @action="changeOpen = true" />
        <MciDataTable v-else :rows="changes" :columns="changeColumns"><template #actions="{ row }"><button type="button" :disabled="action.status === 'loading'" @click="validateChange(row)">校验门禁</button></template></MciDataTable>
        <pre v-if="validationResult" class="mci-code result-code">{{ JSON.stringify(validationResult, null, 2) }}</pre>
      </article>

      <article class="mci-card mci-section span-5">
        <div class="mci-section__head"><div><h2>协作编辑租约</h2><p>跨浏览器、跨节点的单资源编辑权由共享租约和栅栏令牌保护。</p></div><span class="mci-badge" :data-tone="leaseResult?.State === 'Active' ? 'success' : 'neutral'">{{ leaseResult?.State || '未持有' }}</span></div>
        <div class="lease-form"><label class="mci-field"><span>资源类型</span><select v-model="leaseForm.ResourceType"><option>PageEngine</option><option>FormEngine</option><option>AssetPackage</option><option>PrintTemplate</option><option>ApiEngine</option></select></label><label class="mci-field"><span>资源Id</span><input v-model.trim="leaseForm.ResourceId" placeholder="选择资产包时自动填充" /></label><label class="mci-field full"><span>本客户端租约Id</span><input v-model.trim="leaseForm.ClientLeaseId" /></label></div>
        <div class="lease-actions"><button type="button" class="mci-button mci-button--primary" @click="lease('Acquire')">获取</button><button type="button" class="mci-button" @click="lease('Renew')">续租</button><button type="button" class="mci-button" @click="lease('Inspect')">查看</button><button type="button" class="mci-button mci-button--danger" @click="lease('Release')">释放</button></div>
        <code v-if="leaseResult" class="mci-code">Holder: {{ leaseResult.HolderName || '—' }}\nFencingToken: {{ leaseResult.FencingToken || '—' }}\nLeaseExpiresAt: {{ leaseResult.LeaseExpiresAt || '—' }}</code>
        <div v-if="action.message" class="feedback" :data-state="action.status" role="status">{{ action.message }}</div>
      </article>
    </div>

    <MciDialog :open="packageOpen" title="新建可复用资产包" confirm-text="创建资产包" :busy="action.status === 'loading'" @cancel="packageOpen = false" @confirm="createPackage">
      <div class="form-grid"><label class="mci-field"><span>资产包Key</span><input v-model.trim="packageForm.PackageKey" placeholder="sales-dashboard-block" /></label><label class="mci-field"><span>资产包名称</span><input v-model.trim="packageForm.Name" placeholder="销售看板区块" /></label><label class="mci-field"><span>类型</span><select v-model="packageForm.AssetType"><option>Block</option><option>Component</option><option>PageTemplate</option><option>Theme</option><option>DataAdapter</option></select></label><label class="mci-field"><span>作用域</span><select v-model="packageForm.Scope"><option>Tenant</option><option>Application</option><option>Official</option></select></label><label class="mci-field"><span>负责人</span><input v-model.trim="packageForm.Owner" /></label><label class="mci-field"><span>标签 JSON</span><input v-model="packageForm.TagsJson" /></label><label class="mci-field full"><span>说明</span><textarea v-model="packageForm.Description"></textarea></label></div>
    </MciDialog>
    <MciDialog :open="publishOpen" title="发布不可变资产版本" confirm-text="确认发布" :busy="action.status === 'loading'" @cancel="publishOpen = false" @confirm="publishVersion">
      <div class="form-grid"><label class="mci-field"><span>版本号</span><input v-model.trim="publishForm.VersionNo" placeholder="1.0.0" /></label><label class="mci-field"><span>最低平台版本</span><input v-model.trim="publishForm.MinPlatformVersion" placeholder="可选" /></label><label class="mci-field"><span>最高兼容版本</span><input v-model.trim="publishForm.MaxPlatformVersion" placeholder="可选" /></label><label class="mci-field full"><span>Manifest JSON</span><textarea v-model="publishForm.ManifestJson" spellcheck="false"></textarea><small>协议固定为 microi.asset.v1；组件可声明属性、设置器、事件、插槽和运行端。</small></label><label class="mci-field full"><span>内容 JSON</span><textarea v-model="publishForm.ContentJson" spellcheck="false"></textarea></label><label class="mci-field full"><span>依赖 JSON</span><textarea v-model="publishForm.DependenciesJson" spellcheck="false"></textarea><small>每项支持 PackageKey、MinVersion、MaxVersion、Optional；发布前验证完整依赖图和循环。</small></label></div>
      <div class="publish-validation"><p>内容发布后不可修改；请先执行只读校验，再确认发布。</p><button type="button" class="mci-button" :disabled="action.status === 'loading'" @click="validateVersion">仅校验，不发布</button></div>
      <pre v-if="publishPlan" class="mci-code result-code">{{ JSON.stringify(publishPlan, null, 2) }}</pre>
    </MciDialog>
    <MciDialog :open="changeOpen" title="新建跨资源变更集" confirm-text="创建并校验" :busy="action.status === 'loading'" @cancel="changeOpen = false" @confirm="createChange">
      <div class="form-grid"><label class="mci-field"><span>变更Key</span><input v-model.trim="changeForm.ChangeKey" placeholder="release-2026-08-09" /></label><label class="mci-field"><span>变更名称</span><input v-model.trim="changeForm.Name" /></label><label class="mci-field"><span>环境</span><select v-model="changeForm.Environment"><option>Development</option><option>Test</option><option>Staging</option><option>Production</option></select></label><label class="mci-field"><span>负责人</span><input v-model.trim="changeForm.Owner" /></label><label class="mci-field full"><span>资源清单 JSON</span><textarea v-model="changeForm.ResourcesJson" spellcheck="false"></textarea></label><label class="mci-field full"><span>测试证据 JSON</span><textarea v-model="changeForm.EvidenceJson" spellcheck="false"></textarea></label><label class="mci-field full"><span>回滚方案 JSON</span><textarea v-model="changeForm.RollbackJson" spellcheck="false"></textarea></label></div>
    </MciDialog>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import MciDataTable from '../components/MciDataTable.vue'
import MciDialog from '../components/MciDialog.vue'
import MciPageIntro from '../components/MciPageIntro.vue'
import MciStatePanel from '../components/MciStatePanel.vue'
import type { ActionState, HostContext } from '../domain/models'
import { addRow, getTable, runEngine } from '../platform/client'

const props = defineProps<{ context: HostContext }>()
type Row = Record<string, any>
const packages = ref<Row[]>([]), versions = ref<Row[]>([]), changes = ref<Row[]>([]), sessions = ref<Row[]>([])
const selectedPackageId = ref(''), state = ref<'loading' | 'ready' | 'error'>('loading'), error = ref(''), action = reactive<ActionState>({ status: 'idle' })
const packageOpen = ref(false), publishOpen = ref(false), changeOpen = ref(false), publishTarget = ref<Row | null>(null)
const resolvedAsset = ref<unknown>(null), validationResult = ref<unknown>(null), publishPlan = ref<unknown>(null), leaseResult = ref<Row | null>(null)
const packageForm = reactive({ PackageKey: '', Name: '', AssetType: 'Block', Scope: 'Tenant', Owner: '', TagsJson: '[]', Description: '' })
const publishForm = reactive({ VersionNo: '1.0.0', MinPlatformVersion: '', MaxPlatformVersion: '', ManifestJson: '{}', ContentJson: '{}', DependenciesJson: '[]' })
const changeForm = reactive({ ChangeKey: '', Name: '', Environment: 'Test', Owner: '', ResourcesJson: '[]', EvidenceJson: '[]', RollbackJson: '{"steps":[]}' })
const leaseForm = reactive({ ResourceType: 'AssetPackage', ResourceId: '', ClientLeaseId: createLeaseId() })
const selectedPackage = computed(() => packages.value.find((item) => String(item.Id) === selectedPackageId.value) || null)
const selectedVersions = computed(() => versions.value.filter((item) => String(item.PackageId) === selectedPackageId.value))
const changeColumns = [{ key: 'Name', label: '变更' }, { key: 'Environment', label: '环境', tone: true }, { key: 'Status', label: '状态', tone: true }, { key: 'Owner', label: '负责人' }, { key: 'PlanHash', label: '计划哈希' }, { key: 'UpdateTime', label: '更新时间' }]
function createLeaseId() { try { return `studio-${crypto.randomUUID()}` } catch { return `studio-${Date.now()}-${Math.random().toString(16).slice(2)}` } }
function parseJson(text: string, label: string) { try { return JSON.parse(text || '{}') } catch { throw new Error(`${label}必须是有效 JSON。`) } }
function assetIcon(type: string) { return ({ Block: '▦', Component: '◇', PageTemplate: '▤', Theme: '◉', DataAdapter: '⇄' } as Record<string,string>)[type] || '□' }
function versionLabel(item: Row) { const version = versions.value.find((row) => row.Id === item.CurrentVersionId); return version?.VersionNo || '未发布' }
async function load() { state.value = 'loading'; error.value = ''; try { const [p, v, c, s] = await Promise.all([getTable<Row>(props.context, 'mci_asset_package'), getTable<Row>(props.context, 'mci_asset_version', { _OrderBy: 'PublishedTime', _OrderByType: 'DESC' }), getTable<Row>(props.context, 'mci_change_set'), getTable<Row>(props.context, 'mci_collaboration_session', { _Where: [['State', '=', 'Active']] })]); packages.value = p.rows; versions.value = v.rows; changes.value = c.rows; sessions.value = s.rows; if (!selectedPackageId.value && packages.value.length) selectPackage(packages.value[0]); state.value = 'ready' } catch (e) { error.value = e instanceof Error ? e.message : '加载失败'; state.value = 'error' } }
async function act<T>(work: () => Promise<T>, success: string) { action.status = 'loading'; action.message = ''; try { const result = await work(); action.status = 'success'; action.message = success; return result } catch (e) { action.status = 'error'; action.message = e instanceof Error ? e.message : '执行失败'; return null } }
function selectPackage(item: Row) { selectedPackageId.value = String(item.Id); leaseForm.ResourceType = 'AssetPackage'; leaseForm.ResourceId = String(item.Id) }
async function createPackage() { if (!/^[a-z0-9][a-z0-9.-]{1,138}$/.test(packageForm.PackageKey) || !packageForm.Name) { action.status = 'error'; action.message = '资产包Key必须使用小写字母、数字、点或短横线，名称不能为空。'; return } let tags: unknown; try { tags = parseJson(packageForm.TagsJson, '标签') } catch (e) { action.status = 'error'; action.message = (e as Error).message; return } const result = await act(() => addRow<Row>(props.context, 'mci_asset_package', { ...packageForm, TagsJson: JSON.stringify(tags), CurrentVersionId: '', Status: 'Draft' }), '资产包已创建。'); if (result) { packageOpen.value = false; await load() } }
function bumpVersion(value: unknown) { const match = String(value || '').match(/^v?(\d+)\.(\d+)\.(\d+)/); return match ? `${match[1]}.${match[2]}.${Number(match[3]) + 1}` : '1.0.0' }
function manifestTemplate(item: Row) { const base: Row = { Schema: 'microi.asset.v1', Name: item.PackageKey, Label: item.Name, Platforms: ['Web', 'MobileWeb'], Description: item.Description || '' }; if (item.AssetType === 'Component') base.Component = { Name: item.PackageKey.replace(/(^|[-.])(\w)/g, (_: string, __: string, char: string) => char.toUpperCase()), Props: [{ Name: 'title', Label: '标题', Type: 'String', Setter: 'Text', Required: false }], Events: [], Slots: [] }; return base }
function contentTemplate(type: string) { if (type === 'PageTemplate') return { JsonObj: { formConfig: { gutter: 12, mask: true, drag: true, left: true }, wrapperList: [] } }; if (type === 'Block') return { Wrappers: [{ type: 'wrapper', wrapperOption: { number: 'asset-wrapper', title: '区块' }, widgetList: [] }] }; if (type === 'Component') return { Widget: { type: 'html', widgetOption: { number: 'asset-widget', title: '组件', html: '<div>Microi吾码组件</div>' } } }; if (type === 'Theme') return { FormConfig: { gutter: 12, dark: false } }; return { Adapter: { AdapterKey: 'data-adapter', SourceType: 'ApiEngine', ApiEngineKey: '', RequestMap: {}, ResponseMap: {} } } }
function prettyStored(value: unknown, fallback: unknown) { try { return JSON.stringify(typeof value === 'string' ? JSON.parse(value) : (value || fallback), null, 2) } catch { return JSON.stringify(fallback, null, 2) } }
function openPublish(item: Row) { publishTarget.value = item; selectPackage(item); resolvedAsset.value = null; publishPlan.value = null; const current = versions.value.find((row) => row.Id === item.CurrentVersionId); publishForm.VersionNo = bumpVersion(current?.VersionNo); publishForm.MinPlatformVersion = String(current?.MinPlatformVersion || ''); publishForm.MaxPlatformVersion = String(current?.MaxPlatformVersion || ''); publishForm.ManifestJson = prettyStored(current?.ManifestJson, manifestTemplate(item)); publishForm.ContentJson = prettyStored(current?.ContentJson, contentTemplate(item.AssetType)); publishForm.DependenciesJson = prettyStored(current?.DependenciesJson, []); publishOpen.value = true }
function readPublishPayload(dryRun: boolean) { const item = publishTarget.value; if (!item) throw new Error('请先选择资产包。'); const current = versions.value.find((row) => row.Id === item.CurrentVersionId); return { PackageId: item.Id, VersionNo: publishForm.VersionNo, ExpectedCurrentHash: current?.ContentHash || '', Manifest: parseJson(publishForm.ManifestJson, 'Manifest'), Content: parseJson(publishForm.ContentJson, '内容'), Dependencies: parseJson(publishForm.DependenciesJson, '依赖'), MinPlatformVersion: publishForm.MinPlatformVersion, MaxPlatformVersion: publishForm.MaxPlatformVersion, DryRun: dryRun } }
async function validateVersion() { let payload: Row; try { payload = readPublishPayload(true) } catch (e) { action.status = 'error'; action.message = (e as Error).message; return } const result = await act(() => runEngine<Row>(props.context, 'mci-asset-publish', payload), '资产协议、内容和依赖图校验通过，未产生写入。'); if (result) publishPlan.value = result }
async function publishVersion() { let payload: Row; try { payload = readPublishPayload(false) } catch (e) { action.status = 'error'; action.message = (e as Error).message; return } const result = await act(() => runEngine<Row>(props.context, 'mci-asset-publish', payload), '资产版本已发布。'); if (result) { publishOpen.value = false; publishPlan.value = null; await load() } }
async function resolveAsset(item: Row) { const result = await act(() => runEngine(props.context, 'mci-asset-resolve', { PackageKey: item.PackageKey }), '资产依赖已解析。'); if (result) { selectPackage(item); resolvedAsset.value = result } }
async function createChange() { if (!changeForm.ChangeKey || !changeForm.Name) { action.status = 'error'; action.message = '变更Key和名称不能为空。'; return } let resources: unknown, evidence: unknown, rollback: unknown; try { resources = parseJson(changeForm.ResourcesJson, '资源清单'); evidence = parseJson(changeForm.EvidenceJson, '测试证据'); rollback = parseJson(changeForm.RollbackJson, '回滚方案') } catch (e) { action.status = 'error'; action.message = (e as Error).message; return } const row = await act(() => addRow<Row>(props.context, 'mci_change_set', { ...changeForm, Status: 'Draft', PlanHash: '', ResourcesJson: JSON.stringify(resources), EvidenceJson: JSON.stringify(evidence), RollbackJson: JSON.stringify(rollback) }), '变更集已创建。'); if (row) { changeOpen.value = false; await load(); const created = changes.value.find((item) => item.ChangeKey === changeForm.ChangeKey); if (created) await validateChange(created) } }
async function validateChange(row: Row) { const result = await act(() => runEngine(props.context, 'mci-change-set-validate', { ChangeSetId: row.Id }), '变更门禁已校验。'); if (result) { validationResult.value = result; await load() } }
async function lease(command: 'Acquire' | 'Renew' | 'Release' | 'Inspect') { if (!leaseForm.ResourceId) { action.status = 'error'; action.message = '资源Id不能为空。'; return } const result = await act(() => runEngine<Row | null>(props.context, 'mci-collaboration-lease', { ...leaseForm, Action: command }), `协作租约“${command}”已处理。`); if (result !== null) { leaseResult.value = result; await load() } else if (command === 'Inspect') leaseResult.value = null }
onMounted(load)
</script>

<style scoped>
.asset-grid { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 11px; }.asset-card { padding: 13px; border: 1px solid var(--mci-border-color); border-radius: var(--mci-shape-card); background: var(--mci-bg-soft); cursor: pointer; }.asset-card.selected { border-color: var(--mci-color-primary); box-shadow: inset 0 0 0 1px var(--mci-color-primary-glow); }.asset-card header { display: grid; grid-template-columns: 38px minmax(0,1fr) auto; align-items: center; gap: 9px; }.asset-card header > span { display: grid; width: 38px; height: 38px; place-items: center; border: 1px solid var(--mci-border-color); border-radius: 10px; color: var(--mci-color-primary); background: var(--mci-bg-elevated); font-size: 17px; }.asset-card header div { display: grid; gap: 2px; min-width: 0; }.asset-card header strong, .asset-card header small { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.asset-card header small { color: var(--mci-text-tertiary); font-family: var(--mci-font-mono); font-size: 9px; }.asset-card header i { font-style: normal; }.asset-card footer { display: flex; flex-wrap: wrap; gap: 6px; margin: 13px 0; }.asset-card footer span { padding: 3px 7px; border-radius: var(--mci-radius-full); color: var(--mci-text-secondary); background: var(--mci-bg-elevated); font-size: 10px; }.asset-actions { display: flex; gap: 7px; }.asset-actions button { min-height: 32px; flex: 1; }.resolved, .result-code { max-height: 340px; margin-top: 12px; }.version-list { display: grid; gap: 13px; margin: 0; padding: 0; list-style: none; }.version-list li { display: grid; grid-template-columns: 10px minmax(0,1fr); gap: 9px; }.version-list li > span { width: 8px; height: 8px; margin-top: 5px; border-radius: 50%; background: var(--mci-text-tertiary); }.version-list li.current > span { background: var(--mci-color-success); box-shadow: 0 0 0 4px color-mix(in srgb, var(--mci-color-success) 13%, transparent); }.version-list div { display: grid; gap: 3px; }.version-list small { color: var(--mci-text-secondary); }.version-list code { color: var(--mci-text-tertiary); font-size: 10px; }.lease-form, .form-grid { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 12px; }.lease-form .full, .form-grid .full { grid-column: 1 / -1; }.lease-actions { display: flex; flex-wrap: wrap; gap: 7px; margin: 14px 0; }.feedback { margin-top: 12px; padding: 10px; border-radius: var(--mci-shape-input); background: var(--mci-bg-soft); }.feedback[data-state="error"] { color: var(--mci-color-danger); }.feedback[data-state="success"] { color: var(--mci-color-success); }
.publish-validation { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-top: 12px; }.publish-validation p { margin: 0; color: var(--mci-text-secondary); }
@media (max-width: 700px) { .asset-grid, .lease-form, .form-grid { grid-template-columns: 1fr; }.lease-form .full, .form-grid .full { grid-column: auto; } }
</style>
