<template>
  <section class="mci-page-enter">
    <MciPageIntro eyebrow="RELEASE CONTROL" title="发布、审批与回滚控制台" description="计划哈希固定变更，审批证据不可覆盖；门禁、分布式单步执行、断点续跑和条件回滚保持完整审计链。">
      <button type="button" class="mci-button" @click="flagOpen = true">新建功能开关</button>
      <button type="button" class="mci-button" @click="planOpen = true">新建发布计划</button>
    </MciPageIntro>

    <MciStatePanel v-if="state === 'loading'" state="loading" />
    <MciStatePanel v-else-if="state === 'error'" state="error" :message="error" @retry="load" />
    <div v-else class="mci-grid">
      <article class="mci-card mci-section span-4">
        <div class="mci-section__head"><div><h2>功能开关</h2><p>权威身份与稳定分桶。</p></div><span class="mci-badge">{{ flags.length }} 个</span></div>
        <MciStatePanel v-if="!flags.length" state="empty" title="暂无功能开关" action="创建第一个开关" @action="flagOpen = true" />
        <template v-else>
          <label class="mci-field"><span>开关</span><select v-model="flagEval.FlagKey"><option v-for="item in flags" :key="String(item.Id)" :value="item.FlagKey">{{ item.Name }} · {{ item.FlagKey }}</option></select></label>
          <label class="mci-field"><span>主体Key</span><input v-model.trim="flagEval.SubjectKey" placeholder="用户Id、设备Id或业务Key" /></label>
          <button type="button" class="mci-button mci-button--primary full-button" :disabled="action.status === 'loading'" @click="evaluateFlag">评估</button>
          <div v-if="flagResult" class="flag-result" :data-enabled="flagResult.Enabled"><span>{{ flagResult.Enabled ? 'ON' : 'OFF' }}</span><div><strong>{{ flagResult.Variant }}</strong><small>{{ flagResult.Reason }}</small></div></div>
        </template>
      </article>

      <article class="mci-card mci-section span-8">
        <div class="mci-section__head"><div><h2>发布状态机</h2><p>审批、门禁、发布和回滚均使用计划哈希与行版本。</p></div><span v-if="selectedPlan" class="mci-badge" :data-tone="tone(selectedPlan.Status)">{{ selectedPlan.Status }}</span></div>
        <MciStatePanel v-if="!plans.length" state="empty" title="暂无发布计划" action="创建发布计划" @action="planOpen = true" />
        <template v-else>
          <label class="mci-field"><span>发布计划</span><select v-model="selectedPlanId"><option v-for="item in plans" :key="String(item.Id)" :value="String(item.Id)">{{ item.Name }} · {{ item.VersionNo }} · {{ item.Environment }} · {{ item.Status }}</option></select></label>
          <div v-if="selectedPlan" class="plan-facts">
            <span><small>环境</small><strong>{{ selectedPlan.Environment }}</strong></span><span><small>计划哈希</small><code>{{ shortHash(selectedPlan.PlanHash) }}</code></span><span><small>审批轮次</small><strong>{{ selectedPlan.ReviewRound || 0 }}</strong></span><span><small>行版本</small><strong>{{ selectedPlan.RowVersion || 0 }}</strong></span>
          </div>
          <label v-if="selectedPlan?.Status === 'Reviewing'" class="mci-field"><span>审批意见</span><textarea v-model.trim="approvalComment" placeholder="填写批准或驳回依据"></textarea></label>
          <div class="state-actions">
            <button v-if="selectedPlan?.Status === 'Draft'" type="button" class="mci-button mci-button--primary" :disabled="busy" @click="transition('Submit')">提交审批</button>
            <button v-if="selectedPlan?.Status === 'Reviewing'" type="button" class="mci-button mci-button--primary" :disabled="busy" @click="transition('Approve')">批准</button>
            <button v-if="selectedPlan?.Status === 'Reviewing'" type="button" class="mci-button" :disabled="busy" @click="transition('Reject')">驳回</button>
            <button v-if="['Approved','Blocked','Ready'].includes(String(selectedPlan?.Status || ''))" type="button" class="mci-button" :disabled="busy" @click="validateRelease">执行门禁</button>
            <button v-if="selectedPlan?.Status === 'Ready'" type="button" class="mci-button mci-button--primary" :disabled="busy" @click="executeRelease('Release', false)">开始发布</button>
            <button v-if="latestRun?.Direction === 'Release' && ['Running','Failed'].includes(String(latestRun.Status))" type="button" class="mci-button mci-button--primary" :disabled="busy" @click="executeRelease('Release', latestRun.Status === 'Failed')">{{ latestRun.Status === 'Failed' ? '断点续发' : '继续发布' }}</button>
            <button v-if="selectedPlan?.Status === 'Released' || (selectedPlan?.Status === 'Failed' && latestRun?.Direction === 'Release')" type="button" class="mci-button" :disabled="busy" @click="executeRelease('Rollback', false)">执行回滚</button>
            <button v-if="latestRun?.Direction === 'Rollback' && ['Running','Failed'].includes(String(latestRun.Status))" type="button" class="mci-button" :disabled="busy" @click="executeRelease('Rollback', latestRun.Status === 'Failed')">{{ latestRun.Status === 'Failed' ? '断点续回滚' : '继续回滚' }}</button>
            <button v-if="['Rejected','Blocked','Cancelled','Failed'].includes(String(selectedPlan?.Status || ''))" type="button" class="mci-button" :disabled="busy" @click="transition('Reopen')">重新打开</button>
            <button v-if="['Draft','Reviewing','Approved','Blocked','Ready'].includes(String(selectedPlan?.Status || ''))" type="button" class="mci-button" :disabled="busy" @click="transition('Cancel')">取消</button>
          </div>
          <div v-if="latestRun" class="run-strip"><span class="mci-badge" :data-tone="tone(latestRun.Status)">{{ latestRun.Direction }} · {{ latestRun.Status }}</span><strong>{{ latestRun.Checkpoint || 0 }}/{{ latestRun.TotalSteps || 0 }}</strong><small>{{ latestRun.ErrorMessage || '最近运行台账已回读' }}</small></div>
          <div v-if="gateResult" class="gate-result"><div class="gate-result__summary"><span class="mci-badge" :data-tone="gateResult.Passed ? 'success' : 'danger'">{{ gateResult.Passed ? '全部通过' : '已阻断' }}</span><small>{{ gateResult.CheckedAt }}</small></div><ul><li v-for="item in gateResult.Checks" :key="item.Key"><span :data-pass="item.Passed" aria-hidden="true">{{ item.Passed ? '✓' : '×' }}</span><div><strong>{{ item.Key }}</strong><small>{{ item.Message }}</small></div></li></ul></div>
          <div v-if="runResult" class="run-result"><strong>{{ runResult.Direction }} · {{ runResult.Status }}</strong><span>{{ runResult.Checkpoint }}/{{ runResult.TotalSteps }}</span><small v-if="runResult.ErrorMessage">{{ runResult.ErrorMessage }}</small></div>
        </template>
        <div v-if="action.message" class="feedback" :data-state="action.status" role="status">{{ action.message }}</div>
      </article>

      <article class="mci-card mci-section span-12">
        <div class="mci-section__head"><div><h2>发布计划</h2><p>固定计划、审批证据和运行台账均可独立追溯。</p></div></div>
        <MciDataTable v-if="plans.length" :rows="plans" :columns="planColumns"><template #actions="{ row }"><button type="button" class="mci-button" @click="selectedPlanId = String(row.Id)">选择</button></template></MciDataTable>
        <MciStatePanel v-else state="empty" title="暂无发布计划" />
      </article>
    </div>

    <MciDialog :open="flagOpen" title="发布功能开关" confirm-text="校验并发布" :busy="busy" @cancel="flagOpen = false" @confirm="createFlag(false)">
      <div class="form-grid"><label class="mci-field"><span>开关Key</span><input v-model.trim="flagForm.FlagKey" placeholder="new-portal-shell" /></label><label class="mci-field"><span>开关名称</span><input v-model.trim="flagForm.Name" placeholder="新版门户外壳" /></label><label class="mci-field"><span>语义版本</span><input v-model.trim="flagForm.VersionNo" placeholder="1.0.0" /></label><label class="mci-field"><span>灰度百分比</span><input v-model.number="flagForm.Percentage" type="number" min="0" max="100" step="0.01" /></label><label class="mci-field"><span>负责人</span><input v-model.trim="flagForm.Owner" placeholder="平台团队" /></label><label class="mci-field"><span>启用状态</span><select v-model.number="flagForm.Enabled"><option :value="0">发布但关闭</option><option :value="1">发布并启用</option></select></label><label class="mci-field"><span>开始时间</span><input v-model.trim="flagForm.StartTime" placeholder="2026-08-10 10:00:00" /></label><label class="mci-field"><span>结束时间</span><input v-model.trim="flagForm.EndTime" placeholder="可留空" /></label><label class="mci-field full"><span>定向规则 JSON</span><textarea v-model="flagForm.RulesJson" spellcheck="false"></textarea></label></div>
      <div class="dialog-tools"><button type="button" class="mci-button" :disabled="busy" @click="createFlag(true)">DryRun 校验</button><small>普通用户只能按自身权威身份评估；模拟其它主体仅限超级管理员。</small></div><code v-if="flagPreview" class="mci-code preview">{{ JSON.stringify(flagPreview, null, 2) }}</code>
    </MciDialog>

    <MciDialog :open="planOpen" title="固定发布计划" confirm-text="校验并保存" :busy="busy" @cancel="planOpen = false" @confirm="createPlan(false)">
      <div class="form-grid"><label class="mci-field"><span>发布Key</span><input v-model.trim="planForm.ReleaseKey" placeholder="platform-v2-0-1" /></label><label class="mci-field"><span>发布名称</span><input v-model.trim="planForm.Name" placeholder="AI平台治理发布" /></label><label class="mci-field"><span>版本号</span><input v-model.trim="planForm.VersionNo" placeholder="v2.0.1" /></label><label class="mci-field"><span>环境</span><select v-model="planForm.Environment"><option>Development</option><option>Test</option><option>Staging</option><option>Production</option></select></label><label class="mci-field full"><span>变更摘要</span><textarea v-model.trim="planForm.ChangeSummary"></textarea></label><label class="mci-field full"><span>门禁规则 JSON</span><textarea v-model="planForm.GatesJson" spellcheck="false"></textarea></label><label class="mci-field full"><span>发布步骤 JSON</span><textarea v-model="planForm.ResourcesJson" spellcheck="false"></textarea></label><label class="mci-field full"><span>回滚步骤 JSON</span><textarea v-model="planForm.RollbackJson" spellcheck="false"></textarea></label><label class="mci-field full"><span>审批策略 JSON</span><textarea v-model="planForm.ApprovalPolicyJson" spellcheck="false"></textarea></label><label class="mci-field full"><span>测试与回读证据 JSON</span><textarea v-model="planForm.EvidenceJson" spellcheck="false"></textarea></label></div>
      <div class="dialog-tools"><button type="button" class="mci-button" :disabled="busy" @click="createPlan(true)">DryRun 校验</button><small>生产计划提交审批前必须有回滚步骤和真实证据；计划内容不会自动部署。</small></div><code v-if="planPreview" class="mci-code preview">{{ JSON.stringify(planPreview, null, 2) }}</code>
    </MciDialog>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import MciDataTable from '../components/MciDataTable.vue'
import MciDialog from '../components/MciDialog.vue'
import MciPageIntro from '../components/MciPageIntro.vue'
import MciStatePanel from '../components/MciStatePanel.vue'
import type { ActionState, HostContext } from '../domain/models'
import { getTable, runEngine } from '../platform/client'

const props = defineProps<{ context: HostContext }>()
type Row = Record<string, any>
interface FlagResult { FlagKey: string; Enabled: boolean; Variant: string; Reason: string; EvaluatedAt: string }
interface GateResult { Passed: boolean; CheckedAt: string; RowVersion?: number; Checks: { Key: string; Passed: boolean; Message: string }[] }
interface RunResult { RunId: string; RunKey: string; Status: string; Direction: 'Release' | 'Rollback'; Checkpoint: number; TotalSteps: number; HasMore: boolean; ResumeRequired?: boolean; ErrorMessage?: string }
const flags = ref<Row[]>([]), plans = ref<Row[]>([]), runs = ref<Row[]>([]), state = ref<'loading' | 'ready' | 'error'>('loading'), error = ref('')
const action = reactive<ActionState>({ status: 'idle' }), flagOpen = ref(false), planOpen = ref(false), approvalComment = ref('')
const flagEval = reactive({ FlagKey: '', SubjectKey: 'preview-user' }), flagResult = ref<FlagResult | null>(null), flagPreview = ref<unknown>(null)
const selectedPlanId = ref(''), gateResult = ref<GateResult | null>(null), runResult = ref<RunResult | null>(null), planPreview = ref<unknown>(null)
const flagForm = reactive({ FlagKey: '', Name: '', VersionNo: '1.0.0', Percentage: 100, Owner: '', Enabled: 0, StartTime: '', EndTime: '', RulesJson: '{\n  "UserIds": [],\n  "ExcludedUserIds": [],\n  "DeptIds": [],\n  "RoleIds": []\n}' })
const planForm = reactive({ ReleaseKey: '', Name: '', VersionNo: 'v2.0.1', Environment: 'Test', ChangeSummary: '', GatesJson: '[\n  { "Key": "critical-alerts", "Type": "NoCriticalAlerts", "Required": true },\n  { "Key": "identity-conflicts", "Type": "NoIdentityConflicts", "Required": true },\n  { "Key": "configuration-drift", "Type": "NoConfigurationDrift", "Required": true }\n]', ResourcesJson: '[]', RollbackJson: '[]', ApprovalPolicyJson: '{}', EvidenceJson: '{}' })
const planColumns = [{ key: 'Name', label: '发布' }, { key: 'VersionNo', label: '版本' }, { key: 'Environment', label: '环境' }, { key: 'Status', label: '状态', tone: true }, { key: 'ReviewRound', label: '审批轮次' }, { key: 'LastCheckTime', label: '最近检查' }]
const selectedPlan = computed(() => plans.value.find((item) => String(item.Id) === selectedPlanId.value) || null)
const latestRun = computed(() => runs.value.find((item) => String(item.ReleasePlanId) === selectedPlanId.value) || null)
const busy = computed(() => action.status === 'loading')
function validJson(value: string, label: string) { try { return JSON.parse(value) } catch { throw new Error(`${label}不是有效JSON。`) } }
function shortHash(value: unknown) { const hash = String(value || ''); return hash ? `${hash.slice(0, 12)}…${hash.slice(-8)}` : '—' }
function tone(value: unknown) { const status = String(value || '').toLowerCase(); if (/failed|blocked|rejected/.test(status)) return 'danger'; if (/ready|released|completed|approved/.test(status)) return 'success'; if (/review|running|releasing|rolling/.test(status)) return 'primary'; return 'warning' }
async function load() { state.value = 'loading'; error.value = ''; try { const [f, p, r] = await Promise.all([getTable<Row>(props.context, 'mci_feature_flag'), getTable<Row>(props.context, 'mci_release_plan'), getTable<Row>(props.context, 'mci_release_run')]); flags.value = f.rows; plans.value = p.rows; runs.value = r.rows; flagEval.FlagKey ||= flags.value[0]?.FlagKey || ''; if (!plans.value.some((item) => String(item.Id) === selectedPlanId.value)) selectedPlanId.value = String(plans.value[0]?.Id || ''); state.value = 'ready' } catch (e) { error.value = e instanceof Error ? e.message : '加载失败'; state.value = 'error' } }
async function runAction<T>(work: () => Promise<T>, success: string) { action.status = 'loading'; action.message = ''; try { const result = await work(); action.status = 'success'; action.message = success; return result } catch (e) { action.status = 'error'; action.message = e instanceof Error ? e.message : '执行失败'; return null } }
async function evaluateFlag() { if (!flagEval.FlagKey || !flagEval.SubjectKey) { action.status = 'error'; action.message = '开关和主体Key不能为空。'; return } const result = await runAction(() => runEngine<FlagResult>(props.context, 'mci-feature-flag-evaluate', { FlagKey: flagEval.FlagKey, Context: { SubjectKey: flagEval.SubjectKey } }), '功能开关评估完成。'); if (result) flagResult.value = result }
async function createFlag(dryRun: boolean) { let rules: unknown; try { rules = validJson(flagForm.RulesJson, '定向规则') } catch (e) { action.status = 'error'; action.message = (e as Error).message; return } if (!flagForm.FlagKey || !flagForm.Name || !flagForm.VersionNo || flagForm.Percentage < 0 || flagForm.Percentage > 100) { action.status = 'error'; action.message = '请填写有效的Key、名称、版本和0-100灰度百分比。'; return } const result = await runAction(() => runEngine<Row>(props.context, 'mci-feature-flag-publish', { ...flagForm, Rules: rules, Description: '', Variant: 'on', ExpectedContentHash: '', ChangeSummary: 'AI平台治理中心发布功能开关', DryRun: dryRun }), dryRun ? '功能开关规则校验通过，尚未发布。' : '功能开关已发布。'); if (result && dryRun) flagPreview.value = result; if (result && !dryRun) { flagPreview.value = null; flagOpen.value = false; await load() } }
async function createPlan(dryRun: boolean) { let gates: unknown, resources: unknown, rollback: unknown, policy: unknown, evidence: unknown; try { gates = validJson(planForm.GatesJson, '门禁规则'); resources = validJson(planForm.ResourcesJson, '发布步骤'); rollback = validJson(planForm.RollbackJson, '回滚步骤'); policy = validJson(planForm.ApprovalPolicyJson, '审批策略'); evidence = validJson(planForm.EvidenceJson, '测试证据') } catch (e) { action.status = 'error'; action.message = (e as Error).message; return } if (!planForm.ReleaseKey || !planForm.Name || !planForm.VersionNo) { action.status = 'error'; action.message = '发布Key、名称和版本不能为空。'; return } const result = await runAction(() => runEngine<Row>(props.context, 'mci-release-plan-publish', { ...planForm, Gates: gates, Resources: resources, Rollback: rollback, ApprovalPolicy: policy, Evidence: evidence, ExpectedPlanHash: '', DryRun: dryRun }), dryRun ? '发布计划校验通过，尚未保存。' : '发布计划已固定为草稿。'); if (result && dryRun) planPreview.value = result; if (result && !dryRun) { planPreview.value = null; planOpen.value = false; selectedPlanId.value = String(result.ReleasePlanId || ''); await load() } }
async function transition(nextAction: string) { const plan = selectedPlan.value; if (!plan) return; const result = await runAction(() => runEngine<Row>(props.context, 'mci-release-transition', { ReleasePlanId: plan.Id, Action: nextAction, ExpectedPlanHash: plan.PlanHash, ExpectedRowVersion: Number(plan.RowVersion || 0), Comment: approvalComment.value }), `发布计划已执行${nextAction}。`); if (result) { approvalComment.value = ''; gateResult.value = null; runResult.value = null; await load() } }
async function validateRelease() { const plan = selectedPlan.value; if (!plan) return; const result = await runAction(() => runEngine<GateResult>(props.context, 'mci-release-validate', { ReleasePlanId: plan.Id, ExpectedPlanHash: plan.PlanHash, ExpectedRowVersion: Number(plan.RowVersion || 0), DryRun: false }), '发布门禁执行完成。'); if (result) { gateResult.value = result; await load() } }
function storageKey(plan: Row, direction: string) { return `microi-release:${plan.Id}:${plan.PlanHash}:${direction}` }
function requestKey(plan: Row, direction: string, resume: boolean) { const latest = latestRun.value; if (resume && latest?.IdempotencyKey) return String(latest.IdempotencyKey); const key = storageKey(plan, direction); try { const existing = sessionStorage.getItem(key); if (existing) return existing } catch { /* 沙箱可能禁用存储 */ } const value = `release-${Date.now()}-${Math.random().toString(16).slice(2)}`; try { sessionStorage.setItem(key, value) } catch { /* 使用内存中的本次值 */ } return value }
function clearRequestKey(plan: Row, direction: string) { try { sessionStorage.removeItem(storageKey(plan, direction)) } catch { /* 沙箱可能禁用存储 */ } }
async function executeRelease(direction: 'Release' | 'Rollback', resume: boolean) { const plan = selectedPlan.value; if (!plan) return; const idempotencyKey = requestKey(plan, direction, resume); const result = await runAction(async () => { let current: RunResult | null = null; for (let step = 0; step < 100; step += 1) { current = await runEngine<RunResult>(props.context, 'mci-release-execute', { ReleasePlanId: plan.Id, Direction: direction, IdempotencyKey: idempotencyKey, ExpectedPlanHash: plan.PlanHash, Resume: resume || step > 0 }); if (!current.HasMore || current.ResumeRequired || current.Status === 'Failed') break } if (!current) throw new Error('发布执行器没有返回运行结果。'); return current }, direction === 'Release' ? '发布运行已提交并回读。' : '回滚运行已提交并回读。'); if (!result) return; runResult.value = result; if (result.Status === 'Completed') clearRequestKey(plan, direction); if (result.Status === 'Failed') { action.status = 'error'; action.message = result.ErrorMessage || '执行失败，断点已保存，可使用同一请求继续。' } await load() }
onMounted(load)
</script>

<style scoped>
.form-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:12px; }.form-grid .full { grid-column:1/-1; }.full-button { width:100%; margin-top:12px; }.flag-result { display:flex; align-items:center; gap:12px; margin-top:12px; padding:13px; border:1px solid var(--mci-border-color); border-radius:var(--mci-shape-input); background:var(--mci-bg-soft); }.flag-result>span { display:grid; width:46px; height:32px; place-items:center; border-radius:var(--mci-radius-full); color:var(--mci-text-on-primary); background:var(--mci-color-danger); font-family:var(--mci-font-mono); font-weight:800; }.flag-result[data-enabled="true"]>span { background:var(--mci-color-success); }.flag-result div { display:grid; gap:3px; }.flag-result small,.dialog-tools small { color:var(--mci-text-secondary); }.plan-facts { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:8px; margin:12px 0; }.plan-facts span { display:grid; gap:4px; min-width:0; padding:10px; border:1px solid var(--mci-border-color); border-radius:var(--mci-shape-input); background:var(--mci-bg-soft); }.plan-facts small { color:var(--mci-text-tertiary); }.plan-facts code { overflow:hidden; color:var(--mci-color-primary); text-overflow:ellipsis; }.state-actions,.dialog-tools { display:flex; flex-wrap:wrap; align-items:center; gap:8px; margin-top:12px; }.run-strip,.run-result { display:flex; align-items:center; gap:10px; margin-top:12px; padding:10px; border:1px solid var(--mci-border-color); border-radius:var(--mci-shape-input); background:var(--mci-bg-soft); }.run-strip small,.run-result small { min-width:0; overflow:hidden; color:var(--mci-text-secondary); text-overflow:ellipsis; white-space:nowrap; }.gate-result { margin-top:14px; }.gate-result__summary { display:flex; align-items:center; justify-content:space-between; gap:10px; }.gate-result__summary small { color:var(--mci-text-tertiary); }.gate-result ul { display:grid; gap:8px; padding:0; list-style:none; }.gate-result li { display:flex; align-items:center; gap:10px; padding:10px; border:1px solid var(--mci-border-color); border-radius:var(--mci-shape-input); }.gate-result li>span { display:grid; width:28px; height:28px; place-items:center; border-radius:50%; color:var(--mci-color-danger); background:color-mix(in srgb,var(--mci-color-danger) 8%,var(--mci-bg-elevated)); font-weight:800; }.gate-result li>span[data-pass="true"] { color:var(--mci-color-success); background:color-mix(in srgb,var(--mci-color-success) 8%,var(--mci-bg-elevated)); }.gate-result li div { display:grid; gap:3px; }.gate-result li small { color:var(--mci-text-secondary); }.feedback { margin-top:12px; padding:10px; border-radius:var(--mci-shape-input); background:var(--mci-bg-soft); }.feedback[data-state="error"] { color:var(--mci-color-danger); }.feedback[data-state="success"] { color:var(--mci-color-success); }.preview { max-height:280px; margin-top:10px; }
@media (max-width:900px) { .plan-facts { grid-template-columns:repeat(2,minmax(0,1fr)); } }
@media (max-width:640px) { .form-grid,.plan-facts { grid-template-columns:1fr; }.form-grid .full { grid-column:auto; }.state-actions .mci-button { flex:1 1 calc(50% - 8px); } }
</style>
