//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Microi.net
{
	/// <summary>
	/// 实体类SysLog。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Sys_Log")]
	[Serializable]
	public partial class SysLog : Entity
	{
		#region Model
		private string _Id;
		private string _AppId;
		private string _Api;
		private string _Param;
		private string _Type;
		private string _UserId;
		private string _UserName;
		private string _Title;
		private string _Content;
		private DateTime _CreateTime;
		private string _IP;
		private string _Mac;
		private string _OtherInfo;
		private string _Remark;
		private int _Level;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public string Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 应用程序Id
		/// </summary>
		[Field("AppId")]
		public string AppId
		{
			get { return _AppId; }
			set
			{
				this.OnPropertyValueChange("AppId");
				this._AppId = value;
			}
		}
		/// <summary>
		/// 接口地址
		/// </summary>
		[Field("Api")]
		public string Api
		{
			get { return _Api; }
			set
			{
				this.OnPropertyValueChange("Api");
				this._Api = value;
			}
		}
		/// <summary>
		/// 参数
		/// </summary>
		[Field("Param")]
		public string Param
		{
			get { return _Param; }
			set
			{
				this.OnPropertyValueChange("Param");
				this._Param = value;
			}
		}
		/// <summary>
		/// 日志类型
		/// </summary>
		[Field("Type")]
		public string Type
		{
			get { return _Type; }
			set
			{
				this.OnPropertyValueChange("Type");
				this._Type = value;
			}
		}
		/// <summary>
		/// 操作人SysUserId
		/// </summary>
		[Field("UserId")]
		public string UserId
		{
			get { return _UserId; }
			set
			{
				this.OnPropertyValueChange("UserId");
				this._UserId = value;
			}
		}
		/// <summary>
		/// 操作人
		/// </summary>
		[Field("UserName")]
		public string UserName
		{
			get { return _UserName; }
			set
			{
				this.OnPropertyValueChange("UserName");
				this._UserName = value;
			}
		}
		/// <summary>
		/// 标题
		/// </summary>
		[Field("Title")]
		public string Title
		{
			get { return _Title; }
			set
			{
				this.OnPropertyValueChange("Title");
				this._Title = value;
			}
		}
		/// <summary>
		/// 日志内容
		/// </summary>
		[Field("Content")]
		public string Content
		{
			get { return _Content; }
			set
			{
				this.OnPropertyValueChange("Content");
				this._Content = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("CreateTime")]
		public DateTime CreateTime
		{
			get { return _CreateTime; }
			set
			{
				this.OnPropertyValueChange("CreateTime");
				this._CreateTime = value;
			}
		}
		/// <summary>
		/// 外网IP
		/// </summary>
		[Field("IP")]
		public string IP
		{
			get { return _IP; }
			set
			{
				this.OnPropertyValueChange("IP");
				this._IP = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Mac")]
		public string Mac
		{
			get { return _Mac; }
			set
			{
				this.OnPropertyValueChange("Mac");
				this._Mac = value;
			}
		}
		/// <summary>
		/// 附加信息
		/// </summary>
		[Field("OtherInfo")]
		public string OtherInfo
		{
			get { return _OtherInfo; }
			set
			{
				this.OnPropertyValueChange("OtherInfo");
				this._OtherInfo = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get { return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Level")]
		public int Level
		{
			get { return _Level; }
			set
			{
				this.OnPropertyValueChange("Level");
				this._Level = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.AppId,
				_.Api,
				_.Param,
				_.Type,
				_.UserId,
				_.UserName,
				_.Title,
				_.Content,
				_.CreateTime,
				_.IP,
				_.Mac,
				_.OtherInfo,
				_.Remark,
				_.Level,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._AppId,
				this._Api,
				this._Param,
				this._Type,
				this._UserId,
				this._UserName,
				this._Title,
				this._Content,
				this._CreateTime,
				this._IP,
				this._Mac,
				this._OtherInfo,
				this._Remark,
				this._Level,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Sys_Log");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Sys_Log", "");
			/// <summary>
			/// 应用程序Id
			/// </summary>
			public readonly static Field AppId = new Field("AppId", "Sys_Log", "应用程序Id");
			/// <summary>
			/// 接口地址
			/// </summary>
			public readonly static Field Api = new Field("Api", "Sys_Log", "接口地址");
			/// <summary>
			/// 参数
			/// </summary>
			public readonly static Field Param = new Field("Param", "Sys_Log", "参数");
			/// <summary>
			/// 日志类型
			/// </summary>
			public readonly static Field Type = new Field("Type", "Sys_Log", "日志类型");
			/// <summary>
			/// 操作人SysUserId
			/// </summary>
			public readonly static Field UserId = new Field("UserId", "Sys_Log", "操作人SysUserId");
			/// <summary>
			/// 操作人
			/// </summary>
			public readonly static Field UserName = new Field("UserName", "Sys_Log", "操作人");
			/// <summary>
			/// 标题
			/// </summary>
			public readonly static Field Title = new Field("Title", "Sys_Log", "标题");
			/// <summary>
			/// 日志内容
			/// </summary>
			public readonly static Field Content = new Field("Content", "Sys_Log", "日志内容");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "Sys_Log", "创建时间");
			/// <summary>
			/// 外网IP
			/// </summary>
			public readonly static Field IP = new Field("IP", "Sys_Log", "外网IP");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Mac = new Field("Mac", "Sys_Log", "");
			/// <summary>
			/// 附加信息
			/// </summary>
			public readonly static Field OtherInfo = new Field("OtherInfo", "Sys_Log", "附加信息");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "Sys_Log", "备注");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Level = new Field("Level", "Sys_Log", "");
		}
		#endregion
	}
}