import test from'node:test';
import assert from'node:assert/strict';
import {createHash}from'node:crypto';
import {readFileSync}from'node:fs';
const source=readFileSync(process.env.BUILD_ZIP_TEST_SOURCE_PATH||new URL('./ai-app-download-build-zip.js',import.meta.url),'utf8');
const sha=b=>createHash('sha256').update(b).digest('hex');
const system=(fallback=false)=>({...(fallback?{}:{Security:{Cryptography:{SHA256:{Create:()=>({ComputeHash:b=>createHash('sha256').update(b).digest()})}}},BitConverter:{ToString:b=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('-')}}),Convert:{ToBase64String:b=>Buffer.from(b).toString('base64'),FromBase64String:b=>Buffer.from(b,'base64')}});
function run(body,options={}){
 const bytes=Buffer.isBuffer(body)?body:Buffer.from(body),asset={Path:'.vite/manifest.json',Size:bytes.length,Sha256:sha(bytes),StableFilePathName:'/itdos/micro-app/demo/v1.0.0/.vite/manifest.json',HdfsPath:'/itdos/micro-app/demo/v1.0.0/.vite/manifest.json',...options.asset};
 const index=Buffer.from('<!doctype html>'),assets=[asset,{Path:'index.html',Size:index.length,Sha256:sha(index),StableFilePathName:'/itdos/micro-app/demo/v1.0.0/index.html',HdfsPath:'/itdos/micro-app/demo/v1.0.0/index.html'}];let entries=[],creates=0,httpRequests=[];
 const response=options.response??bytes,manifestHash=sha([...assets].sort((a,b)=>a.Path<b.Path?-1:1).map(a=>a.Path+'\t'+a.Sha256+'\t'+a.Size).join('\n')),app={Id:'a',AppKey:'demo',Name:'Demo',AppType:'MicroService',...(options.committed?{ApplicationType:'MicroService',AppType:'官方应用',AppVersion:'v1.0.0',PublishState:'Completed',CommittedPublishVersionId:'v-1',CommittedRuntimeManifestHash:manifestHash}:{}),...options.app},version={Id:'v-1',AppId:'a',VersionNo:'v1.0.0',PublishState:'Completed',RuntimeManifestHash:manifestHash,RequestFingerprint:sha('request'),RowVersion:1,...options.version};let appReads=0,versionReads=0;
 const v8={Param:{AppId:'a',VersionNo:'v1.0.0'},OsClient:'iTdos',SysConfig:{ApiBase:'https://api.example.test',FileServer:'https://cdn.example.test'},EncryptHelper:{Sha256Hex:s=>sha(s)},FormEngine:{GetFormData:t=>({Code:1,Data:t==='sys_microistore'?(appReads++?{...app,...options.afterApp}:app):{BuildVersion:'v1.0.0',AssetsJson:JSON.stringify(assets),DistHash:options.distHash??manifestHash,EntryPath:'index.html'}}),GetTableData:t=>({Code:1,Data:t==='mci_ai_app_file'?assets.map(a=>({FilePath:'dist/'+a.Path,FileName:a.Path.split('/').at(-1),Size:a.Size,ContentHash:a.Sha256,StorageScope:'PublicBuildStream',PublishHdfsPath:a.StableFilePathName,HdfsPath:a.HdfsPath})):options.versions??[(++versionReads>2?{...version,...options.afterVersion}:version)]})},Http:{GetResponse:({Url,RequireSsrfProtection})=>{httpRequests.push({Url,RequireSsrfProtection});const b=Url.endsWith('index.html')?index:response;return{StatusCode:Object.hasOwn(options,'status')?options.status:200,RawBytes:b,Content:Buffer.from(b).toString('utf8')};}},Method:{GetPrivateFileUrl:()=>({Code:1,Data:'https://hdfs.example.test/manifest.json'}),CreateZip:({Entries})=>{entries=Entries;creates++;return{Code:1,Data:{FileByteBase64:'emlw',Size:3,Sha256:sha(Buffer.from('zip'))}};}}};
 const result=new Function('V8','System','DateNow',source)(v8,system(options.fallback),()=> '2026-10-03 02:00:00');
 return{result,entries,creates,bytes,manifestHash,httpRequests};
}
test('legitimate Vite manifest JSON is included with its exact .vite path and bytes',()=>{const r=run('{"src/app.ts":{"file":"assets/app.js","isEntry":true}}');assert.equal(r.result.Code,1);assert.deepEqual(r.entries.map(x=>x.Path),['.vite/manifest.json','index.html','microi-app-version.json']);assert.deepEqual(Buffer.from(r.entries[0].FileByteBase64,'base64'),r.bytes);});
test('legitimate ordinary JSON, arrays and JSON null remain byte assets',()=>{for(const value of ['{}','[]','null','{"theme":"light","version":2}'])assert.equal(run(value).result.Code,1);});
test('asset content fields named Code cannot override the authenticated byte manifest',()=>{for(const value of ['{"Code":0,"description":"valid application configuration"}','{"Code":1001,"Data":{"isExample":true}}','{"Code":1,"Msg":"fixture"}'])assert.equal(run(value).result.Code,1);});
test('even an envelope-shaped frozen JSON file remains the exact declared file',()=>assert.equal(run('{"Code":0,"Data":null,"Msg":"intentional JSON fixture"}').result.Code,1));
test('HTTP200 business failure envelopes are rejected when their bytes differ from the trusted asset',()=>{for(const value of ['{"Code":0,"Msg":"failure","Data":null}','{"Code":1001,"Msg":"expired"}','{"Code":1002,"Msg":"no permission"}'])assert.throws(()=>run('{"file":"known.js"}',{response:Buffer.from(value)}),/文件长度不一致|SHA-256/);});
test('equal-length business envelope substitution cannot bypass raw SHA verification',()=>{const known='{"file":"known.js"}',bad=Buffer.from('{"Code":0}'.padEnd(known.length));assert.throws(()=>run(known,{response:bad}),/SHA-256/);});
test('different JSON formatting is rejected despite identical semantic content',()=>assert.throws(()=>run('{"a":1}',{response:Buffer.from('{ "a":1 }')}),/文件长度不一致|SHA-256/));
test('non-JSON byte substitution also fails closed',()=>assert.throws(()=>run(Buffer.from([0,255,127,128]),{response:Buffer.from([0,255,127,129])}),/SHA-256/));
test('every status other than exact HTTP200 fails before ZIP construction',()=>{for(const status of [0,undefined,199,201,204,206,301,403,404,500,'200oops']){assert.throws(()=>run('asset-bytes',{status}),/HTTP/);}});
test('unknown and malformed status does not become a successful full file',()=>assert.throws(()=>run('asset-bytes',{status:'unknown'}),/HTTP/));
test('missing malformed negative fractional or unsafe declared size fails closed',()=>{for(const Size of [undefined,null,-1,1.5,'2oops',Number.MAX_SAFE_INTEGER+1])assert.throws(()=>run(Buffer.from([1,2]),{asset:{Size}}),/长度|大小/);});
test('missing malformed and wrong SHA fails closed',()=>{for(const Sha256 of [undefined,null,'','z'.repeat(64),'0'.repeat(63),'0'.repeat(64)])assert.throws(()=>run(Buffer.from([1,2]),{asset:{Sha256}}),/SHA-256|摘要/);});
test('zero-byte files require the exact empty raw SHA and are retained',()=>{const r=run(Buffer.alloc(0));assert.equal(r.result.Code,1);assert.equal(r.entries[0].FileByteBase64,'');assert.throws(()=>run(Buffer.alloc(0),{asset:{Sha256:'0'.repeat(64)}}),/SHA-256/);});
test('native-unavailable compatibility fallback verifies known binary and multiblock raw bytes',()=>{for(const b of [Buffer.from('abc'),Buffer.from([0,128,255,254,127,1]),Buffer.from(Array.from({length:4097},(_,i)=>i&255))]){const r=run(b,{fallback:true});assert.equal(r.result.Code,1);assert.deepEqual(Buffer.from(r.entries[0].FileByteBase64,'base64'),b);}});

const attempt=(body,options)=>{try{return run(body,options);}catch(error){return{Error:error.message};}};
const metadata=r=>JSON.parse(r.entries.find(e=>e.Path==='microi-app-version.json').Content);
test('all newly exported ZIP metadata contains the hash of its complete verified byte manifest',()=>{const r=run('{}',{app:{AppType:'Web',ApplicationType:'Web'}});assert.equal(metadata(r).RuntimeManifestHash,r.manifestHash);assert.match(metadata(r).RuntimeManifestHash,/^[a-f0-9]{64}$/);});
test('ApplicationType selects MicroService when historical AppType is official store classification',()=>{const r=run('{}',{committed:true});assert.equal(r.result.Code,1);assert.equal(metadata(r).ApplicationType,'MicroService');assert.equal(metadata(r).AppType,'官方应用');assert.equal(metadata(r).RuntimeManifestHash,r.manifestHash);});
test('Completed pointer is required before current v3 ZIP export',()=>{for(const PublishState of ['ProjectionPending','RepairRequired','ReleaseVerified','']){const r=attempt('{}',{committed:true,app:{AppType:'MicroService',PublishState}});assert.ok(r.Error||r.result?.Code!==1);}});
test('version must belong to the exact app and committed identifier',()=>{for(const version of [{AppId:'foreign'},{Id:'foreign-version'},{PublishState:'RepairRequired'},{VersionNo:'v2.0.0'},{RuntimeManifestHash:'0'.repeat(64)},{RequestFingerprint:''}]){const r=attempt('{}',{committed:true,app:{AppType:'MicroService'},version});assert.ok(r.Error||r.result?.Code!==1);}});
test('duplicate or missing committed version rows are not accepted',()=>{for(const versions of [[],[{VersionNo:'v1.0.0'},{VersionNo:'v1.0.0'}]]){const r=attempt('{}',{committed:true,app:{AppType:'MicroService'},versions});assert.ok(r.Error||r.result?.Code!==1);}});
test('complete runtime hash must match independently verified asset set',()=>{const r=attempt('{}',{distHash:'0'.repeat(64)});assert.ok(r.Error||r.result?.Code!==1);});
test('current application version drift during byte reads fails closed',()=>{for(const afterApp of [{AppVersion:'v2.0.0'},{CommittedPublishVersionId:'different'},{CommittedRuntimeManifestHash:'0'.repeat(64)},{PublishState:'RepairRequired'}]){const r=attempt('{}',{committed:true,app:{AppType:'MicroService'},afterApp});assert.ok(r.Error||r.result?.Code!==1);}});
test('version fingerprint or row version drift during byte reads fails closed',()=>{for(const afterVersion of [{RequestFingerprint:'f'.repeat(64)},{RowVersion:2}]){const r=attempt('{}',{committed:true,app:{AppType:'MicroService'},afterVersion});assert.ok(r.Error||r.result?.Code!==1);}});

test('app identity or runtime type drift during reads fails closed',()=>{for(const afterApp of [{Id:'other-app'},{AppKey:'other-key'},{ApplicationType:'Web'}]){const r=attempt('{}',{committed:true,app:{AppType:'MicroService'},afterApp});assert.ok(r.Error||r.result?.Code!==1);}});

test('every network asset read uses the existing strict SSRF transport that forbids redirects',()=>{const r=run('{}');assert.ok(r.httpRequests.length>=2);for(const request of r.httpRequests)assert.equal(request.RequireSsrfProtection,true);});
