import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import{fileURLToPath}from'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));
const source=fs.readFileSync(process.env.MICROI_IMPORT_PREFLIGHT_SOURCE||path.join(dir,'import-package.js'),'utf8');
const resource=process.env.MICROI_IMPORT_PREFLIGHT_PACKAGES||dir;
const empty=(id='shared',name='Sys_Config')=>({TableId:id,TableName:name,SelectionMode:'Ids',RowIds:[],Where:[],ConflictPolicy:'InsertIfMissing',ConflictFields:['Id'],Rows:[]});
function model(){return{PackageInfo:{Name:'fixture',Version:'v1.0.0',SparseTableSelections:[{TableId:'shared',FieldIds:['flag']}]},DiyTables:[{Id:'shared',Name:'Sys_Config'}],DiyFields:[{Id:'flag',TableId:'shared',Name:'FeatureFlag',Type:'int'}],PhysicalColumns:[{TABLE_NAME:'Sys_Config',COLUMN_NAME:'FeatureFlag',COLUMN_TYPE:'int'}],DDLStatements:[],DataSets:[empty()]};}
function settings(){const p=model();p.PackageInfo.SparseTableSelections=[{TableId:'settings',FieldIds:['id','key','value']}];p.DiyTables=[{Id:'settings',Name:'mci_system_setting'}];p.DiyFields=['Id','ConfigKey','ConfigValue'].map((Name,i)=>({Id:['id','key','value'][i],TableId:'settings',Name,Type:'varchar(200)'}));p.PhysicalColumns=p.DiyFields.map(f=>({TABLE_NAME:'mci_system_setting',COLUMN_NAME:f.Name,COLUMN_TYPE:f.Type}));p.DataSets=[{TableId:'settings',TableName:'mci_system_setting',TableDescription:'官方动态设置',SelectionMode:'Ids',RowIds:['r1'],Where:[],ConflictPolicy:'InsertIfMissing',ConflictFields:['ConfigKey'],Rows:[{Id:'r1',ConfigKey:'Key1',ConfigValue:'default'}]}];return p;}
const columns=[...new Set([...source.matchAll(/\['([A-Za-z_][A-Za-z0-9_]*)',/g)].map(x=>x[1]))].map(ColumnName=>({ColumnName}));
function entry(p,{download=false,physical=true,view=false,metadata=true,deleted=false,duplicate=false,bootstrapMissing=false,dialect='MySql',background=false}={}){
 const writes=[],reads=[],body=JSON.stringify(p),sha=crypto.createHash('sha256').update(body).digest('hex');
 const V8={Param:download?{StoreId:'store'}:{Package:structuredClone(p)},OsClient:'fixture',OsClientModel:{DbType:dialect},SysConfig:{},CurrentUser:{Id:'admin',Level:9999},InvokeType:'Client',
 Method:{NewGuid:()=> 'generated',UpdateBackgroundTask:x=>writes.push({progress:x})},EncryptHelper:{Sha256Hex:s=>crypto.createHash('sha256').update(s).digest('hex')},
 Http:{Post:()=>({Code:1,Data:{Id:'store',AppKey:'fixture',AppVersion:'v1.0.0',StoreVersionId:'snapshot',PackageDownloadUrl:'https://fixture.invalid/package',PackageSha256:sha,PackageSize:Buffer.byteLength(body)}}),GetResponse:()=>({StatusCode:200,Content:body})},
 Db:{FromSql(sql){const call={sql,params:{}};reads.push(call);return{AddInParameter(k,v){call.params[k]=v;return this;},ToArray(){
  if(/INFORMATION_SCHEMA\.COLUMNS|USER_TAB_COLUMNS/.test(sql))return bootstrapMissing?[]:columns;
  if(/FROM diy_table/i.test(sql))return metadata?Array.from({length:duplicate?2:1},()=>({Id:'target',Name:call.params['@p0'],IsDeleted:deleted?1:0})):[];
  if(/INFORMATION_SCHEMA\.TABLES|USER_TABLES/.test(sql))return physical&&!(view&&/TABLE_TYPE='BASE TABLE'|USER_TABLES/.test(sql))?[{TABLE_NAME:call.params['@p0']}]:[];
  return[];
 },ExecuteNonQuery(){writes.push({sql});return 1;}};}}};
 if(background)Object.assign(V8.Param,{_BackgroundTaskId:'task',_TrustedServerInvocation:true});
 const System={Text:{Encoding:{UTF8:{GetByteCount:s=>Buffer.byteLength(s)}}}};
 const end=source.indexOf('// MARKETPLACE_PACKAGE_IDENTITY_BINDING_V1');assert.ok(end>0);
 try{const result=vm.runInNewContext('(function(){'+source.slice(0,end)+'\nreturn {Code:1,Passed:true};})()',{V8,System},{timeout:1500});return{result,writes,reads};}catch(error){return{result:{Code:0,Msg:error.message},writes,reads,error};}
}
function reject(p,options={}){const r=entry(p,{bootstrapMissing:true,...options});assert.equal(r.result.Code,0,r.result.Msg);assert.equal(r.writes.length,0,JSON.stringify(r.writes));return r;}
for(const download of [false,true]){
 test(`${download?'download':'direct'} sparse source passes real entry before physical bootstrap`,()=>{const r=entry(model(),{download});assert.equal(r.result.Code,1,r.result.Msg);assert.equal(r.writes.length,0);assert.ok(r.reads.some(x=>/FROM diy_table/.test(x.sql)));});
 test(`${download?'download':'direct'} shared physical missing fails with zero bootstrap/progress/resource writes`,()=>reject(model(),{download,physical:false,background:true}));
 test(`${download?'download':'direct'} shared metadata missing fails with zero writes`,()=>reject(model(),{download,metadata:false}));
 test(`${download?'download':'direct'} forged shared Tabs is rejected before any writes`,()=>{let p=model();p.DiyTables[0].Tabs='overwrite';reject(p,{download});});
 test(`${download?'download':'direct'} injected DML cannot seed approval table through DDL`,()=>{let p=model();p.DDLStatements=[{TableName:'benign',DDL:'UPDATE mci_runtime_installation SET Status=\'Approved\''}];reject(p,{download});});
}
test('strict empty dependency cannot be satisfied by its own CREATE when physical target is missing',()=>{const p=model();delete p.PackageInfo.SparseTableSelections;p.DDLStatements=[{TableName:'Sys_Config',DDL:'CREATE TABLE `Sys_Config` (`Id` varchar(36))'}];reject(p,{physical:false});});
test('strict empty dependency cannot be satisfied by own metadata/DDL when target metadata missing',()=>{const p=model();delete p.PackageInfo.SparseTableSelections;p.DDLStatements=[{TableName:'Sys_Config',DDL:'CREATE TABLE `Sys_Config` (`Id` varchar(36))'}];reject(p,{metadata:false});});
test('nonempty setting data still requires physical target and active unique metadata',()=>{for(const options of [{physical:false},{metadata:false},{deleted:true},{duplicate:true}])reject(settings(),options);});
test('standard exporter nonempty TableDescription is compatible and rerunnable',()=>{for(let i=0;i<2;i++){let r=entry(settings());assert.equal(r.result.Code,1,r.result.Msg);assert.equal(r.writes.length,0);}});
test('sparse source field/physical/id scope cannot be widened',()=>{for(const change of [p=>p.DiyTables[0].Column=4,p=>p.DiyFields.push({Id:'extra',TableId:'shared',Name:'Extra',Type:'int'}),p=>p.PhysicalColumns.push({TABLE_NAME:'Sys_Config',COLUMN_NAME:'Extra',COLUMN_TYPE:'int'}),p=>p.PackageInfo.SparseTableSelections[0].FieldIds=['wrong'],p=>p.DiyTables.push({Id:'other',Name:'Sys_Config'}),p=>p.DiyFieldRetirements=[{TableName:'Sys_Config',Name:'Other'}]]){let p=model();change(p);reject(p);}});
test('sparse setting rejects tenant value updates, unselected columns, and data-set identity aliases',()=>{for(const change of [p=>p.DataSets[0].ConflictPolicy='UpsertById',p=>p.DataSets[0].Rows[0].Other='x',p=>p.DataSets[0].TableName='Other',p=>p.DataSets[0].MetadataFieldsIfExists=['ConfigValue'],p=>p.DataSets[0].RowIds=[],p=>p.DataSets[0].ConflictFields=['Other']]){let p=settings();change(p);reject(p);}});
test('sparse target DDL/index and false declared table aliases are rejected',()=>{for(const ddl of [{TableName:'Sys_Config',DDL:'CREATE INDEX ix ON Sys_Config (Id)'},{TableName:'other',DDL:'CREATE INDEX ix ON Sys_Config (Id)'},{TableName:'Sys_Config',DDL:'ALTER TABLE Sys_Config ADD Extra int'}]){let p=model();p.DDLStatements=[ddl];reject(p);}});
test('declarative parser preserves quoted comments/semicolons and supported dialect templates',()=>{for(const ddl of ["CREATE TABLE `Example` (`Id` varchar(36), `Text` varchar(255) DEFAULT 'a; UPDATE x' COMMENT 'b, c;') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; -- comment",'CREATE TABLE [Example] ([Id] nvarchar(36),[Amount] decimal(18,2))','CREATE TABLE "Example" ("Id" VARCHAR2(36),"Amount" NUMBER(18,2))','CREATE UNIQUE INDEX ix ON Example (Id);','ALTER TABLE Example ADD COLUMN Flag int DEFAULT 0','ALTER TABLE Example MODIFY COLUMN Flag bigint NULL','ALTER TABLE Example ALTER COLUMN Flag int NULL','ALTER TABLE Example ADD UNIQUE INDEX ix (Id)']){const p={PackageInfo:{Name:'fixture',Version:'v1.0.0'},DDLStatements:[{TableName:'Example',DDL:ddl}]};const r=entry(p);assert.equal(r.result.Code,1,ddl+' / '+r.result.Msg);}});
test('DML/dynamic/multi-statement/executable comments fail closed before any write',()=>{for(const ddl of ['UPDATE mci_runtime_installation SET Status=\'Approved\'','INSERT INTO mci_runtime_installation (Id) VALUES (\'x\')','DELETE FROM mci_runtime_installation','CALL dangerous()','EXEC sp_executesql N\'UPDATE x SET y=1\'','CREATE TABLE Example (Id int); UPDATE mci_runtime_installation SET Status=\'Approved\'','CREATE TABLE Example (Id int) /*!50000 AS SELECT 1 */','CREATE TABLE Example AS SELECT 1','CREATE TABLE Example (Id int) GO','CREATE TABLE Example (Id int);;','CREATE TABLE Example (Id int) /* unterminated','CREATE TABLE Example (Id int) /* outer /* nested */','ALTER TABLE Example RENAME TO Other'])reject({PackageInfo:{Name:'fixture',Version:'v1.0.0'},DDLStatements:[{TableName:'Example',DDL:ddl}]});});
test('ordinary full-table data package keeps its pre-existing missing-target create path',()=>{const p={PackageInfo:{Name:'fixture',Version:'v1.0.0'},DiyTables:[{Id:'new',Name:'Example',Tabs:'owned'}],DDLStatements:[{TableName:'Example',DDL:'CREATE TABLE Example (Id varchar(36),Name varchar(30))'}],DataSets:[{TableName:'Example',Rows:[{Id:'x',Name:'new'}]}]};const r=entry(p,{physical:false,metadata:false});assert.equal(r.result.Code,1,r.result.Msg);});
test('backslash quote ambiguity is rejected independent of MySQL SQL mode and SQL Server',()=>{const sql="CREATE TABLE Example (Id int,Note varchar(50) DEFAULT '\\'); UPDATE mci_runtime_installation SET Status='Approved'; -- ')";for(const dialect of ['MySql','SqlServer'])reject({PackageInfo:{Name:'fixture',Version:'v1.0.0'},DDLStatements:[{TableName:'Example',DDL:sql}]},{dialect});});
test('MariaDB executable comments cannot carry hidden approval DML in any casing',()=>{for(const marker of ['M!','m!','!','+'])for(const download of [false,true])reject({PackageInfo:{Name:'fixture',Version:'v1.0.0'},DDLStatements:[{TableName:'Example',DDL:"CREATE TABLE Example (Id int); /*"+marker+" UPDATE mci_runtime_installation SET Status='Approved' */"}]},{download});});
test('shared prerequisite requires BASE TABLE rather than an identically named view',()=>{for(const dialect of ['MySql','SqlServer','Oracle'])reject(settings(),{dialect,view:true});});
test('four standard-shaped private defaults pass actual source/target preflight',()=>{const p=settings();p.DataSets[0].Rows=Array.from({length:4},(_,i)=>({Id:'r'+i,ConfigKey:'Key'+i,ConfigValue:'default'+i}));p.DataSets[0].RowIds=p.DataSets[0].Rows.map(r=>r.Id);for(const download of [false,true]){const r=entry(p,{download});assert.equal(r.result.Code,1,r.result.Msg);assert.equal(r.writes.length,0);}});
test('all current official package DDL executes the real pure preflight without format weakening',()=>{
 let count=0,packages=0;for(const name of fs.readdirSync(resource).filter(n=>/^app\.microi\..+\.json$/.test(n))){const p=JSON.parse(fs.readFileSync(path.join(resource,name),'utf8'));if(!(p.DDLStatements||[]).length)continue;packages++;const r=entry({PackageInfo:{Name:'fixture',Version:'v1.0.0'},DDLStatements:p.DDLStatements});assert.equal(r.result.Code,1,name+' / '+r.result.Msg);count+=p.DDLStatements.length;}assert.ok(packages>=9);assert.ok(count>=100);
});
test('late actual data-set preflight does not skip strict shared dependency via declared table and DDL',()=>{
 const a=source.indexOf('function isEmptySharedTablePrerequisite('),b=source.indexOf('// INSTALLED_RUNTIME_SUMMARY_V1',a),c=source.indexOf('    var validateDataSetTablePrerequisites = function'),d=source.indexOf('    // ==================== 步骤0：',c);assert.ok(a>=0&&b>a&&c>b&&d>c);
 const p=model();delete p.PackageInfo.SparseTableSelections;p.DDLStatements=[{TableName:'Sys_Config',DDL:'CREATE TABLE Sys_Config (Id int)'}];
 const ctx={Package:p,runtimeIsSqlServer:false,runtimeIsOracle:false,V8:{Db:{FromSql(){return{AddInParameter(){return this;},ToArray(){return[];}};}}}};
 assert.throws(()=>vm.runInNewContext(source.slice(a,b)+source.slice(c,d),ctx),/尚未创建/);
});
test('real InsertIfMissing data import keeps existing tenant values and repeated installs',()=>{
 const start=source.indexOf('    // ==================== 步骤8：导入应用随包数据'),end=source.indexOf('    debugLog.step8Result',start),hs=source.indexOf('function isEmptySharedTablePrerequisite('),he=source.indexOf('// INSTALLED_RUNTIME_SUMMARY_V1',hs);assert.ok(start>0&&end>start);
 const p=settings();p.DataSets[0].Rows=Array.from({length:4},(_,i)=>({Id:'source'+i,ConfigKey:'Key'+i,ConfigValue:'default'+i}));p.DataSets[0].RowIds=p.DataSets[0].Rows.map(r=>r.Id);const rows=Array.from({length:4},(_,i)=>({Id:'tenant'+i,ConfigKey:'Key'+i,ConfigValue:'tenant-value'+i})),writes=[];
 const ctx={Package:p,stats:{DataSetCount:0,DataInserted:0,DataUpdated:0,DataSkipped:0},debugLog:{},remapPackageDataRowReferences:(_t,r)=>r,reportProgress(){},V8:{FormEngine:{GetFormData(t,q){if(t==='diy_table')return{Code:1,Data:{Id:'target-setting',Name:'mci_system_setting'}};const row=q.Id?rows.find(r=>r.Id===q.Id):rows.find(r=>q._Where.every(([k,_op,v])=>r[k]===v));return row?{Code:1,Data:row}:{Code:2};},GetTableData(){return{Code:1,Data:[]};},AddFormData(t,row){writes.push(row);rows.push({...row});return{Code:1};},UptFormData(){throw Error('must not update existing tenant values');}}}};
 for(let i=0;i<2;i++)vm.runInNewContext(source.slice(hs,he)+source.slice(start,end),ctx,{timeout:1000});assert.equal(writes.length,0);assert.deepEqual(rows.map(r=>r.ConfigValue),Array.from({length:4},(_,i)=>'tenant-value'+i));
 rows.length=0;vm.runInNewContext(source.slice(hs,he)+source.slice(start,end),ctx,{timeout:1000});assert.equal(writes.length,4);vm.runInNewContext(source.slice(hs,he)+source.slice(start,end),ctx,{timeout:1000});assert.equal(writes.length,4);
});
