import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {readOfficialApiSource,officialApiSourceEntries} from './official-api-source.mjs';
const directory=import.meta.dirname;
const digest=s=>createHash('sha256').update(s).digest('hex');
const json=async p=>JSON.parse(await fs.readFile(p,'utf8'));
async function fixture(run){const root=await fs.mkdtemp(path.join(os.tmpdir(),'microi-official-source-'));try{for(const item of await fs.readdir(directory,{withFileTypes:true}))if(item.isFile()&&item.name.endsWith('.mjs')&&!item.name.endsWith('.test.mjs'))await fs.copyFile(path.join(directory,item.name),path.join(root,item.name));for(const name of ['official-api-source-contract.json','app.microi.saas-engine.json','app.microi.sso.json'])await fs.copyFile(path.join(directory,name),path.join(root,name));await fs.cp(path.join(directory,'OfficialApiSources'),path.join(root,'OfficialApiSources'),{recursive:true});for(const e of officialApiSourceEntries)if(!e.File.includes('/'))await fs.copyFile(path.join(directory,e.File),path.join(root,e.File));await run(root);}finally{await fs.rm(root,{recursive:true,force:true});}}
function execute(root,script){return spawnSync(process.execPath,['--max-old-space-size=256',path.join(root,script)],{cwd:root,encoding:'utf8',timeout:15000});}
function readChild(root,key){return spawnSync(process.execPath,['--input-type=module','-e',`import {readOfficialApiSource} from './official-api-source.mjs';readOfficialApiSource(${JSON.stringify(key)});`],{cwd:root,encoding:'utf8',timeout:5000});}
test('42个声明资源与正式包完整正文一致，Hook仅带安全默认模板',async()=>{assert.equal(officialApiSourceEntries.length,42);for(const e of officialApiSourceEntries){const pkg=await json(path.join(directory,e.Package)),source=readOfficialApiSource(e.Key),expected=e.Kind==='ApiEngine'?pkg.SysApiEngines.find(x=>x.ApiEngineKey===e.Key)?.ApiV8Code:pkg.DiyTables.find(x=>x.Name==='sys_microistore')?.SubmitBeforeServerV8;assert.equal(source,expected,e.Key);assert.equal(digest(source),e.Sha256);}});
for(const [script,pkg]of [['configure-platform-auth-resource.mjs','app.microi.saas-engine.json'],['configure-sso-resource.mjs','app.microi.sso.json']])test('生成器'+script+'保持全部接口稳定Id、版本、权限及源码，不改写发行源',async()=>fixture(async root=>{const before=await json(path.join(root,pkg)),sourceHashes=Object.fromEntries(await Promise.all(officialApiSourceEntries.map(async e=>[e.File,digest(await fs.readFile(path.join(root,e.File)))])));const result=execute(root,script);assert.equal(result.status,0,result.stderr);const after=await json(path.join(root,pkg));assert.deepEqual(after.SysApiEngines,before.SysApiEngines);assert.deepEqual(after.ResourcePolicies,before.ResourcePolicies);for(const e of officialApiSourceEntries)assert.equal(digest(await fs.readFile(path.join(root,e.File))),sourceHashes[e.File]);const again=execute(root,script);assert.equal(again.status,0,again.stderr);assert.deepEqual((await json(path.join(root,pkg))).SysApiEngines,after.SysApiEngines);}));
test('不存在的镜像和未声明Key不能成为备用源码',async()=>fixture(async root=>{assert.notEqual(readChild(root,'tenant_mirror_unknown').status,0);await fs.unlink(path.join(root,'OfficialApiSources/send-sms-reg.js'));assert.notEqual(readChild(root,'send-sms-reg').status,0);const before=await fs.readFile(path.join(root,'app.microi.saas-engine.json'));const r=execute(root,'configure-platform-auth-resource.mjs');assert.notEqual(r.status,0);assert.deepEqual(await fs.readFile(path.join(root,'app.microi.saas-engine.json')),before);}));
test('原正文摘要漂移在生成包之前拒绝',async()=>fixture(async root=>{await fs.appendFile(path.join(root,'OfficialApiSources/send-sms-reg.js'),'\nV8.Sms.Send({});');const r=readChild(root,'send-sms-reg');assert.notEqual(r.status,0);assert.match(r.stderr,/正文或版本/);}));
for(const [label,mutate]of [['跨目录',c=>c.Entries[0].File='../outside.js'],['重复Key',c=>c.Entries.push(c.Entries[0])],['错官方租户',c=>c.OfficialOsClient='other']])test(label+'发行契约拒绝',async()=>fixture(async root=>{const p=path.join(root,'official-api-source-contract.json'),c=await json(p);mutate(c);await fs.writeFile(p,JSON.stringify(c));assert.notEqual(readChild(root,'platform_auth_sms_login').status,0);}));
test('合法摘要也不能将租户自定义逻辑放入CreateIfMissing默认Hook',async()=>fixture(async root=>{const p=path.join(root,'official-api-source-contract.json'),c=await json(p),entry=c.Entries.find(e=>e.Key==='platform_auth_login_hook'),file=path.join(root,entry.File);const source=(await fs.readFile(file,'utf8')).replace('return { Code : 1 };','V8.FormEngine.DelFormData("business", {});\nreturn { Code : 1 };');entry.Sha256=digest(source);await fs.writeFile(file,source);await fs.writeFile(p,JSON.stringify(c));const r=readChild(root,entry.Key);assert.notEqual(r.status,0);assert.match(r.stderr,/不能携带/);}));
