import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
import test from 'node:test';
import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('./official-resource-api.js',import.meta.url),'utf8'),cut=source.indexOf('var action = text(PARAM.Action)'),lib=source.slice(0,cut);
const names=['app.microi.form-engine.json','app.microi.module-engine.json','app.microi.saas-engine.json','app.microi.sso.json','app.microi.store.json','app.microi.sys_user.json','app.microi.sys-config.json','app.microi.message-notification.json','app.microi.ai-engine.json'],sha=s=>crypto.createHash('sha256').update(s).digest('hex'),h='a'.repeat(64),sys={Name:'app.microi.sys-log.json',ExpectedSha256:h};
function harness(params,packages={}){let locks=0,history=0;const sandbox={V8:{Param:params,Db:{FromSql(){return{ToArray(){locks++;return[]}}}}},console};const code=lib+`\nreadRawResource=function(name){return packages[name]||{Code:0,Msg:'missing'};};\nvalidatePublishResource=function(name,content){return {PackageModel:JSON.parse(content)};};\nensurePackageChangeLog=function(){history++;};\nreturn {parse:parseReconcileItems,prepare:preparePublishedApiEngineProjection};`;sandbox.packages=packages;sandbox.history=0;const api=vm.runInNewContext('(function(){'+code+'})()',sandbox);return{...api,locks:()=>locks,history:()=>sandbox.history};}
const plain=v=>JSON.parse(JSON.stringify(v)),all=()=>names.map(Name=>({Name,ExpectedSha256:h})),pkg=(id='app.microi.sys-log',key='mci-cdn-manager',policy='Managed')=>({PackageInfo:{AppId:id},SysApiEngines:[{ApiEngineKey:key,ApiV8Code:'return {Code:1};'}],ResourcePolicies:{ApiEngines:{[key]:{UpgradePolicy:policy}}}}),resource=p=>({Code:1,Data:{Content:JSON.stringify(p),Sha256:h,RowId:'store-id'}});
test('original default nine exact order and selection remain intact',()=>{assert.deepEqual(plain(harness({Resources:all().reverse()}).parse()).map(r=>r.Name),names);for(const list of [all().slice(1),[...all(),sys]])assert.throws(()=>harness({Resources:list}).parse());});
test('SystemLog requires sole fixed sys-log filename and exact 64hex digest',()=>{assert.deepEqual(plain(harness({ProjectionScope:'SystemLog',Resources:[sys]}).parse()),[sys]);for(const item of [{...sys,Name:'app.microi.store.json'},{...sys,Name:'../app.microi.sys-log.json'},{...sys,ExpectedSha256:'x'}, {...sys,ExpectedSha256:''}])assert.throws(()=>harness({ProjectionScope:'SystemLog',Resources:[item]}).parse());for(const items of [[],[sys,sys],[sys,...all()]])assert.throws(()=>harness({ProjectionScope:'SystemLog',Resources:items}).parse());});
test('missing explicit scope and unknown scope are rejected without fallback',()=>{assert.throws(()=>harness({Resources:[sys]}).parse());for(const s of ['All','systemlog','SystemLog/..','arbitrary'])assert.throws(()=>harness({ProjectionScope:s,Resources:all()}).parse(),/作用范围/);});
test('actual full package SHA is required before any projection/history',()=>{const r=resource(pkg());r.Data.Sha256='b'.repeat(64);const a=harness({ProjectionScope:'SystemLog',Resources:[sys]},{[sys.Name]:r});assert.throws(()=>a.prepare(),/发生变化/);assert.equal(a.history(),0);assert.equal(a.locks(),2);});
test('SystemLog file and PackageInfo AppId are inseparable',()=>{for(const id of ['app.microi.store','mci-cms','',undefined]){const a=harness({ProjectionScope:'SystemLog',Resources:[sys]},{[sys.Name]:resource(pkg(id))});if(id===undefined){const p=pkg();delete p.PackageInfo.AppId;assert.throws(()=>harness({ProjectionScope:'SystemLog',Resources:[sys]},{[sys.Name]:resource(p)}).prepare(),/AppId/);}else assert.throws(()=>a.prepare(),/AppId/);assert.equal(a.history(),0);}});
test('valid SystemLog has exact own projection and preserves Managed/CIM behavior',()=>{for(const policy of ['Managed','CreateIfMissing']){const a=harness({ProjectionScope:'SystemLog',Resources:[sys]},{[sys.Name]:resource(pkg('app.microi.sys-log','mci-cdn-manager',policy))});const p=plain(a.prepare());assert.equal(p.Items.length,1);assert.equal(p.Projections.length,1);assert.equal(p.Projections[0].Policy,policy);assert.equal(p.PackageHashes[sys.Name],h);}});
test('missing owner policy and duplicate resource key still fail closed',()=>{const p=pkg();delete p.ResourcePolicies.ApiEngines['mci-cdn-manager'];assert.throws(()=>harness({ProjectionScope:'SystemLog',Resources:[sys]},{[sys.Name]:resource(p)}).prepare(),/策略/);const dup=pkg();dup.SysApiEngines.push({...dup.SysApiEngines[0]});assert.throws(()=>harness({ProjectionScope:'SystemLog',Resources:[sys]},{[sys.Name]:resource(dup)}).prepare(),/重复/);});
test('all original nine complete projections retain order and cross-owner key collision rejection',()=>{const packages={};names.forEach((n,i)=>packages[n]=resource(pkg(n.slice(0,-5),'owned-'+i)));const p=plain(harness({Resources:all()},packages).prepare());assert.equal(p.Items.length,9);assert.equal(p.Projections.length,9);assert.deepEqual(p.Items.map(i=>i.Name),names);packages[names[1]]=resource(pkg('app.microi.module-engine','owned-0'));assert.throws(()=>harness({Resources:all()},packages).prepare(),/跨包重复/);});
test('trusted authorization, fixed DB locks and native full readback gates remain present',()=>{for(const s of ['V8.Method.AuthorizeOfficialResourcePublish()','ORDER BY Id FOR UPDATE','后回读内容哈希不一致','function reconcilePublishedApiEngines()'])assert.ok(source.includes(s));});
