import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const root=new URL('../../../Microi-V8-Engine/宁波鸿地-开发环境 (api-dev.chongstech.com)/hongdi-dev.default.default/',import.meta.url);
const quota=fs.readFileSync(new URL('接口引擎/原材料采购/采购来源额度校验(junchi_ycl_purchase_source_quota_validate).js',root),'utf8');
test('主单编辑和审核继承已持久化的精确支数快照，V1快照仍无标记',()=>{const flow=fs.readFileSync(new URL('接口引擎/AI生成/原材料采购订单主子表业务(junchi_ycl_purchase_order_flow).js',root),'utf8');const helper=flow.slice(0,flow.indexOf('function validateSourceQuota'));const c={V8:{},DateNow:()=>''};vm.runInNewContext(helper,c);for(const exact of [true,false]){const snapshot={items:[{lengthM:12,meters:7.2,weightKg:72,referencePieceQty:0.6,...(exact?{pieceQuantityMode:'Exact'}:{})}]};const items=c.buildCandidateLengthItems(JSON.stringify(snapshot),'HBeam',12000,7.2,72,0.6);assert.equal(items[0].pieceQuantityMode,exact?'Exact':'');assert.equal(items[0].referencePieceQty,0.6);}});
function run(qty,exact,override={}){const meters=qty*12;const source={Id:'q',InventoryId:'inv',StockType:'HBeam',RequisitionWeight:1000,Mishu:100,UnitWeightPerMeterSnapshot:10,ExecutionStatus:'Active'};const params={RequisitionId:'q',CandidateWeightKg:meters*10,CandidateMeters:meters,CandidatePieces:999,CandidateLengthItems:[{lengthM:12,meters,weightKg:meters*10,referencePieceQty:999,...(exact?{pieceQuantityMode:'Exact'}:{})}],RequireActiveSource:true,...override};const db={FromSql:sql=>({AddInParameter(){return this},ToArray:()=>sql.includes('FROM qinggouqingdan')?[source]:[]})};return vm.runInNewContext('(function(V8){'+quota+'})')({Param:params,Db:db});}
test('V2额度按米数及支长重算0.5/0.6/3.9支，不信任客户端999支',()=>{for(const qty of [0.5,0.6,3.9]){const r=run(qty,true);assert.equal(r.Code,1);assert.equal(r.Data.Allowed,true);assert.equal(r.Data.CandidatePieces,qty);assert.equal(r.Data.CandidateLengthItems[0].referencePieceQty,qty);assert.equal(r.Data.CandidateLengthItems[0].pieceQuantityMode,'Exact');assert.equal(r.Data.CandidateWeightKg,qty*120)}});
test('未标记V1保留原0.7取整规则',()=>{for(const [qty,expected] of [[0.5,0],[0.6,0],[3.9,4],[3,3]]){const r=run(qty,false);assert.equal(r.Data.CandidatePieces,expected)}});
test('小数支不获得整支豁免，超110%仍拒绝，米数重量篡改拒绝',()=>{assert.equal(run(9.5,true).Data.Allowed,false);assert.equal(run(0.6,true,{CandidateWeightKg:999}).Code,0);assert.equal(run(0.6,true,{CandidateMeters:999}).Code,0)});
test('普通编辑仅对已持久化Exact快照保留小数，旧单和整卷规则不变',()=>{const event=fs.readFileSync(new URL('表单引擎/diy_ycl_purchase_order/SubmitBeforeServerV8.js',root),'utf8');const start=event.indexOf('if (profileStock) {\n    if (candidateLengthItems.length > 1)'),end=event.indexOf("} else if (stockType == 'CoilPlate')",start);assert.ok(start>0&&end>start);const block=event.slice(start,end)+'}';const rounded=(m,l)=>{const n=m/l;return Math.floor(n)+(n-Math.floor(n)>=0.7?1:0)};for(const exact of [true,false])for(const changed of [true,false]){const c={profileStock:true,candidateLengthItems:[{}],lengthChanged:false,quantityChanged:changed,metersChanged:false,length:12000,meters:7.2,purchaseQty:0.6,exactPieceMode:exact,weightChanged:false,unitWeightPerMeter:10,singleWeight:0,totalWeight:72,round4:n=>Math.round(n*10000)/10000,numberValue:Number,roundedProfilePieces:rounded};vm.runInNewContext(block,c);assert.equal(c.purchaseQty,exact?0.6:1);assert.equal(c.meters,exact?7.2:changed?12:7.2);}assert.match(event,/normalizeLengthItems\(oldForm.LengthCompositionSnapshot\)/);assert.match(event,/profileStock && !exactPieceMode/);assert.match(event,/resolveInquiryRemark/)});
