<script setup>
import { computed,onMounted,onUnmounted,reactive,ref } from 'vue'
import QRCode from 'qrcode'
import { configureV8,getContext,subscribeContext } from './microi.js'
import { promotionTheme,tenantCsv,trialLabels,usageLabels,summarizeUsage } from './saas-promotion-model.js'
import './saas-promotion.css'
const context=ref(getContext()), section=ref('Overview'), loading=ref(true),busy=ref(false),error=ref(''),notice=ref('')
const actor=ref({}),users=ref([]),roles=ref([]),dashboard=ref(null),tenants=ref([]),total=ref(0),usage=ref({}),links=ref([]),tasks=ref([]),detail=ref(null),detailUsage=ref(null)
const filters=reactive({Keyword:'',State:'',ReferralUserId:'',FromDate:'',ToDate:'',Page:1,PageSize:20})
const settings=reactive({Enabled:false,TrialDays:14,DailyLimit:20,LinkLimit:50,WebBase:'',ManagerRoleIds:[]})
const linkForm=reactive({Title:'',ReferralUserId:'',TrialDays:14,MaxTenants:50,ValidDays:30,Remark:''}),showLinkForm=ref(false),share=ref(''),qr=ref('')
const follow=reactive({Stage:'Trial',Notes:'',NextFollowup:'',ReferralUserId:''})
const fleetUsage=ref([]),fleetProgress=ref(0),fleetCollecting=ref(false)
const fleet=computed(()=>summarizeUsage(fleetUsage.value,dashboard.value?.UsageTargets||[]))
const fleetCards=[['Forms','表单总数'],['ApiEngines','接口引擎'],['Menus','菜单总数'],['Users','用户总数'],['ActiveUsers7Days','近7天登录用户'],['ActiveUsers30Days','近30天登录用户']]
const navigation=computed(()=>[{key:'Overview',icon:'◫',label:'推广总览'},{key:'Tenants',icon:'▤',label:'租户台账'},{key:'Trials',icon:'◷',label:'试用跟进'},{key:'Team',icon:'♧',label:'团队统计'},{key:'Links',icon:'↗',label:'推广链接'},...(actor.value.CanConfigure?[{key:'Settings',icon:'⚙',label:'开通配置'}]:[])])
const cards=[['Total','推广租户'],['Trial','试用中'],['Expiring','3天内到期'],['Converted','已转化'],['New30Days','30天新增'],['FollowupDue','待跟进']]
const selectedTitle=computed(()=>navigation.value.find(n=>n.key===section.value)?.label||'推广中心')
const style=computed(()=>promotionTheme(context.value))
const conversion=computed(()=>dashboard.value?.Counts?.Total?((dashboard.value.Counts.Converted/dashboard.value.Counts.Total)*100).toFixed(1)+'%':'—')
const maxTrend=computed(()=>Math.max(1,...(dashboard.value?.NewTenantTrend||[]).map(v=>v.Tenants)))
let alive=true,visible=true,sequence=0,interval
const unsubscribe=subscribeContext(c=>{context.value=c})
// 真实跨库聚合及冷缓存授权可比普通 CRUD 慢；界面保持可见进度，并用请求序号丢弃过期结果。
async function api(Action,data={}) { const r=await configureV8().ApiEngine.RunDirect('platform-saas-promotion',{Action,...data},{timeout:120000,checkCode:false,silentError:true});if(Number(r?.Code)!==1)throw new Error(r?.Msg||'推广数据读取失败。');return r.Data }
function parseRoles(value){try{const v=JSON.parse(value||'[]');return Array.isArray(v)?v:[]}catch{return []}}
async function bootstrap(){loading.value=true;error.value='';try{const data=await api('Bootstrap');actor.value=data.Actor;users.value=data.Users||[];roles.value=data.Roles||[];linkForm.ReferralUserId=data.Actor.UserId;
  if(data.Settings){const s=data.Settings;Object.assign(settings,{Enabled:Number(s.SaasPublicTrialEnabled)===1,TrialDays:Number(s.SaasPublicTrialDays)||14,DailyLimit:Number(s.SaasPublicTrialDailyLimit)||20,LinkLimit:Number(s.SaasPublicTrialLinkLimit)||50,WebBase:s.SaasPublicTrialWebBase||'',ManagerRoleIds:parseRoles(s.SaasPromotionManagerRoleIds)})}
  linkForm.TrialDays=settings.TrialDays;linkForm.MaxTenants=settings.LinkLimit;await load()
}catch(e){error.value=e?.message||e?.Msg||'请求失败，请稍后重试。'}finally{loading.value=false}}
async function load(refresh=false){const ticket=++sequence;busy.value=true;error.value='';try{
  if(['Overview','Team'].includes(section.value)){const data=await api('Dashboard');if(alive&&ticket===sequence){dashboard.value=data;await collectFleetUsage(data.UsageTargets||[],refresh,ticket)}}
  else if(['Tenants','Trials'].includes(section.value)){const data=await api(section.value,{...filters});if(!alive||ticket!==sequence)return;tenants.value=data.Items||[];total.value=data.Total;usage.value={};await loadUsage(tenants.value,refresh,ticket)}
  else if(section.value==='Links'){const [l,t]=await Promise.all([api('Links'),api('Tasks')]);if(alive&&ticket===sequence){links.value=l.Items||[];tasks.value=t.Items||[]}}
}catch(e){if(alive&&ticket===sequence)error.value=e?.message||e?.Msg||'请求失败，请稍后重试。'}finally{if(alive&&ticket===sequence)busy.value=false}}
async function loadUsage(items,refresh,ticket){if(!items.length)return;try{const data=await api('Usage',{TenantIds:items.map(t=>t.Id),Refresh:refresh});if(alive&&ticket===sequence)usage.value=Object.fromEntries((data.Items||[]).map(v=>[v.Id,v]))}catch(e){if(alive&&ticket===sequence)notice.value='台账已读取；用量暂不可读：'+(e?.message||e?.Msg||'请求失败。')}}
// 每批仍由服务器重新核验推荐归属。分批读取允许页面立即呈现总览，并在切换或隐藏时停止下一批。
async function collectFleetUsage(targets,refresh,ticket){fleetUsage.value=[];fleetProgress.value=0;fleetCollecting.value=true;try{
  for(let i=0;i<targets.length;i+=20){if(!alive||ticket!==sequence||!visible||document.hidden)return;
    const data=await api('Usage',{TenantIds:targets.slice(i,i+20).map(t=>t.Id),Refresh:refresh});
    if(!alive||ticket!==sequence)return;fleetUsage.value.push(...(data.Items||[]));fleetProgress.value=Math.min(i+20,targets.length)
  }
}catch(e){if(alive&&ticket===sequence)notice.value='用量汇总尚未全部完成：'+(e?.message||e?.Msg||'稍后刷新可重新采集。')}
finally{if(ticket===sequence)fleetCollecting.value=false}}
function choose(key){section.value=key;filters.Page=1;detail.value=null;share.value='';notice.value='';fleetCollecting.value=false;load()}
async function search(){filters.Page=1;await load()}
async function page(delta){filters.Page+=delta;await load()}
async function openTenant(item){busy.value=true;error.value='';try{detail.value=await api('TenantDetail',{Id:item.Id});detailUsage.value=usage.value[item.Id]||null;Object.assign(follow,{Stage:detail.value.PromotionStage==='Converted'?'Converted':'Trial',Notes:detail.value.PromotionNotes||'',NextFollowup:(detail.value.PromotionNextFollowup||'').replace(' ','T'),ReferralUserId:detail.value.ReferralUserId||''});const data=await api('Usage',{TenantIds:[item.Id]});detailUsage.value=data.Items?.[0]||null}catch(e){error.value=e?.message||e?.Msg||'请求失败，请稍后重试。'}finally{busy.value=false}}
async function action(callback){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await callback()}catch(e){error.value=e?.message||e?.Msg||'请求失败，请稍后重试。'}finally{busy.value=false}}
async function saveFollow(){await action(async()=>{await api('UpdateFollowup',{Id:detail.value.Id,Stage:follow.Stage,Notes:follow.Notes,NextFollowup:follow.NextFollowup?follow.NextFollowup.replace('T',' ').slice(0,19).padEnd(19,':00'):''});notice.value='跟进记录已保存。';detail.value=null;await load()})}
async function assign(){await action(async()=>{await api('Assign',{Id:detail.value.Id,ReferralUserId:follow.ReferralUserId});notice.value='推荐人已分配。';detail.value=null;await load()})}
async function createLink(){await action(async()=>{await api('CreateLink',{...linkForm});showLinkForm.value=false;linkForm.Title='';await load();notice.value='推广链接已创建，可复制或下载二维码。'})}
async function showShare(link){await action(async()=>{const data=await api('ShareLink',{Id:link.Id});share.value=data.Url;qr.value=await QRCode.toDataURL(data.Url,{width:240,margin:2,errorCorrectionLevel:'L'})})}
async function toggle(link){await action(async()=>{await api('UpdateLink',{Id:link.Id,Enabled:Number(link.IsEnable)!==1});share.value='';await load();notice.value='已更新链接状态。之前分享的地址已失效，请重新复制。'})}
async function resumeTask(task){await action(async()=>{await api('ResumeTask',{Id:task.Id});await load();notice.value='原申请已恢复，将继续使用原请求和数据库检查点。'})}
async function copy(){try{await navigator.clipboard.writeText(share.value);notice.value='推广地址已复制。'}catch{notice.value='请选中分享地址手动复制。'}}
async function saveSettings(){await action(async()=>{await api('SaveSettings',{...settings});notice.value='开通配置已保存。'})}
async function exportRows(){await action(async()=>{const data=await api('Export',{...filters});const blob=new Blob([tenantCsv(data.Items||[])],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='SaaS推广台账.csv';a.click();URL.revokeObjectURL(url);notice.value='已导出当前授权范围内的筛选结果。'})}
function metric(id,key){const data=usage.value[id];return data&&['Ready','Partial','Stale'].includes(data.Status)&&data[key]!=null?data[key]:'—'}
function lifecycle(event){visible=event.detail?.appState!=='afterhidden';if(visible&&!loading.value)load()}
function visibility(){visible=!document.hidden}
onMounted(()=>{bootstrap();document.addEventListener('visibilitychange',visibility);window.addEventListener('appstate-change',lifecycle);interval=setInterval(()=>{if(visible&&!document.hidden&&!busy.value&&!detail.value&&!showLinkForm.value&&section.value!=='Settings')load()},60000)})
onUnmounted(()=>{alive=false;sequence++;clearInterval(interval);unsubscribe();document.removeEventListener('visibilitychange',visibility);window.removeEventListener('appstate-change',lifecycle)})
</script>
<template>
<main class="saas-promotion sp-shell" data-mci-ui-root="microi-platform-service" :data-theme="context.themeMode" :style="style">
  <aside class="sp-sidebar"><div class="sp-brand"><span class="sp-brand-icon">↗</span><div><small>SAAS GROWTH</small><strong>推广中心</strong></div></div><p class="sp-scope">{{actor.CanViewAll?'全部推广 · 管理视图':'我的推广 · 业务员视图'}}</p>
    <nav aria-label="推广中心功能"><button v-for="n in navigation" :key="n.key" :class="{selected:section===n.key}" :aria-current="section===n.key?'page':undefined" :aria-label="n.label" @click="choose(n.key)"><span>{{n.icon}}</span>{{n.label}}</button></nav>
    <div class="sp-sidebar-note"><strong>{{actor.UserName||context.currentUser?.Name||'当前用户'}}</strong><p>每一次推广都有归属<br>每一套租户都有真实记录</p></div>
  </aside>
  <section class="sp-content"><header class="sp-header"><div><small>系统引擎 / SaaS 推广</small><h1>{{selectedTitle}}</h1><p>{{section==='Overview'?'看见推广成果，及时跟进每一位客户。':section==='Links'?'创建专属开通链接，让客户自主开始试用。':section==='Settings'?'设置公开开通范围、试用期限和管理角色。':'所有数据均来自当前授权范围内的真实租户。'}}</p></div><button class="sp-button" :disabled="busy||loading" @click="load(true)">↻ 刷新数据</button></header>
  <p v-if="error" class="sp-alert" role="alert">{{error}} <button :disabled="busy" @click="bootstrap">重试</button></p><p v-if="notice" class="sp-notice" role="status">{{notice}}</p>
  <section v-if="loading" class="sp-skeleton" aria-busy="true" aria-label="正在读取推广数据"><i v-for="i in 6" :key="i"></i><b></b></section>
  <template v-else>
    <template v-if="section==='Overview'"><div class="sp-cards"><article v-for="[key,label] in cards" :key="key"><span>{{label}}</span><strong>{{dashboard?.Counts?.[key]??'—'}}<small>套</small></strong><i :class="key">{{key==='Converted'?'转化率 '+conversion:key==='Expiring'?'按 UTC 试用期限计算':key==='FollowupDue'?'到期与跟进时间提醒':'当前授权范围'}}</i></article></div>
    <article class="sp-panel"><header><h2>全部授权租户的真实用量</h2><small>{{fleetCollecting?'采集中':'本次采集'}} {{fleetProgress}} / {{dashboard?.UsageTargets?.length||0}} 套 · 可读 {{fleet.Readable}} 套</small></header><div class="sp-cards"><article v-for="[key,label] in fleetCards" :key="key"><span>{{label}}</span><strong>{{fleet.Metrics[key]?.Value??'—'}}</strong><i>{{fleet.Metrics[key]?.Covered||0}} / {{fleet.Total}} 套可读</i></article></div><p class="sp-caption">只汇总已读取的真实数值；不可读租户不按0计入。统计缓存60秒，页面可见时自动刷新。{{fleet.OldestCollectedAt?'最早采集：'+fleet.OldestCollectedAt.slice(0,19).replace('T',' ')+' UTC':''}}</p></article>
    <div class="sp-two"><article class="sp-panel"><header><h2>近30天新增租户</h2><small>按租户创建时间</small></header><div v-if="dashboard?.NewTenantTrend?.length" class="sp-trend"><div v-for="day in dashboard.NewTenantTrend" :key="day.Day" :title="`${day.Day}：${day.Tenants}套`"><b>{{day.Tenants}}</b><i :style="{height:Math.max(4,day.Tenants/maxTrend*112)+'px'}"></i><small>{{day.Day.slice(5)}}</small></div></div><p v-else class="sp-empty">近30天没有新增推广租户。</p></article>
    <article class="sp-panel"><header><h2>推广质量</h2><small>试用台账口径</small></header><div class="sp-quality"><strong>{{conversion}}</strong><span>已标记转化 / 推广总数</span></div><div class="sp-stats-line"><span>试用已到期</span><b>{{dashboard?.Counts?.Expired??'—'}} 套</b></div><div class="sp-stats-line"><span>历史未分配推荐人</span><b>{{dashboard?.Counts?.Unassigned??'—'}} 套</b></div><div class="sp-stats-line"><span>未登记试用期限</span><b>{{dashboard?.Counts?.Unclassified??'—'}} 套</b></div></article></div>
    <article class="sp-panel"><header><h2>优先跟进</h2><button class="sp-link" @click="choose('Trials')">查看试用台账 →</button></header><div v-if="dashboard?.Attention?.length" class="sp-attention"><button v-for="t in dashboard.Attention" :key="t.Id" @click="openTenant(t)"><div><strong>{{t.ClientName||t.OsClient}}</strong><small>{{t.ReferralUserName}} · {{t.PromotionContact||'未登记联系人'}}</small></div><span class="sp-tag" :data-state="t.TrialState">{{trialLabels[t.TrialState]}}</span><small>{{t.TrialEndTime||t.PromotionNextFollowup||'—'}} UTC</small><b>查看 →</b></button></div><p v-else class="sp-empty">目前没有到期或逾期跟进事项。</p></article>
    <article class="sp-panel"><header><h2>最近开通</h2><button class="sp-link" @click="choose('Tenants')">全部租户 →</button></header><div class="sp-attention"><button v-for="t in dashboard?.Recent||[]" :key="t.Id" @click="openTenant(t)"><div><strong>{{t.ClientName||t.OsClient}}</strong><small>{{t.OsClient}}</small></div><span>{{t.ReferralUserName}}</span><small>{{t.CreateTime}}</small><b>查看 →</b></button></div><p v-if="!dashboard?.Recent?.length" class="sp-empty">尚无推广租户。创建专属链接，开始第一次推广。</p></article></template>
    <template v-if="['Tenants','Trials'].includes(section)"><form class="sp-filters" @submit.prevent="search"><label>搜索<input v-model="filters.Keyword" placeholder="系统、租户、联系人或推荐人" /></label><label>状态<select v-model="filters.State"><option value="">全部状态</option><option v-for="(label,key) in trialLabels" :key="key" :value="key">{{label}}</option></select></label><label v-if="actor.CanViewAll">推荐人<select v-model="filters.ReferralUserId"><option value="">全部推荐人</option><option v-for="u in users" :key="u.Id" :value="u.Id">{{u.Name||u.Account}}</option></select></label><label>创建开始<input v-model="filters.FromDate" type="date" /></label><label>创建结束<input v-model="filters.ToDate" type="date" /></label><button class="sp-button primary" :disabled="busy">筛选</button><button type="button" class="sp-button" :disabled="busy" @click="exportRows">导出 CSV</button></form>
    <article class="sp-panel"><header><h2>{{section==='Trials'?'试用租户':'推广租户'}} <small>{{total}} 套</small></h2><small>用量缓存60秒 · 刷新间隔至少15秒</small></header><div class="sp-table-scroll"><table><thead><tr><th>租户 / 推荐人</th><th>试用状态</th><th>表单</th><th>接口</th><th>菜单</th><th>用户</th><th>近7天登录用户</th><th>统计时间</th><th>操作</th></tr></thead><tbody><tr v-for="t in tenants" :key="t.Id"><td><strong>{{t.ClientName||t.OsClient}}</strong><small>{{t.OsClient}} · {{t.ReferralUserName}}</small></td><td><span class="sp-tag" :data-state="t.TrialState">{{trialLabels[t.TrialState]}}</span><small>{{t.TrialEndTime? t.TrialEndTime+' UTC':'未登记试用期限'}}</small></td><td>{{metric(t.Id,'Forms')}}</td><td>{{metric(t.Id,'ApiEngines')}}</td><td>{{metric(t.Id,'Menus')}}</td><td>{{metric(t.Id,'Users')}}</td><td>{{metric(t.Id,'ActiveUsers7Days')}}</td><td><span :class="['sp-collection',usage[t.Id]?.Status]">{{({Ready:'正常',Partial:'部分可读',Stale:'上次统计',Unavailable:'不可用',Collecting:'采集中',Unsupported:'暂不支持'})[usage[t.Id]?.Status]||'待采集'}}</span><small>{{usage[t.Id]?.CollectedAt?.slice(0,19).replace('T',' ')||'—'}}</small></td><td><button class="sp-link" @click="openTenant(t)">详情 / 跟进</button></td></tr></tbody></table></div><p v-if="!tenants.length" class="sp-empty">没有符合条件的租户。</p><div class="sp-pagination"><span>共 {{total}} 套 · 第 {{filters.Page}} 页</span><button :disabled="busy||filters.Page<=1" @click="page(-1)">上一页</button><button :disabled="busy||filters.Page*20>=total" @click="page(1)">下一页</button></div></article></template>
    <template v-if="section==='Team'"><article class="sp-panel"><header><h2>{{actor.CanViewAll?'推广团队表现':'我的推广表现'}}</h2><small>用量采集 {{fleetProgress}} / {{fleet.Total}} 套</small></header><div class="sp-table-scroll"><table><thead><tr><th>成员</th><th>推广总数</th><th>试用中</th><th>即将到期</th><th>已到期</th><th>已转化</th><th>近30天新增</th><th>转化率</th><th>表单</th><th>接口</th><th>用户</th><th>近7天登录用户</th><th>可读租户</th></tr></thead><tbody><tr v-for="member in dashboard?.Team||[]" :key="member.Id"><td><strong>{{member.Name}}</strong></td><td>{{member.Total}}</td><td>{{member.Trial}}</td><td>{{member.Expiring}}</td><td>{{member.Expired}}</td><td>{{member.Converted}}</td><td>{{member.New30Days}}</td><td>{{member.Total?(member.Converted/member.Total*100).toFixed(1)+'%':'—'}}</td><td v-for="key in ['Forms','ApiEngines','Users','ActiveUsers7Days']" :key="key">{{fleet.Team[member.Id]?.Metrics[key]?.Value??'—'}}</td><td>{{fleet.Team[member.Id]?.Readable||0}} / {{member.Total}}</td></tr></tbody></table></div></article><p class="sp-caption">转化状态由授权人员维护。历史租户不会按创建人自动推断推荐归属。用量仅汇总可读租户，未知指标不按0计入。</p></template>
    <template v-if="section==='Links'"><article class="sp-panel"><header><div><h2>我的推广活动</h2><small>推荐人由服务器绑定；停用或更新状态后旧链接失效。</small></div><button class="sp-button primary" @click="showLinkForm=!showLinkForm">＋ 创建链接</button></header>
      <form v-if="showLinkForm" class="sp-form" @submit.prevent="createLink"><label>活动名称<input v-model="linkForm.Title" maxlength="100" required placeholder="例如 客户软件试用邀请" /></label><label>推荐人<select v-model="linkForm.ReferralUserId" required><option v-for="u in users" :key="u.Id" :value="u.Id">{{u.Name||u.Account}}</option></select></label><label>试用天数<input v-model.number="linkForm.TrialDays" type="number" min="1" :max="actor.CanViewAll?90:settings.TrialDays" /></label><label>开通额度<input v-model.number="linkForm.MaxTenants" type="number" min="1" :max="actor.CanViewAll?10000:settings.LinkLimit" /></label><label>链接有效天数<input v-model.number="linkForm.ValidDays" type="number" min="1" max="365" /></label><label>活动说明<input v-model="linkForm.Remark" maxlength="1000" /></label><div class="sp-form-footer"><button type="button" class="sp-button" @click="showLinkForm=false">取消</button><button class="sp-button primary" :disabled="busy">创建</button></div></form>
      <div class="sp-table-scroll"><table><thead><tr><th>活动</th><th>推荐人</th><th>试用天数</th><th>已开通 / 额度</th><th>到期UTC</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="l in links" :key="l.Id"><td><strong>{{l.Title}}</strong><small>{{l.Remark}}</small></td><td>{{users.find(u=>u.Id===l.ReferralUserId)?.Name||'账号已停用'}}</td><td>{{l.TrialDays}}</td><td>{{l.Tenants}} / {{l.MaxTenants}}</td><td>{{l.ExpiresAt}}</td><td>{{Number(l.IsEnable)===1?'启用':'停用'}}</td><td><button class="sp-link" :disabled="busy||Number(l.IsEnable)!==1" @click="showShare(l)">分享</button><button class="sp-link" :disabled="busy" @click="toggle(l)">{{Number(l.IsEnable)===1?'停用':'重新启用'}}</button></td></tr></tbody></table></div><p v-if="!links.length" class="sp-empty">创建推广链接后，客户无需登录即可申请空库。</p>
      <section v-if="share" class="sp-share"><img :src="qr" width="200" height="200" alt="推广开通二维码" /><div><h3>分享给潜在客户</h3><label>专属开通地址<textarea :value="share" readonly rows="4"></textarea></label><div class="sp-inline"><button class="sp-button primary" @click="copy">复制地址</button><a class="sp-button" :href="share" target="_blank" rel="noopener noreferrer">预览开通页 ↗</a><a class="sp-button" :href="qr" download="SaaS试用邀请.png">下载二维码</a></div></div></section></article>
      <article class="sp-panel"><header><h2>最近公开开通申请</h2><small>仅显示所属推广链接的任务</small></header><div class="sp-table-scroll"><table><thead><tr><th>申请</th><th>状态</th><th>进度</th><th>提交时间</th><th>操作</th></tr></thead><tbody><tr v-for="t in tasks" :key="t.Id"><td>{{t.Title}}</td><td>{{({Succeeded:'已开通',Failed:'失败',Running:'开通中',Pending:'排队中',Queued:'排队中',Canceled:'已取消'})[t.Status]||t.Status}}</td><td>{{t.Progress}}%</td><td>{{t.CreateTime}}</td><td><button v-if="t.Status==='Failed'" class="sp-link" :disabled="busy" @click="resumeTask(t)">恢复原申请</button></td></tr></tbody></table></div><p v-if="!tasks.length" class="sp-empty">尚无公开开通申请。</p></article></template>
    <template v-if="section==='Settings'"><article class="sp-panel"><header><h2>公开开通</h2><small>配置仅作用于当前主租户运行分区</small></header><form class="sp-form" @submit.prevent="saveSettings"><label class="sp-checkbox"><input v-model="settings.Enabled" type="checkbox" />启用客户自主空库开通</label><label>主租户 Web 地址<input v-model.trim="settings.WebBase" type="url" required placeholder="https://your-main.example.com" /><small>与业务员分享的主租户访问入口保持一致。</small></label><label>默认试用天数<input v-model.number="settings.TrialDays" type="number" min="1" max="90" required /></label><label>每日公开开通上限<input v-model.number="settings.DailyLimit" type="number" min="1" max="10000" required /></label><label>每个链接默认开通额度<input v-model.number="settings.LinkLimit" type="number" min="1" max="10000" required /></label><fieldset class="sp-wide"><legend>可查看全部推广数据的角色</legend><label v-for="r in roles" :key="r.Id" class="sp-checkbox"><input v-model="settings.ManagerRoleIds" type="checkbox" :value="r.Id" />{{r.Name}}</label><p class="sp-caption">业务员授予“推广中心”菜单即可查看自己的记录。管理角色还需菜单权限；只有平台管理员可以修改本页。</p></fieldset><div class="sp-wide sp-note">公开开通始终验证图形验证码，并按每日、链接与来源网络限制提交。试用期限用于跟进统计；应用授权和付费许可仍按平台授权规则执行。</div><div class="sp-form-footer"><button class="sp-button primary" :disabled="busy">保存配置</button></div></form></article></template>
  </template></section>
  <div v-if="detail" class="sp-overlay" @click.self="detail=null"><section class="sp-detail" role="dialog" aria-modal="true" aria-labelledby="saas-detail-title"><header><div><small>{{detail.OsClient}} · {{detail.ReferralUserName}}</small><h2 id="saas-detail-title">{{detail.ClientName||detail.OsClient}}</h2></div><button class="sp-button" aria-label="关闭租户详情" @click="detail=null">关闭 ×</button></header><span class="sp-tag" :data-state="detail.TrialState">{{trialLabels[detail.TrialState]}}</span><p>联系人：{{detail.PromotionContact||'未登记'}} · {{detail.PromotionPhone||'未登记电话'}}</p><p>试用：{{detail.TrialStartTime||'未登记'}} 至 {{detail.TrialEndTime||'未登记'}} UTC</p>
    <h3>使用情况 <small>{{detailUsage?.CollectedAt?.slice(0,19).replace('T',' ')||'待采集'}} UTC</small></h3><p v-if="detailUsage?.Message" class="sp-note">{{detailUsage.Message}}</p><div class="sp-usage-grid"><article v-for="(label,key) in usageLabels" :key="key"><span>{{label}}</span><strong>{{detailUsage?.[key]??'—'}}</strong></article></div><p class="sp-caption">最近登录：{{detailUsage?.LastLoginTime||'未记录'}}。近7/30天指标按用户最近一次登录时间统计，不能代表登录次数。</p>
    <details v-if="detailUsage?.LatestLoginUserTrend?.length"><summary>最近一次登录日期分布（近30天）</summary><div class="sp-login-trend" v-for="d in detailUsage.LatestLoginUserTrend" :key="d.Day"><span>{{d.Day}}</span><b>{{d.Users}} 位用户</b></div></details>
    <form class="sp-form" @submit.prevent="saveFollow"><label>推广阶段<select v-model="follow.Stage"><option value="Trial">试用</option><option value="Converted">已转化</option></select></label><label>下次跟进（UTC）<input v-model="follow.NextFollowup" type="datetime-local" step="1" /></label><label class="sp-wide">跟进记录<textarea v-model="follow.Notes" maxlength="5000" rows="4" placeholder="记录客户需求、使用反馈和下次沟通安排"></textarea></label><div class="sp-form-footer"><button class="sp-button primary" :disabled="busy">保存跟进</button></div></form>
    <form v-if="actor.CanViewAll" class="sp-inline" @submit.prevent="assign"><label>分配推荐人<select v-model="follow.ReferralUserId" required><option value="">请选择有效用户</option><option v-for="u in users" :key="u.Id" :value="u.Id">{{u.Name||u.Account}}</option></select></label><button class="sp-button" :disabled="busy">保存归属</button></form>
  </section></div>
</main>
</template>
