<script setup>
import { computed,onMounted,onUnmounted,reactive,ref } from 'vue'
import { configureV8,getContext,subscribeContext } from './microi.js'
import { promotionTheme,safeTaskSnapshot,terminalTask } from './saas-promotion-model.js'
import './saas-promotion.css'
const context=ref(getContext()),loading=ref(true),busy=ref(false),error=ref(''),notice=ref(''),info=ref(null),captcha=ref(''),task=ref(null),result=ref(null)
const form=reactive({TenantKey:'',SystemName:'',ContactName:'',ContactPhone:'',AdminPassword:'',CaptchaId:'',CaptchaValue:'',Website:''})
const query=computed(()=>context.value.route?.query||{}),style=computed(()=>promotionTheme(context.value)),progress=computed(()=>Math.max(0,Math.min(100,Number(task.value?.Progress)||0)))
const storageKey=computed(()=>`Microi:SaasPublicTrial:${context.value.apiBase}:${context.value.osClient}:${String(query.value.ref||'')}:${String(query.value.link||'').slice(-24)}`)
let requestId='',saved=null,timer,alive=true,visible=true,captchaController
const unsubscribe=subscribeContext(c=>{context.value=c})
async function api(Action,data={}) {
  // 公开申请需要完成可信校验和持久入队；有界等待仍保留同一 RequestId，以应对响应丢失后的恢复。
  const V8=configureV8();const r=await V8.ApiEngine.RunDirect('platform-saas-public-trial',{Action,...data}, {auth:false,checkCode:false,silentError:true,timeout:120000});
  if(Number(r?.Code)!==1){const e=new Error(r?.Msg||'公开开通暂不可用。');e.reason=r?.Data?.ReasonCode;throw e}return r.Data
}
function linkParams(){return {ReferralUserId:String(query.value.ref||''),LinkToken:String(query.value.link||'')}}
function persist(){try{sessionStorage.setItem(storageKey.value,JSON.stringify({RequestId:requestId,Task:saved,Draft:{TenantKey:form.TenantKey,SystemName:form.SystemName,ContactName:form.ContactName,ContactPhone:form.ContactPhone}}))}catch{notice.value='当前浏览器不允许保存申请进度，请保留此页面。'}}
async function loadCaptcha(){captchaController?.abort();captchaController=new AbortController();try{
  // Captcha is binary and its identifier is a response header; the compatibility V8 SDK returns only the body.
  const url=new URL('/api/Captcha/GetCaptcha',context.value.apiBase);url.searchParams.set('OsClient',context.value.osClient);
  const timeout=setTimeout(()=>captchaController.abort(),10000);let response;try{response=await fetch(url,{signal:captchaController.signal,cache:'no-store',credentials:'omit',headers:{osclient:context.value.osClient}})}finally{clearTimeout(timeout)}
  if(!response.ok)throw new Error('验证码读取失败。');const id=response.headers.get('captchaid');if(!id)throw new Error('验证码标识不可读，请检查 API 跨域配置。');
  const image=await response.blob();if(captcha.value)URL.revokeObjectURL(captcha.value);captcha.value=URL.createObjectURL(image);form.CaptchaId=id;form.CaptchaValue=''
}catch(e){if(e.name!=='AbortError')error.value=e.message}}
async function bootstrap(){loading.value=true;error.value='';try{
  try{const data=JSON.parse(sessionStorage.getItem(storageKey.value)||'null');if(data){requestId=data.RequestId||'';saved=safeTaskSnapshot(data.Task);Object.assign(form,data.Draft||{})}}catch{}
  if(!requestId)requestId=crypto.randomUUID();
  if(saved){await poll();return}
  info.value=await api('Bootstrap',linkParams());await loadCaptcha()
}catch(e){error.value=e.message}finally{loading.value=false}}
async function submit(){if(busy.value)return;busy.value=true;error.value='';notice.value='';persist();try{
  saved=safeTaskSnapshot(await api('Create',{...linkParams(),RequestId:requestId,...form}));if(!saved)throw new Error('任务回执不完整，请保留相同申请编号重试。');
  form.AdminPassword='';form.CaptchaValue='';persist();task.value={Status:'Pending',Progress:0};await poll()
}catch(e){error.value=e.message;await loadCaptcha()}finally{busy.value=false}}
async function poll(){clearTimeout(timer);if(!saved||!alive)return;try{const data=await api('Progress',{RequestId:saved.RequestId,ProgressToken:saved.ProgressToken});if(!alive)return;task.value=data;result.value=data.Status==='Succeeded'?data.Result:null;error.value='';if(!terminalTask(data.Status)&&visible&&!document.hidden)timer=setTimeout(poll,3000)}catch(e){if(!alive)return;error.value='申请状态暂未读取成功。'+e.message;if(visible&&!document.hidden)timer=setTimeout(poll,10000)}}
function lifecycle(e){visible=e.detail?.appState!=='afterhidden';if(visible&&saved&&!terminalTask(task.value?.Status))poll();else clearTimeout(timer)}
function visibility(){visible=!document.hidden;if(visible&&saved&&!terminalTask(task.value?.Status))poll();else clearTimeout(timer)}
function fresh(){saved=null;task.value=null;result.value=null;requestId=crypto.randomUUID();try{sessionStorage.removeItem(storageKey.value)}catch{};Object.assign(form,{TenantKey:'',SystemName:'',ContactName:'',ContactPhone:'',AdminPassword:'',CaptchaValue:''});bootstrap()}
onMounted(()=>{bootstrap();window.addEventListener('appstate-change',lifecycle);document.addEventListener('visibilitychange',visibility)})
onUnmounted(()=>{alive=false;clearTimeout(timer);captchaController?.abort();if(captcha.value)URL.revokeObjectURL(captcha.value);form.AdminPassword='';unsubscribe();window.removeEventListener('appstate-change',lifecycle);document.removeEventListener('visibilitychange',visibility)})
</script>
<template>
<main class="saas-promotion sp-public" data-mci-ui-root="microi-platform-service" :data-theme="context.themeMode" :style="style">
<section class="sp-public-intro"><span class="sp-brand-icon">↗</span><small>开启您的专属软件空间</small><h1>{{context.systemShortTitle||context.systemTitle||info?.Title||'软件试用'}}<br><em>从这里开始</em></h1><p>独立租户、独立数据库。无需先登录，填写信息即可申请开通标准空库，随后使用自己的管理员账号开始配置。</p><div class="sp-public-benefits"><div><b>01</b><span>填写开通信息<small>专属系统名称与租户标识</small></span></div><div><b>02</b><span>后台自动准备<small>实时查看申请进度</small></span></div><div><b>03</b><span>进入您的空间<small>使用 admin 与您设置的密码</small></span></div></div><p v-if="info" class="sp-public-campaign">{{info.Campaign}} · {{info.TrialDays}} 天试用跟进期</p></section>
<section class="sp-public-card"><p v-if="error" class="sp-alert" role="alert">{{error}}</p><p v-if="notice" class="sp-notice" role="status">{{notice}}</p>
  <section v-if="loading" class="sp-skeleton" aria-busy="true" aria-label="正在验证开通入口"><b></b></section>
  <template v-else-if="saved"><header><h2>{{task?.Status==='Succeeded'?'您的空间已准备好':task?.Status==='Failed'?'本次开通未完成':'正在准备您的空间'}}</h2><p>申请编号 {{saved.RequestId}}</p></header><div class="sp-public-progress" role="progressbar" :aria-valuenow="progress" aria-valuemin="0" aria-valuemax="100"><i :style="{width:progress+'%'}"></i></div><div class="sp-stats-line"><span>{{({Pending:'排队中',Queued:'排队中',Running:'开通中',Succeeded:'已完成',Failed:'失败',Canceled:'已取消'})[task?.Status]||'正在读取状态'}}</span><b>{{progress}}%</b></div><p class="sp-caption">{{task?.Message||'申请已进入持久任务队列，可刷新本页继续查看进度。'}}</p><p v-if="task?.HeartbeatTime" class="sp-caption">最近更新：{{task.HeartbeatTime}}</p>
  <section v-if="result" class="sp-public-success"><span>✓</span><h3>{{result.SystemName}}</h3><p>租户标识：{{result.OsClient}}</p><p>管理员账号：{{result.AdminAccount||'admin'}}</p><p>密码：您在申请时设置的密码</p><a v-if="result.LaunchUrl" class="sp-button primary" :href="result.LaunchUrl" target="_blank" rel="noopener noreferrer">进入系统 ↗</a><p class="sp-caption">当前使用主租户提供的启动地址。独立域名需联系推荐人另行绑定。</p></section>
  <div class="sp-inline"><button v-if="task?.Status==='Failed'||task?.Status==='Canceled'" class="sp-button" @click="fresh">填写新的申请</button><button v-if="!terminalTask(task?.Status)" class="sp-button" @click="poll">刷新进度</button></div></template>
  <form v-else-if="info" class="sp-form" @submit.prevent="submit"><header class="sp-wide"><h2>开通专属空库</h2><p class="sp-caption">请保管好管理员密码。开通信息将提供给推荐人用于试用服务。</p></header><label class="sp-wide">系统名称<input v-model.trim="form.SystemName" name="systemName" required maxlength="100" placeholder="例如：星辰客户管理系统" autocomplete="organization" /></label><label class="sp-wide">租户唯一标识<input v-model.trim="form.TenantKey" name="tenantKey" required pattern="[A-Za-z][A-Za-z0-9_-]{2,49}" minlength="3" maxlength="50" placeholder="例如：xingchen_crm" autocomplete="off" /><small>3–50位，英文字母开头，可含数字、下划线和短横线。</small></label><label>联系人<input v-model.trim="form.ContactName" name="contactName" required maxlength="60" autocomplete="name" /></label><label>联系电话<input v-model.trim="form.ContactPhone" name="contactPhone" type="tel" required pattern="[0-9+ ()-]{6,32}" autocomplete="tel" /></label><label class="sp-wide">管理员密码<input v-model="form.AdminPassword" name="adminPassword" type="password" required minlength="10" maxlength="128" autocomplete="new-password" placeholder="至少10位，请妥善保存" /><small>用于新租户 admin 账号。系统不会展示或发送此密码。</small></label><label class="sp-wide">图形验证码<div class="sp-captcha"><input v-model.trim="form.CaptchaValue" name="captchaValue" required maxlength="12" autocomplete="off" /><button type="button" aria-label="刷新图形验证码" @click="loadCaptcha"><img v-if="captcha" :src="captcha" alt="图形验证码，点击刷新" /><span v-else>点击获取</span></button></div></label><label class="sp-honeypot" aria-hidden="true">Website<input v-model="form.Website" tabindex="-1" autocomplete="off" /></label><div class="sp-form-footer"><button class="sp-button primary sp-wide-button" :disabled="busy||!captcha">{{busy?'正在登记申请…':'创建我的专属空间 →'}}</button></div><p class="sp-wide sp-caption">开通标准空库，应用与业务内容可在登录后安装。试用跟进期结束后的使用与授权安排，请联系推荐人。</p></form>
  <section v-else class="sp-empty"><h2>此开通链接暂不可用</h2><p>请联系推荐人获取有效链接。</p><button class="sp-button" @click="bootstrap">重新验证</button></section>
</section></main>
</template>
<style scoped>
.sp-public{display:grid;grid-template-columns:1fr 1fr;gap:70px;align-items:center;min-height:100vh;padding:60px max(35px,calc((100vw - 1100px)/2));background:radial-gradient(ellipse at 5% 0%,color-mix(in srgb,var(--sp-primary) 11%,transparent),transparent 60%),var(--sp-bg)}.sp-public-intro>.sp-brand-icon{margin-bottom:35px;width:50px;height:50px}.sp-public-intro>small{color:var(--sp-primary-text);letter-spacing:2px}.sp-public-intro h1{font-size:39px;line-height:1.35;margin:14px 0 21px;font-weight:750}.sp-public-intro em{font-style:normal;color:var(--sp-primary-text)}.sp-public-intro>p{color:var(--sp-muted);line-height:1.9;font-size:14px}.sp-public-benefits{display:grid;gap:20px;margin:35px 0}.sp-public-benefits>div{display:flex;align-items:center;gap:14px}.sp-public-benefits b{font-size:14px;color:var(--sp-primary-text);background:color-mix(in srgb,var(--sp-primary) 11%,transparent);width:38px;height:38px;border-radius:11px;display:grid;place-content:center}.sp-public-benefits span{font-size:14px;font-weight:650}.sp-public-benefits small{display:block;font-weight:400;margin-top:2px}.sp-public-campaign{font-size:12px!important}.sp-public-card{min-width:0;padding:32px;border:1px solid var(--sp-border);border-radius:22px;background:var(--sp-surface);box-shadow:0 18px 65px #1a34530a}.sp-public-card>header p{color:var(--sp-muted);font-size:11px;overflow-wrap:anywhere;margin-top:10px}.sp-public-card .sp-form{margin:0;gap:18px}.sp-public-card .sp-alert{margin-bottom:14px}.sp-captcha{display:flex;align-items:center;gap:12px}.sp-captcha input{min-width:0}.sp-captcha button{background:var(--sp-bg);border:1px solid var(--sp-border);border-radius:8px;width:125px;height:39px;flex:none;overflow:hidden;padding:0}.sp-captcha img{display:block;width:100%;height:100%;object-fit:contain}.sp-wide-button{width:100%;min-height:44px!important}.sp-honeypot{position:absolute;left:-10000px;width:1px;height:1px;overflow:hidden}.sp-public-progress{height:9px;border-radius:8px;background:var(--sp-bg);overflow:hidden;margin:25px 0 10px}.sp-public-progress i{display:block;height:100%;background:var(--sp-primary);transition:width .3s}.sp-public-success{padding:25px 0;display:grid;gap:9px}.sp-public-success>span{color:#1b9d74;font-size:36px}.sp-public-success .sp-button{margin-top:12px}.sp-public-success p{font-size:13px;overflow-wrap:anywhere}@media(max-width:900px){.sp-public{gap:30px;padding:35px;grid-template-columns:1fr 1.2fr}.sp-public-intro h1{font-size:30px}.sp-public-card{padding:23px}}@media(max-width:600px){.sp-public{display:block;padding:23px 16px;min-height:100%}.sp-public-intro>.sp-brand-icon{margin-bottom:16px}.sp-public-intro h1{font-size:27px;margin:10px 0 13px}.sp-public-intro>p{font-size:12px}.sp-public-benefits{display:none}.sp-public-card{margin-top:24px;padding:22px 18px}.sp-public-campaign{margin-top:12px!important}}@media(prefers-reduced-motion:reduce){.sp-public-progress i{transition:none}}
</style>
