//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dos.ORM;using System;


namespace Microi.net
{
	/// <summary>
	/// 实体类SysBaseData。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Sys_BaseData")]
	[Serializable]
	public partial class SysBaseData : Entity
	{
		#region Model
		private string _Id;
		private string _Key;
		private string _Value;
		private string _ParentId;
		private string _ParentKey;
		private int _Sort;
		private string _Remark;
		private DateTime _CreateTime;
		private string _Customer;
		private int _IsDeleted;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public string Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Key")]
		public string Key
		{
			get { return _Key; }
			set
			{
				this.OnPropertyValueChange("Key");
				this._Key = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Value")]
		public string Value
		{
			get { return _Value; }
			set
			{
				this.OnPropertyValueChange("Value");
				this._Value = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ParentId")]
		public string ParentId
		{
			get { return _ParentId; }
			set
			{
				this.OnPropertyValueChange("ParentId");
				this._ParentId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ParentKey")]
		public string ParentKey
		{
			get { return _ParentKey; }
			set
			{
				this.OnPropertyValueChange("ParentKey");
				this._ParentKey = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Sort")]
		public int Sort
		{
			get { return _Sort; }
			set
			{
				this.OnPropertyValueChange("Sort");
				this._Sort = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get { return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreateTime")]
		public DateTime CreateTime
		{
			get { return _CreateTime; }
			set
			{
				this.OnPropertyValueChange("CreateTime");
				this._CreateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Customer")]
		public string Customer
		{
			get { return _Customer; }
			set
			{
				this.OnPropertyValueChange("Customer");
				this._Customer = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsDeleted")]
		public int IsDeleted
		{
			get { return _IsDeleted; }
			set
			{
				this.OnPropertyValueChange("IsDeleted");
				this._IsDeleted = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Key,
				_.Value,
				_.ParentId,
				_.ParentKey,
				_.Sort,
				_.Remark,
				_.CreateTime,
				_.Customer,
				_.IsDeleted,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Key,
				this._Value,
				this._ParentId,
				this._ParentKey,
				this._Sort,
				this._Remark,
				this._CreateTime,
				this._Customer,
				this._IsDeleted,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Sys_BaseData");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Sys_BaseData", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Key = new Field("Key", "Sys_BaseData", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Value = new Field("Value", "Sys_BaseData", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentId = new Field("ParentId", "Sys_BaseData", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentKey = new Field("ParentKey", "Sys_BaseData", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sort = new Field("Sort", "Sys_BaseData", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "Sys_BaseData", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "Sys_BaseData", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Customer = new Field("Customer", "Sys_BaseData", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsDeleted = new Field("IsDeleted", "Sys_BaseData", "");
		}
		#endregion
	}
}