//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dos.ORM;using System;


namespace Microi.net
{
	/// <summary>
	/// 实体类SysDept。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("sys_dept")]
	[Serializable]
	public partial class SysDept : Entity
	{
		#region Model
		private string _Id;
		private string _ParentId;
		private string _Name;
		private string _Code;
		private DateTime _CreateTime;
		private DateTime _UpdateTime;
		private string _Remark;
		private int _IsDeleted;
		private int _Sort;
		private int _State;

		private string _TenantName;
		private string _TenantId;
        /// <summary>
        /// 
        /// </summary>
        [Field("TenantName")]
        public string TenantName
        {
            get { return _TenantName; }
            set
            {
                this.OnPropertyValueChange("TenantName");
                this._TenantName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TenantId")]
        public string TenantId
        {
            get { return _TenantId; }
            set
            {
                this.OnPropertyValueChange("TenantId");
                this._TenantId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Field("Id")]
		public string Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ParentId")]
		public string ParentId
		{
			get { return _ParentId; }
			set
			{
				this.OnPropertyValueChange("ParentId");
				this._ParentId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get { return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Code")]
		public string Code
		{
			get { return _Code; }
			set
			{
				this.OnPropertyValueChange("Code");
				this._Code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreateTime")]
		public DateTime CreateTime
		{
			get { return _CreateTime; }
			set
			{
				this.OnPropertyValueChange("CreateTime");
				this._CreateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UpdateTime")]
		public DateTime UpdateTime
		{
			get { return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange("UpdateTime");
				this._UpdateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get { return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsDeleted")]
		public int IsDeleted
		{
			get { return _IsDeleted; }
			set
			{
				this.OnPropertyValueChange("IsDeleted");
				this._IsDeleted = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Sort")]
		public int Sort
		{
			get { return _Sort; }
			set
			{
				this.OnPropertyValueChange("Sort");
				this._Sort = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("State")]
		public int State
		{
			get { return _State; }
			set
			{
				this.OnPropertyValueChange("State");
				this._State = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ParentId,
				_.Name,
				_.Code,
				_.CreateTime,
				_.UpdateTime,
				_.Remark,
				_.IsDeleted,
				_.Sort,
				_.State,
                _.TenantName,
                _.TenantId,
            };
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ParentId,
				this._Name,
				this._Code,
				this._CreateTime,
				this._UpdateTime,
				this._Remark,
				this._IsDeleted,
				this._Sort,
				this._State,
                this._TenantName,
                this._TenantId,
            };
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "sys_dept");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "sys_dept", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentId = new Field("ParentId", "sys_dept", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "sys_dept", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Code = new Field("Code", "sys_dept", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "sys_dept", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime", "sys_dept", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "sys_dept", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsDeleted = new Field("IsDeleted", "sys_dept", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sort = new Field("Sort", "sys_dept", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State", "sys_dept", "");
            public readonly static Field TenantName = new Field("TenantName", "sys_dept", "");
            public readonly static Field TenantId = new Field("TenantId", "sys_dept", "");
        }
		#endregion
	}
}