//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dos.ORM;using System;


namespace Microi.net
{
	/// <summary>
	/// 实体类SysLog。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("SysLog")]
	[Serializable]
	public partial class SysLog
	{
		public string Id { get; set; }
		public string EventId { get; set; }
		public string SessionId { get; set; }
		public string Category { get; set; }
		public string Action { get; set; }
		public string Source { get; set; }
		public string ClientType { get; set; }
		public string Did { get; set; }
		public string TargetType { get; set; }
		public string TargetId { get; set; }
		public long? DurationSeconds { get; set; }
		public bool? Success { get; set; }
		public string TraceId { get; set; }
		public string SpanId { get; set; }
		public string ParentSpanId { get; set; }
		public string TraceFlags { get; set; }
		public string ServiceName { get; set; }
		public string ServiceVersion { get; set; }
		public string NodeId { get; set; }
		public string Environment { get; set; }
		public double? DurationMs { get; set; }
		public int? HttpStatusCode { get; set; }
		public DateTime? OccurredAt { get; set; }
		public string AppId { get; set; }
		public string Api { get; set; }
		public string Param { get; set; }
		public string Type { get; set; }
		public string UserId { get; set; }
		public string UserName { get; set; }
		public string Title { get; set; }
		public string Content { get; set; }
		public DateTime CreateTime { get; set; }
		public string IP { get; set; }
		public string Mac { get; set; }
		public string OtherInfo { get; set; }
		public string Remark { get; set; }
		public int? Level { get; set; }
		public int? Timer { get; set; }
	}
}
