//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dos.ORM;
using System;

namespace Microi.net
{
    /// <summary>
    /// 实体类SysRoleLimit。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_RoleLimit")]
    [Serializable]
    public partial class SysRoleLimit : Entity
    {
        #region Model
		private string _Id;
		private string _RoleId;
		private string _FkId;
		private string _Type;
		private DateTime _CreateTime;
		private string _Customer;
		private string _Permission;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public string Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RoleId")]
		public string RoleId
		{
			get{ return _RoleId; }
			set
			{
				this.OnPropertyValueChange("RoleId");
				this._RoleId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FkId")]
		public string FkId
		{
			get{ return _FkId; }
			set
			{
				this.OnPropertyValueChange("FkId");
				this._FkId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Type")]
		public string Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange("Type");
				this._Type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreateTime")]
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange("CreateTime");
				this._CreateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Customer")]
		public string Customer
		{
			get{ return _Customer; }
			set
			{
				this.OnPropertyValueChange("Customer");
				this._Customer = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Permission")]
		public string Permission
		{
			get{ return _Permission; }
			set
			{
				this.OnPropertyValueChange("Permission");
				this._Permission = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.RoleId,
				_.FkId,
				_.Type,
				_.CreateTime,
				_.Customer,
				_.Permission,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._RoleId,
				this._FkId,
				this._Type,
				this._CreateTime,
				this._Customer,
				this._Permission,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Sys_RoleLimit");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Sys_RoleLimit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field RoleId = new Field("RoleId", "Sys_RoleLimit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FkId = new Field("FkId", "Sys_RoleLimit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type", "Sys_RoleLimit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "Sys_RoleLimit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Customer = new Field("Customer", "Sys_RoleLimit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Permission = new Field("Permission", "Sys_RoleLimit", "");
        }
        #endregion
	}
}