//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Dos.ORM;using System;


namespace Microi.net
{
	/// <summary>
	/// 实体类SysRole。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Sys_Role")]
	[Serializable]
	public partial class SysRole : Entity
	{
		#region Model
		private string _Id;
		private string _Name;
		private DateTime _CreateTime;
		private DateTime _UpdateTime;
		private int? _Sort;
		private string _Class;
		private string _BaseLimit;
		private int _IsDeleted;
		private string _Remark;
		private int _Level;
		private string _DeptIds;

        private string _TenantName;
        private string _TenantId;
        /// <summary>
        /// 
        /// </summary>
        [Field("TenantName")]
        public string TenantName
        {
            get { return _TenantName; }
            set
            {
                this.OnPropertyValueChange("TenantName");
                this._TenantName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TenantId")]
        public string TenantId
        {
            get { return _TenantId; }
            set
            {
                this.OnPropertyValueChange("TenantId");
                this._TenantId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Field("Id")]
		public string Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get { return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreateTime")]
		public DateTime CreateTime
		{
			get { return _CreateTime; }
			set
			{
				this.OnPropertyValueChange("CreateTime");
				this._CreateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UpdateTime")]
		public DateTime UpdateTime
		{
			get { return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange("UpdateTime");
				this._UpdateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Sort")]
		public int? Sort
		{
			get { return _Sort; }
			set
			{
				this.OnPropertyValueChange("Sort");
				this._Sort = value;
			}
		}
		/// <summary>
		/// 就是Customer
		/// </summary>
		[Field("Class")]
		public string Class
		{
			get { return _Class; }
			set
			{
				this.OnPropertyValueChange("Class");
				this._Class = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BaseLimit")]
		public string BaseLimit
		{
			get { return _BaseLimit; }
			set
			{
				this.OnPropertyValueChange("BaseLimit");
				this._BaseLimit = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsDeleted")]
		public int IsDeleted
		{
			get { return _IsDeleted; }
			set
			{
				this.OnPropertyValueChange("IsDeleted");
				this._IsDeleted = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get { return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Level")]
		public int Level
		{
			get { return _Level; }
			set
			{
				this.OnPropertyValueChange("Level");
				this._Level = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptIds")]
		public string DeptIds
		{
			get { return _DeptIds; }
			set
			{
				this.OnPropertyValueChange("DeptIds");
				this._DeptIds = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Name,
				_.CreateTime,
				_.UpdateTime,
				_.Sort,
				_.Class,
				_.BaseLimit,
				_.IsDeleted,
				_.Remark,
				_.Level,
				_.DeptIds,
                _.TenantName,
                _.TenantId,
            };
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Name,
				this._CreateTime,
				this._UpdateTime,
				this._Sort,
				this._Class,
				this._BaseLimit,
				this._IsDeleted,
				this._Remark,
				this._Level,
				this._DeptIds,
                this._TenantName,
                this._TenantId,
            };
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Sys_Role");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Sys_Role", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "Sys_Role", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "Sys_Role", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime", "Sys_Role", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sort = new Field("Sort", "Sys_Role", "");
			/// <summary>
			/// 就是Customer
			/// </summary>
			public readonly static Field Class = new Field("Class", "Sys_Role", "就是Customer");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BaseLimit = new Field("BaseLimit", "Sys_Role", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsDeleted = new Field("IsDeleted", "Sys_Role", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "Sys_Role", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Level = new Field("Level", "Sys_Role", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptIds = new Field("DeptIds", "Sys_Role", "");
            public readonly static Field TenantName = new Field("TenantName", "Sys_Role", "");
            public readonly static Field TenantId = new Field("TenantId", "Sys_Role", "");
        }
		#endregion
	}
}