//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Microi.net
{
	/// <summary>
	/// 实体类SysUser。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Sys_User")]
	[Serializable]
	public partial class SysUser : Entity
	{
		#region Model
		private string _Id;
		private string _No;
		private string _Account;
		private string _Pwd;
		private string _Name;
		private string _DeptId;
		private string _DeptName;
		private string _DeptCode;
		private string _DeptIds;
		private string _RoleIds;
		private DateTime _CreateTime;
		private DateTime? _UpdateTime;
		private string _Phone;
		private int _State;
		private string _Remark;
		private string _Avatar;
		private string _Sex;
		private string _Email;
		private int _IsDeleted;
		private int _Level;

        private string _TenantName;
        private string _TenantId;
        /// <summary>
        /// 
        /// </summary>
        [Field("TenantName")]
        public string TenantName
        {
            get { return _TenantName; }
            set
            {
                this.OnPropertyValueChange("TenantName");
                this._TenantName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TenantId")]
        public string TenantId
        {
            get { return _TenantId; }
            set
            {
                this.OnPropertyValueChange("TenantId");
                this._TenantId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Field("Id")]
		public string Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("No")]
		public string No
		{
			get { return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Account")]
		public string Account
		{
			get { return _Account; }
			set
			{
				this.OnPropertyValueChange("Account");
				this._Account = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pwd")]
		public string Pwd
		{
			get { return _Pwd; }
			set
			{
				this.OnPropertyValueChange("Pwd");
				this._Pwd = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get { return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 所属机构的最后一个Id
		/// </summary>
		[Field("DeptId")]
		public string DeptId
		{
			get { return _DeptId; }
			set
			{
				this.OnPropertyValueChange("DeptId");
				this._DeptId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptName")]
		public string DeptName
		{
			get { return _DeptName; }
			set
			{
				this.OnPropertyValueChange("DeptName");
				this._DeptName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptCode")]
		public string DeptCode
		{
			get { return _DeptCode; }
			set
			{
				this.OnPropertyValueChange("DeptCode");
				this._DeptCode = value;
			}
		}
		/// <summary>
		/// 包含所有所属机构Id
		/// </summary>
		[Field("DeptIds")]
		public string DeptIds
		{
			get { return _DeptIds; }
			set
			{
				this.OnPropertyValueChange("DeptIds");
				this._DeptIds = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RoleIds")]
		public string RoleIds
		{
			get { return _RoleIds; }
			set
			{
				this.OnPropertyValueChange("RoleIds");
				this._RoleIds = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreateTime")]
		public DateTime CreateTime
		{
			get { return _CreateTime; }
			set
			{
				this.OnPropertyValueChange("CreateTime");
				this._CreateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UpdateTime")]
		public DateTime? UpdateTime
		{
			get { return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange("UpdateTime");
				this._UpdateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Phone")]
		public string Phone
		{
			get { return _Phone; }
			set
			{
				this.OnPropertyValueChange("Phone");
				this._Phone = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("State")]
		public int State
		{
			get { return _State; }
			set
			{
				this.OnPropertyValueChange("State");
				this._State = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get { return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Avatar")]
		public string Avatar
		{
			get { return _Avatar; }
			set
			{
				this.OnPropertyValueChange("Avatar");
				this._Avatar = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Sex")]
		public string Sex
		{
			get { return _Sex; }
			set
			{
				this.OnPropertyValueChange("Sex");
				this._Sex = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Email")]
		public string Email
		{
			get { return _Email; }
			set
			{
				this.OnPropertyValueChange("Email");
				this._Email = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsDeleted")]
		public int IsDeleted
		{
			get { return _IsDeleted; }
			set
			{
				this.OnPropertyValueChange("IsDeleted");
				this._IsDeleted = value;
			}
		}
		/// <summary>
		/// 值越大，权限越大
		/// </summary>
		[Field("Level")]
		public int Level
		{
			get { return _Level; }
			set
			{
				this.OnPropertyValueChange("Level");
				this._Level = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.No,
				_.Account,
				_.Pwd,
				_.Name,
				_.DeptId,
				_.DeptName,
				_.DeptCode,
				_.DeptIds,
				_.RoleIds,
				_.CreateTime,
				_.UpdateTime,
				_.Phone,
				_.State,
				_.Remark,
				_.Avatar,
				_.Sex,
				_.Email,
				_.IsDeleted,
				_.Level,
				_.TenantName,
				_.TenantId,
            };
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._No,
				this._Account,
				this._Pwd,
				this._Name,
				this._DeptId,
				this._DeptName,
				this._DeptCode,
				this._DeptIds,
				this._RoleIds,
				this._CreateTime,
				this._UpdateTime,
				this._Phone,
				this._State,
				this._Remark,
				this._Avatar,
				this._Sex,
				this._Email,
				this._IsDeleted,
				this._Level,
				this._TenantName,
				this._TenantId,
            };
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Sys_User");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field No = new Field("No", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Account = new Field("Account", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pwd = new Field("Pwd", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "Sys_User", "");
			/// <summary>
			/// 所属机构的最后一个Id
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "Sys_User", "所属机构的最后一个Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptName = new Field("DeptName", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode", "Sys_User", "");
			/// <summary>
			/// 包含所有所属机构Id
			/// </summary>
			public readonly static Field DeptIds = new Field("DeptIds", "Sys_User", "包含所有所属机构Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RoleIds = new Field("RoleIds", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Phone = new Field("Phone", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Avatar = new Field("Avatar", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sex = new Field("Sex", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Email = new Field("Email", "Sys_User", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsDeleted = new Field("IsDeleted", "Sys_User", "");
			/// <summary>
			/// 值越大，权限越大
			/// </summary>
			public readonly static Field Level = new Field("Level", "Sys_User", "值越大，权限越大");
			public readonly static Field TenantName = new Field("TenantName", "Sys_User", "");
			public readonly static Field TenantId = new Field("TenantId", "Sys_User", "");
        }
        #endregion
    }
}